src/libraries/Microsoft.PowerFx.Core/Microsoft.PowerFx.Core.csproj, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryDate.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Date.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/mathfuncs.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/FileExpressionEvaluationTests.cs
A very basic implementation for custom string formats for the Text() function. 
Changes to the .csproj file were so that it's possible to add these projects to other solutions and make them project references to allow for editing and debugging across other projects that depend on these. 
Also added one small change to the LibraryDate.cs to get one more test to pass that was part of a Text() test.
=> Basic implementation of custom format strings for Text() function.

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Value.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/FileExpressionEvaluationTests.cs
Fixes 4 failing tests in the Value function
=> Fix skipped tests for the Value function

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryMath.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUnary.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/BasicCoercion.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/mathfuncs.txt
Failing/Skipped test count is down to 15
=> Fix failing tests in Mod, Average, TextToBoolean

src/libraries/Microsoft.PowerFx.Core/Functions/BuiltinFunction.cs, src/libraries/Microsoft.PowerFx.Core/IR/IRNodeVisitor.cs, src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/libraries/Microsoft.PowerFx.Core/IR/Nodes/AggregateCoercionNode.cs, src/libraries/Microsoft.PowerFx.Core/IR/Nodes/UnaryOpNode.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/CommonErrors.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUnary.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ArgCoercion.txt
2 new tests are passing related to the CharT function
=> Add TableToTable aggregate coercion support, new IR node

src/tests/Microsoft.PowerFx.Core.Tests/LexerTests.cs
#54 reminded me we needed these tests moved over.
=> Move LexerTests over to PowerFx repo

src/libraries/Microsoft.PowerFx.Core/Microsoft.PowerFx.Core.csproj, src/libraries/Microsoft.PowerFx.Interpreter/Microsoft.PowerFx.Interpreter.csproj, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Microsoft.PowerFx.LanguageServerProtocol.csproj
Updates `System.Text.Json` to the version `5.0.2` across all projects.
=> Update System.Text.Json to 5.0.2

src/strings/en-US/PowerFxResources.resw, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Blank.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Date.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Sql.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Value.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/mathfuncs.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/string.txt
Add error messages for invalid return type scenarios for SQL
Update test files to indicate current support for SQL execution
=> Add error messages for invalid return type, update test files

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryDate.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Date.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/TimeTests.cs
Added TimeZoneOffset function and extended the Text function formatting strings to handle more options for date/time formatting and to handle input locale. Also added a new unit test class test test TimeZoneOffset that can't be tested easily in a .txt file input as the result depends on the time zone the test is running within.
=> Time Zone Offset

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/StandardErrorHandling.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ArgCoercion.txt
Failing/Skipped test count is down to 11
=> Add a generic table function, add support for LenT

src/libraries/Microsoft.PowerFx.Core/App/Controls/PropertyRuleCategory.cs
A follow up to https://github.com/microsoft/Power-Fx/pull/74.
=> Updated IsValid in PropertyRuleCategory

src/libraries/Microsoft.PowerFx.Core/FeatureFlags.cs, src/libraries/Microsoft.PowerFx.Core/Lexer/TexlLexer.cs, src/libraries/Microsoft.PowerFx.Core/Lexer/TokKind.cs, src/libraries/Microsoft.PowerFx.Core/Lexer/Tokens/IdentToken.cs, src/libraries/Microsoft.PowerFx.Core/Lexer/Tokens/IslandEndToken.cs, src/libraries/Microsoft.PowerFx.Core/Lexer/Tokens/IslandStartToken.cs, src/libraries/Microsoft.PowerFx.Core/Lexer/Tokens/StrInterpEndToken.cs, src/libraries/Microsoft.PowerFx.Core/Lexer/Tokens/StrInterpStartToken.cs, src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs, src/libraries/Microsoft.PowerFx.Core/Public/ExpressionError.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Visitors/FindNodeVisitor.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Concatenate.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/string.txt, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs, src/tests/Microsoft.PowerFx.Core.Tests/LexerTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/PowerFxEvaluationTests.cs
Draft PR demonstrating the Lexer changes to add String Interpolation to PowerFx.
=> Initial Lexer changes to support String Interpolation

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/mathfuncs.txt
Implemented the IsNumeric function and added unit tests in math.txt file. Followed pattern used in IsBlank to also expose a public static function that returns a bool directly rather than a FormulaValue as a BooleanValue.
=> Implement IsNumeric function and add unit tests.

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/libraries/Microsoft.PowerFx.Core/IR/Nodes/BinaryOpKind.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryCustomObject.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/CustomObject.txt
Example of working dot operator for CustomObjects. Error messages and tests still need work.
=> Initial working dot operator for CustomObjects

src/libraries/Microsoft.PowerFx.Core/Public/ErrorKind.cs, src/libraries/Microsoft.PowerFx.Core/Types/Enums/EnumStore.cs, src/strings/en-US/PowerFxResources.resw
Reverts microsoft/Power-Fx#108
=> Revert "Add new error kind enum value (canceled)"

src/libraries/Microsoft.PowerFx.Core/Syntax/NamedFormulas.cs, src/tests/Microsoft.PowerFx.Core.Tests/NamedFormulasTests.cs
Changed GetFormulas to GetNamedFormulas with a Tuple return type and returning a DName as well as a formula.
=> Changed GetFormulas to GetNamedFormulas

src/libraries/Microsoft.PowerFx.Core/Public/ErrorKind.cs, src/libraries/Microsoft.PowerFx.Core/Types/Enums/EnumStore.cs, src/strings/en-US/PowerFxResources.resw
New error kind to be used for errors generated due to internal issues in the Power Fx functions.
=> Add new error kind enum value (Internal)

src/tests/Microsoft.PowerFx.Core.Tests/FormatterTests.cs
Required prerequisite commit before String Interpolation pretty/structural print changes.
=> Migrate FormatterTests to PowerFx

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/CountIf.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Lookup.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/CountFunctions.txt
This reverts commit 12b87ac778002a64440b1ace13c507cf237c5f56.
=> Revert "Allow CountIf and LookUp to coerce yes/no to Boolean (#187)"

src/libraries/Microsoft.PowerFx.LanguageServerProtocol/JsonRpc/JsonRpcHelper.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/LanguageServer/LanguageServer.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/JsonRpcError.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/LanguageServerTests.cs
Fixes https://github.com/microsoft/Power-Fx/issues/251
Fix some protocol bugs.
=> Add hook for logging unhandled exception.

src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestHelpers/BaseRunner.cs, src/tests/Microsoft.PowerFx.Core.Tests/TestRunnerTests/TestRunnerTests.cs
Needed for allowing large number expressions like  Exp(430)
=> Better numeric comparison.

src/strings/en-US/PowerFxResources.resw
Added descriptions for the DateTime arguments.
=> Add missing resources from DateTime function

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Entities/External/IExternalDataSource.cs, src/libraries/Microsoft.PowerFx.Core/Entities/External/IExternalEntity.cs, src/libraries/Microsoft.PowerFx.Core/Entities/External/IExternalOptionSet.cs, src/libraries/Microsoft.PowerFx.Core/Types/DTypeExtensionsCore.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/OptionSet.cs
This is from a comment in #280, deserves to be it's own PR for clarity.
=> All symbols know their type without casting

src/libraries/Microsoft.PowerFx.Core/Functions/Delegation/DelegationStrategies/DelegationValidationStrategy.cs
This function was throwing null reference exceptions in Prod. Note that this change does add a semantic meaning for nulls in the binder for certain nodes, whereas there was no meaning (just an exception) before. We need to make sure that this meaning is correct.
=> Improve null-safety of DelegationValidationStrategy IsValidNode

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryTable.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/FilterFunctions.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
Issue #263. Not sure if I should have included extra test cases.
=> Fixing part of issue #263

src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/CountRows.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt
Untyped Object support for the CountRows function.
=> Implement CountRows_UO function

src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/FilterFunctions.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestHelpers/BaseRunner.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestHelpers/TestRunner.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestHelpers/TestRunnerSummary.cs, src/tests/Microsoft.PowerFx.Core.Tests/TestRunnerTests/TestRunnerTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
Somewhere between #306  and #289, there was a merge that went wrong. This restores the changes from #306 that were lost.
=> Repair Merge of test PRs

src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
Adding the ability to delete formulas from the formula dict.
I'm releasing small pieces of code while still working on the main goal for #308.
=> DeleteFormula implementation

src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryMath.cs, src/libraries/Microsoft.PowerFx.Interpreter/Marshal/ITypeMarshallerProvider.cs, src/libraries/Microsoft.PowerFx.Interpreter/Marshal/TypeMarshallerCacheExtensions.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/tests/Microsoft.PowerFx.Core.Tests/LexerTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/TestRunnerTests/TestRunnerTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/LanguageServerTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ValueTests.cs
Various fixes to get rid of build warnings.
=> Build warning fixes

README.md, src/build/PublishToCoveralls.ps1
Point coverage badge in readme to main branch.
Update coveralls.net reference to 3.0.
=> Finalize code coverage reporting

src/libraries/Microsoft.PowerFx.Interpreter/Marshal/TableMarshallerProvider.cs, src/libraries/Microsoft.PowerFx.Interpreter/ReflectionFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Utility.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/CustomFunctions.cs
Just support all types for PrimitiveValue<T>.
Fixes #69
=> Add other parameter types for custom functions.  

src/libraries/Microsoft.PowerFx.Core/Types/DType.cs
Missed this condition in a related PR: related to PR: https://github.com/microsoft/Power-Fx/pull/370
=> Add Multiselect table type support to leftNode

src/libraries/Directory.Build.props, src/libraries/Microsoft.PowerFx.Core/Microsoft.PowerFx.Core.csproj, src/libraries/Microsoft.PowerFx.Interpreter/Microsoft.PowerFx.Interpreter.csproj, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Microsoft.PowerFx.LanguageServerProtocol.csproj, src/libraries/Microsoft.PowerFx.Transport.Attributes/TransportPropertyAttribute.cs
=> Generate xml docs with usual conventions

src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs, src/tests/Microsoft.PowerFx.Core.Tests/BindingEngineTests.cs
add static overload of Parse function
=> add static overload of Parse function

src/libraries/Microsoft.PowerFx.Core/Public/Types/BindingErrorType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/BlankType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/BooleanType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/ColorType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/DateTimeNoTimeZoneType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/DateTimeType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/DateType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/ExternalType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/FormulaType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/GuidType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/HyperlinkType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/ITypeVisitor.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/NumberType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/OptionSetValueType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/RecordType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/Serialization/FormulaTypeToSchemaConverter.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/StringType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/TableType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/TimeType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/UnknownType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/UnsupportedType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/UntypedObjectType.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs
change spelling of ITypeVistor ro ITypeVisitor
=> spelling on ITypeVisitor

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Boolean.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/StandardErrorHandling.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Boolean.txt
Adds Boolean_T. Also adds both Boolean and Boolean_T number variants. Note that coercion cannot be used here.
=> Add Boolean_T and number variants

src/libraries/Microsoft.PowerFx.Core/IR/BinaryOpMatrix.cs, src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Parser/ParseFormulasResult.cs, src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/BlankType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/BooleanType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/ColorType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/DateTimeNoTimeZoneType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/DateTimeType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/DateType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/FormulaType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/GuidType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/HyperlinkType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/NumberType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/StringType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/TimeType.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/ParsedUDFs.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/NamedFormulasTests.cs
Completed parser changes for UDFs. This relies on another PR to go through so do merge until that PR is merged, but it is functional.
=> Parser Changes for UDF

src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/tests/Microsoft.PowerFx.Core.Tests/DTypeTests.cs
To be used by the JSON function in PowerApps.
=> Add recursive type contains function

src/build/yaml/feed-setup-step.yml, src/build/yaml/powerfx-ci.yml
Fix feed setup.
Remove condition from generate_multiconfig_var job.
Add condition to tagging task.
=> Fix bugs in API validation for forks

src/libraries/Microsoft.PowerFx.Connectors/PowerPlatformConnectorClient.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorClientTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorTests.cs
PowerPlatformConnectorClient will take both sync and async getAuthToken param
Transform API becomes async
=> Make connector GetAuthToken async

src/libraries/Microsoft.PowerFx.Interpreter/Functions/CommonErrors.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Error.txt
- Updated the message
- Added the test for the same
- Fixes #529
=> Ensured consistent error messages (Issue #529)

src/libraries/Microsoft.PowerFx.Core/Public/Config/PowerFxConfig.cs, src/libraries/Microsoft.PowerFx.Core/Public/DisplayNames/RenameDriver.cs, src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/tests/Microsoft.PowerFx.Core.Tests/DisplayNameTests.cs
=> Add tests for Renamer when using globals with display names

src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/tests/Microsoft.PowerFx.Core.Tests/DisplayNameTests.cs
- Updated "SupertypeAggregateCore" to fix display name issue with Aggregate types. (Fixes #549)
- Added tests in "DisplayNameTest" for validation.
=> Updated "SupertypeAggregateCore" to attach Display names. Fixes #549

src/tests/Microsoft.PowerFx.Core.Tests/DNameTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/DPathTests.cs
- Added tests in "DNameTests.cs"
- Test Covers DName and DPath Equality and DPath Append functionality
=> Adds Coverage for DPath, DName equality and DPath append

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Binding/BinderUtils.cs
Dataflow Graph changes to help reduce duplicate code.
=> Initial work on binder refactors for DataflowGraph

src/libraries/Microsoft.PowerFx.Core/Public/Types/AggregateType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/RecordType.cs, src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/tests/Microsoft.PowerFx.Core.Tests/DisplayNameTests.cs
-Added Capability to pass DisplayNameProvider to RecordType via Constructor
-Added Test that passes Implementation of DisplayNameProvider to RecordType and verified it is working as expected.
=> Adds capability to provide DisplayNameProvider for derived RecordType

src/libraries/Microsoft.PowerFx.Core/Public/Config/ReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTableOverRecordType.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/ReadOnlySymbolValues.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SymbolValueTests.cs
Enable helpers to pass the parents.
=> Add some helpers for creating Scopes, used for dataverse.

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/DateTime.cs
The description for the DateTime function is incorrect, this fixes it.
=> Fix description for the DateTime function

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ForAll.txt
-Fixes #647 
-Added test for the issue as well.
=> Fixes #647 Crash for ForAll with two fields

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs
=> Assign default value to properly initialize coercionDifference

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/IScope.cs, src/libraries/Microsoft.PowerFx.Interpreter/SymbolContext.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt
Rename ThisItem to ThisRecord for ForAll_UO, because of a conversation with Greg today.
=> Rename ThisItem to ThisRecord in ForAll_UO

src/libraries/Microsoft.PowerFx.Core/Parser/ParserOptions.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ConfigTests.cs
=> Make CultureInfo of ParserOptions public

src/tests/Microsoft.PowerFx.Interpreter.Tests/DatabaseSimulationTests.cs
Fixes #704 
- Use Async/Await to simplify exception handling  (automatically unwraps aggregate exceptions)
- Split pass/fail cases into 2 separate tests. That let me simplify the logic. 
- avoid specifying a Patch delay in test case.
=> Fix flaky test.

src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/ReflectionFunction.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/CustomFunctions.cs
-Fixes #40 
-Adds capability to register custom async function with Power FX.
=> Adds support for custom asynchronous functions

src/tests/Microsoft.PowerFx.Core.Tests/Helpers/TestUtils.cs, src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs
-Ports Texl Tests from [PAClient ](https://msazure.visualstudio.com/OneAgile/_git/PowerApps-Client?path=/src/Cloud/unittests/DocumentServer.Core.LargeTests/TexlTest.cs&_a=contents&version=GBmaster)to PowerFX
=> Porting TexlTests

src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/libraries/Microsoft.PowerFx.Interpreter/ParsedExpression.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ConfigTests.cs
=> Issue 711 fixes and test cases

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Binding/BinderUtils.cs
This is needed to share logic with Dataflow Analysis work
=> Make FindBestErrorOverload a static helper for Binder

src/libraries/Microsoft.PowerFx.Core/App/ErrorContainers/ErrorContainer.cs, src/libraries/Microsoft.PowerFx.Core/Errors/BaseError.cs, src/libraries/Microsoft.PowerFx.Core/Errors/TexlError.cs, src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs, src/libraries/Microsoft.PowerFx.Core/Public/IntellisenseOperations.cs, src/tests/Microsoft.PowerFx.Core.Tests/BindingEngineTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/FormatterTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/ParseTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/ResourceValidationTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs
=>  Switching to different languages during runtime and within the same process.

src/libraries/Microsoft.PowerFx.Core/Errors/BaseError.cs, src/libraries/Microsoft.PowerFx.Core/Errors/TexlError.cs
Fix internal breaking changes from #746
=> Old constructor added back to avoid breaking internals

src/libraries/Microsoft.PowerFx.Core/App/ErrorContainers/ErrorContainer.cs, src/libraries/Microsoft.PowerFx.Core/Errors/BaseError.cs, src/libraries/Microsoft.PowerFx.Core/Errors/TexlError.cs, src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs
=> Fix internal breaks introduced with 746.

src/libraries/Microsoft.PowerFx.Core/Errors/BaseError.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionErrorTests.cs
Fix for breaking changes in #746
=> add missing case and tests for PAClient.

src/libraries/Microsoft.PowerFx.Core/Types/DType.cs
just add comments to dtype and group their fields.
=> DType docs  - no functional change -

src/libraries/Microsoft.PowerFx.Core/Public/Config/ReadOnlySymbolTable.cs, src/tests/Microsoft.PowerFx.Core.Tests/SymbolTableTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ConfigTests.cs
=> Add support to selectively remove functions from the default symbol table

src/libraries/Microsoft.PowerFx.Core/Public/ErrorKind.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Error.cs, src/libraries/Microsoft.PowerFx.Core/Types/Enums/EnumStoreBuilder.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/CommonErrors.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Error.txt
These changes were agreed along PA client team in advance.
=> New Error function overload. Error("Custom error message")

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ConfigTests.cs
=> Fixing Proper and adding extra test cases.

src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryMath.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryTable.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/libraries/Microsoft.PowerFx.Interpreter/ReflectionFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Values/LambdaFormulaValue.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/CustomFunctions.cs
-Fixes #643 
- Now you can add custom function with predicate.
- Added tests to demo it.
=> Adds support for call back function - Reflection function.

src/libraries/Microsoft.PowerFx.Core/Public/Values/CompileTimeTypeWrapperRecordValue.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/CompileTimeTypeWrapperTableValue.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/RecordValue.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/PADRobinExecutionContextTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/Scenarios/DataTableMarshallerProvider.cs
Issue #790.
Side comments/questions:
- Note that PAD temporary code is part of this PR. This is just to proof the changes have taken action over their test cases.
- Still taking on additional test cases to include. Any suggestions?
=> PAD bug fix. Avoiding unnecessary marshalling

src/libraries/Microsoft.PowerFx.Core/Public/DisplayNames/RenameDriver.cs, src/tests/Microsoft.PowerFx.Core.Tests/DisplayNameTests.cs
=> Adding find function to RenameDrive class.

src/libraries/Microsoft.PowerFx.Interpreter/Functions/CollectFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/PatchFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/RemoveFunction.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Collect.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Patch.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Remove.txt
=> Fixing table type exception for mutation functions

src/libraries/Microsoft.PowerFx.Interpreter/Functions/CollectFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/PatchFunction.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Collect.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationFunctionsTests.cs
Issue #856 
Initial draft push to double-check:
- Error and Blank as ObjNull? 
- If(false,Blank()) as _Min?
- Add more test cases.
- What makes a DType.IsTable equals true?
=> Testing mutation functions wrong argument scenarios

src/tests/Microsoft.PowerFx.Interpreter.Tests/SymbolValueTests.cs
Add a test showing how to support ThisItem  in a loop using the SymbolTable classes.
=> Text Example: ThisItem

src/tests/Microsoft.PowerFx.Performance.Tests/Microsoft.PowerFx.Performance.Tests.csproj
Fix Performance test project to not try generating a nuget package
=> Fix Performance test project

src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
=> Provides a way to check if variable exists in RecalcEngine.

src/Microsoft.PowerFx.sln, src/tools/Repl/Program.cs, src/tools/Repl/Repl.csproj
From Samples:
https://github.com/microsoft/power-fx-host-samples/blob/main/Samples/ConsoleREPL/ConsoleREPL.cs
We still want Samples copy since that goes against actual nugets. 
But a copy in the PowerFx repo is convenient for directly testing the SDK. 
Lots of whitespace differences because I had to bring up to coding conventions for this repo. 
Also leverage some recent functionality:
- replace a hack Set() RegEx with using official APIs (parse, etc) 
- FormulaValue.ToExpression to get  string from arbitrary expression.
=> Copy Repl project into PowerFx repo 

src/tests/Microsoft.PowerFx.Interpreter.Tests/FileExpressionEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/Microsoft.PowerFx.Interpreter.Tests.csproj, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/Simple1.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/PowerFxEvaluationTests.cs
Easy .txt tests for testing mutation/side-effects,  like Set(), Collect, etc.
=> add Stateful tests

src/libraries/Microsoft.PowerFx.Interpreter/ReflectionFunction.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/CustomFunctions.cs
=> CustomFunction - missing async case Fixes #935

src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/CollectFunction.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Collect.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/FileExpressionEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/Collect.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/PowerFxEvaluationTests.cs
=> Collect to return a record type.

src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/LanguageServerTests.cs
=> Adding test case from issue #918.

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/CollectionTableValue.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/TableValue.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/PowerFxConfigExtensions.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/ClearFunction.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Clear.txt, src/tests/Microsoft.PowerFx.Core.Tests/TableValueMutationTest.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ClearFunctionTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/FileExpressionEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/Clear.txt
=> Clear function implementation

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/PowerFxConfigExtensions.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/ClearCollectFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/ClearFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/CollectFunction.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Interpreter.Tests/FileExpressionEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/ClearCollect.txt
=> ClearCollect function implementation.

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/DateValue.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Time.txt
=> Supporting millisenconds with up to 7 digits.

src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/Collect.txt
=> Adding extra test cases to test With + Collect interaction.

src/libraries/Microsoft.PowerFx.Json/Microsoft.PowerFx.Json.csproj
Make the Fx.Json Csproj look just like Core/Interpreter's csproj.
=> Fx.Json is not getting properly signed.

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/IR/CoercionKind.cs, src/libraries/Microsoft.PowerFx.Core/IR/CoercionMatrix.cs, src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson_Coercions.txt
=> Revert Revert Initial work on UntypedObject implicit coercions

src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs
These functions will be available soon in other platforms
=> Move the Dec2Hex/Hex2Dec functions to the core library

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Binding/BinderUtils.cs, src/libraries/Microsoft.PowerFx.Core/Binding/INameResolver.cs, src/libraries/Microsoft.PowerFx.Core/Functions/FunctionArgValidators/SortOrderValidator.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/ComposedReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/ReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/ArgumentSuggestions.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseData/IntellisenseData.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseHelper.cs, src/libraries/Microsoft.PowerFx.Core/Types/Enums/EnumStoreBuilder.cs, src/libraries/Microsoft.PowerFx.Core/Types/Enums/EnumSymbol.cs, src/libraries/Microsoft.PowerFx.Core/Utils/LanguageConstants.cs, src/strings/PowerFxResources.en-US.resx
This is a clean up of some enum code that has not been used since PowerApps' Beta. We get a bunch of benefits besides removing debt from this, it significantly reduces the number of resources we need to load on startup, as well as shrinks the resource package size a bit
=> Clean up unused Enum localization code

src/libraries/Microsoft.PowerFx.Interpreter/Values/QueryableTableValue.cs
Changes to support https://github.com/microsoft/Power-Fx-Dataverse/issues/32
=> Adding a way to refresh local records cache lazily.

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/CollectFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/PatchFunction.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterSuggestTests.cs
=> Enables Column suggestion for Patch and Collect function.

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/RemoveFunction.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterSuggestTests.cs
=> Fixes Intellisense for Remove function.

src/tools/Repl/Program.cs
Add null check for the row and update logic to not only check first row but check the first null row for column def.
=> Fix null reference when table has blank() input.

src/libraries/Microsoft.PowerFx.Core/Public/Values/DateTimeValue.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryDate.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/DateTimeUTCTests.cs
=> Fixes datetime issue with untyped object.

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text.txt
Fix issue:  https://github.com/microsoft/Power-Fx/issues/1054. 
Fix Date, Time issue in Text function when format is not defined.
=> Fix Date, Time issue in Text function when format is not defined

src/libraries/Microsoft.PowerFx.Core/Public/Config/ReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/AggregateType.cs, src/tests/Microsoft.PowerFx.Core.Tests/DisplayNameTests.cs
=> Fixes #1077 SymbolTable not giving back DisplayNames

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/FormulaType.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUnary.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Interpreter.Tests/IRTests.cs
Issue https://github.com/microsoft/Power-Fx-Dataverse/issues/61
=> Handling BooleanOptionSetToBoolean coercion

src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTableOverRecordType.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs
=> Fixes #1075 suggest ThisRecord with row scope symbols.

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/If.cs
=> Fixes PR 1032.

src/libraries/Microsoft.PowerFx.Interpreter/Environment/PowerFxConfigExtensions.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/PatchFunction.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Patch.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/PatchFunctionTests.cs
=> Removing Patch(record,record) overload.

src/libraries/Microsoft.PowerFx.Core/Public/Values/CompileTimeTypeWrapperRecordValue.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/InMemoryRecordValue.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/If.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/First.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/If.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Patch.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/With.txt
-Fixes #1038 
-This may wrap the result of the If statement in CompileTimeTypeWrapperRecordValue.
=> Fixes #1038 If record type mismatch.

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/If.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/First.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ForAll.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Last.txt
=> Partially reverts #1032

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/OptionSetInfo.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
-Fixes #1091 
-Adds OptionSetInfo function, which returns the logical name of the option set value
=> Adds OptionSetInfo function, which returns the logical name of the option set value

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUnary.cs, src/libraries/Microsoft.PowerFx.Interpreter/Marshal/TypeCoercionProvider.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text_Format.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/TypeCoercionTest.cs
Issue #1098 
Out of range number to date returns an error instead of throwing an exception.
=> Out of range number to date returns an error

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text.txt
Fix issue: https://github.com/microsoft/Power-Fx/issues/1105
=> Fix culture format of date for Text function and add tests. 

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/CollectFunction.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Collect.txt
- Fixes #1049 
- Now Collect function appends the deep copy of the provided record.
=> Fixes #1049 Wrong Mutation semantics

src/libraries/Microsoft.PowerFx.Core/Public/Types/OptionSetValueType.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SerializationTests.cs
Issue #731.
OptionSetValueType to serialize the first option as the default value. If not options are present, serialize as error.
=> OptionSet default expression value implementation

src/libraries/Microsoft.PowerFx.Core/Public/Types/OptionSetValueType.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SerializationTests.cs
=> OptionSet serialization rely on Dictionary ordering no longer

src/libraries/Microsoft.PowerFx.Json/FormulaValueJSON.cs, src/tests/Microsoft.PowerFx.Json.Tests/ParseJSONTests.cs
=> FormulaValue.FromJson incorrectly Parsed heterogenous JSON arrays.

src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/Intellisense.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseSuggestion.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseSuggestionComparer.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseSuggestionList.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs
Takes advantage of the Culture to sort results properly
Fixes sorting as well
=> Suggest fix

src/libraries/Microsoft.PowerFx.Core/Public/Config/ReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTable.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/ReflectionFunction.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ServiceProviderTests.cs
=> Fixes 1187 Adds ability to add host object.

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryLanguage.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ConfigTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageTest.cs
Fix issue: https://github.com/microsoft/Power-Fx/issues/1195
=> Add default language and test

src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTableExtensions.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Error.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/UserInfoTests.cs
Follow https://github.com/microsoft/Power-Fx/pull/1214
=> Change UserInfo to User for user object

src/libraries/Microsoft.PowerFx.Core/Parser/ParseFormulasResult.cs, src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTableOverRecordType.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs
Will be superseded by #1165.
Fix race discovered via  test site., Fix #1208
=> Expose NamedFormula Parsing so that test site can consume it.

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Text.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/StronglyTypedEnums.txt
=> Fix StronglyTypedEnum use of DTFormat enum in Text Function

src/libraries/Microsoft.PowerFx.Core/Public/Config/PowerFxConfig.cs, src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ConfigTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SandboxTests.cs
Fix issue: https://github.com/microsoft/Power-Fx/issues/995
=> Set default max expression length in PowerFxConfig

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Table.cs, src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ArgCoercion.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/DecimalNonMathFuncs.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TableCoercion.txt
Issue #1204.
Re-pushing due to merge/rebase conflicts. https://github.com/microsoft/Power-Fx/pull/1282
=> Table function now supports coercion

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Public/ExpressionError.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/TableValue.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/AsType.cs, src/libraries/Microsoft.PowerFx.Interpreter/Exceptions/CustomFunctionErrorException.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryTable.cs, src/strings/PowerFxResources.en-US.resx
Fixes https://github.com/microsoft/Power-Fx-Dataverse/issues/113
=> Enables AsType function for Dataverse 

src/libraries/Microsoft.PowerFx.Core/Binding/INameResolver.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTableOverRecordType.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/UserInfoTests.cs
=> Fix #1337 - support [@ ] for symbols

src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationFunctionsTests.cs
Issue #1335.
https://github.com/microsoft/Power-Fx/pull/1338 has mitigated the issue but a regression test case was missing.
=> Adding regression test to #1335

src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/IfError.txt
=> Tactical fix for IfError

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/strings/PowerFxResources.en-US.resx
To support https://github.com/microsoft/Power-Fx-Dataverse/issues/153
=> Localizing delegation warning messages

src/libraries/Microsoft.PowerFx.Core/Public/Values/CompileTimeTypeWrapperRecordValue.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/InMemoryTableValue.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/RecordValue.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Extensions.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/RemoveFunction.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Patch.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Remove.txt
=> Mutation not allowed on partial fields; With functions Remove and Patch

src/libraries/Microsoft.PowerFx.Core/Lexer/TexlLexer.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/RecordValue.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ReservedKeywordNegative.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/SerializationTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/1409.
=> RecordValue.ToExpression to escape identifiers

src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryMath.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryTable.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/RuntimeHelpers.cs, src/libraries/Microsoft.PowerFx.Interpreter/IScope.cs, src/libraries/Microsoft.PowerFx.Interpreter/SymbolContext.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Concat.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/CountIf.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/FilterFunctions.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ForAll.txt
Issue https://github.com/microsoft/Power-Fx/issues/1327.
=> ThisRecord to handle Blank rows

src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/MinMax.txt
See:
Issue https://github.com/microsoft/Power-Fx/issues/1327.
PR https://github.com/microsoft/Power-Fx/pull/1421.
=> Additional test cases

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/IfError.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/IfError_PowerFxV1FeatureEnabled.txt
- Followup to https://github.com/microsoft/Power-Fx/pull/1230
- Fixes #1173
=> Fixes IfError under V1 flag

src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTableOverRecordType.cs
=> Don't eagerly build type for External Type in Global symbols

src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Public/ExpressionError.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionErrorTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Error.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ReservedKeyword_Disabled.txt
Issue https://github.com/microsoft/Power-Fx/issues/1435.
=> Avoid duplicated compilation error messages

src/libraries/Microsoft.PowerFx.Core/Public/Types/AggregateType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/RecordType.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/ParsedExpression.cs, src/tests/Microsoft.PowerFx.Core.Tests/TypeSystemTests/TypeTests.cs
-Fixes https://github.com/microsoft/Power-Fx-Dataverse/issues/171
=> Crash: Polymorphic field in a within With() expression 

src/libraries/Microsoft.PowerFx.Core/IR/BinaryOpMatrix.cs, src/libraries/Microsoft.PowerFx.Core/IR/Nodes/BinaryOpKind.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Blank.txt
Issue https://github.com/microsoft/Power-Fx/issues/1301.
=> Comparison with blank crash

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Atan2.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Char.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/DateTime.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Dec2Hex.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Hex2Dec.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/LeftRight.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/MathFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Rgba.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Sequence.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Split.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/StringOneArgFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Text.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Power.txt
=> Adds null handling in Power operator. (^)

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryDate.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/DateValue.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text.txt
Fix issue: https://github.com/microsoft/Power-Fx/issues/1441
=> Use epoch for DateTimeValue and DateValue without date

src/libraries/Microsoft.PowerFx.Connectors/ODataVisitor.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/ODataDelegationTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/1491.
=> ODataVisitor to support other UnaryOpKind kinds

src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/Tokenization.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/LanguageServer/LanguageServer.cs
Forgot to handle few cases where null ref could be thrown in this pr https://github.com/microsoft/Power-Fx/pull/1420. This pr handles those null ref scenarios. It is a small pr.
=> Fixing small null ref errors that i found from the changes in Pr #1420

src/strings/PowerFxResources.en-US.resx
To support DV issue https://github.com/microsoft/Power-Fx-Dataverse/issues/183.
=> Better warning message for delegation

src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/With.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/With_Decimal.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/With_Float.txt
Fix https://github.com/microsoft/Power-Fx/issues/1503
=> Add tests for With function

src/libraries/Microsoft.PowerFx.Core/Functions/CommonErrors.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/CollectionTableValue.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Patch.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Remove.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/IRTests/IRTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/PADIntegrationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RemoveFunctionTests.cs
=> Patch and Remove that do not find the record should error

src/libraries/Microsoft.PowerFx.Core/Annotations/GuardSingleThreaded.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTable.cs, src/tests/Microsoft.PowerFx.Core.Tests/GuardSingleThreadedTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/ThreadingTests.cs
add guard to catch bugs in host where it calls a single-threaded region on multiple threads.
=> add thread safety guard 

src/libraries/Microsoft.PowerFx.Core/Public/Values/InMemoryTableValue.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/Collect.txt
=> InMemoryTableValue partial Collect not working

src/strings/PowerFxResources.de-DE.resx, src/strings/PowerFxResources.el-GR.resx, src/strings/PowerFxResources.hu-HU.resx, src/strings/PowerFxResources.uk-UA.resx
=> [[Power-Fx]] Localization hand-back [CTAS - RunID=20230606-221330-rpy9vf7bx5]

src/strings/PowerFxResources.kk-KZ.resx, src/strings/PowerFxResources.nb-NO.resx
=> [[Power-Fx]] Localization hand-back [CTAS - RunID=20230613-213820-e29v4zkq13]

ApiCompat.Files.xml
=> Update ApiCompat file

src/libraries/Microsoft.PowerFx.Core/IR/Visitors/RewritingIRVisitor.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Interpreter.Tests/IRTests/RewritingIRVisitorTests.cs
Corresponding DV PR: https://github.com/microsoft/Power-Fx-Dataverse/pull/200
=> Needed for delegation change for Dataverse.

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunctionSet.cs
Fixed issue: https://github.com/microsoft/Power-Fx/issues/1604
=> Add guard single threaded to add/remove methods in TexlFunctionSet

src/libraries/Microsoft.PowerFx.Core/Public/Config/DeferredSymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/ReadOnlySymbolTable.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/SymbolTableTests.cs
Better handling for deferred symbol tables.
=> fix for Dataverse issue 204

src/libraries/Microsoft.PowerFx.Core/App/IExternalEnabledFeatures.cs, src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs
Reverts microsoft/Power-Fx#1626
=> Revert "Revert "Add new ECS flag to negate recent changes to function propert…"

src/libraries/Microsoft.PowerFx.Core/Public/Config/ReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTableOverRecordType.cs, src/tests/Microsoft.PowerFx.Core.Tests/DisplayNameTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SymbolValueTests.cs
Needed for https://dynamicscrm.visualstudio.com/OneCRM/_queries/edit/3428490/
=> Adds capability to block implicit this record.

src/tests/Microsoft.PowerFx.Interpreter.Tests/FileExpressionEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/AndOr.txt
=> Testing And/Or along with behavior functions

src/libraries/Microsoft.PowerFx.Interpreter/Marshal/TypeCoercionProvider.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/TypeCoercionTest.cs
Fix issue: https://github.com/microsoft/Power-Fx/issues/1653.
Check coerce from source to target instead of the opposite.
Add some more tests.
=> Check coerce from source to target instead of the opposite.

src/tests/Microsoft.PowerFx.Interpreter.Tests/TableTests.cs
Add test for issue: https://github.com/microsoft/Power-Fx-Dataverse/issues/189
=> Add test for empty field of record and empty record of table

src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/libraries/Microsoft.PowerFx.Connectors/Shared/ServiceFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/FormattingInfo.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/FormattingInfoHelper.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryDate.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUnary.cs, src/libraries/Microsoft.PowerFx.Interpreter/Marshal/TypeCoercionProvider.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/OpenApiFormUrlEncoderTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/OpenApiJsonSerializerTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/OpenApiParserTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/TypeCoercionTest.cs
Fix issue: https://github.com/microsoft/Power-Fx/issues/1583
=> Make FormattingInfo to Immutable to prevent threading issue

src/libraries/Microsoft.PowerFx.Core/Public/Values/RecordValue.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TableCoercion.txt
=> Fixes Issue with nested field in multiple field record/table

src/libraries/Microsoft.PowerFx.Interpreter/CustomFunction/CustomSetPropertyFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/SetFunction.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/CustomFunctions.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SetFunctionTests.cs
=> Allow Coercion in Set() for numbers.

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/RemoveFunction.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ForAll.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/FileExpressionEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/Remove.txt
Issue https://github.com/microsoft/Power-Fx/issues/1685.
=> Fixing Remove in ForAll return type issue

src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/tests/Microsoft.PowerFx.Core.Tests/IRPrintTest.cs
=> String interpolation without args

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/BooleanT.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ErrorKinds.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ErrorKinds_ColumnNamesAsIdentifiers.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ErrorKinds_ColumnNamesAsIdentifiersDisabled.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ErrorKinds_StronlyTypedBuiltinEnumsDisabled.txt
Also updates tests to run in more configurations
Fixes #1733
=> Fixes boolean-to-decimal tabular conversion

src/libraries/Microsoft.PowerFx.Core/Parser/ParseFormulasResult.cs, src/libraries/Microsoft.PowerFx.Core/Parser/ParseUserDefinitionResult.cs, src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Nodes/TypeLiteralNode.cs, src/tests/Microsoft.PowerFx.Core.Tests/NamedFormulasTests.cs
This adds the parsing of records and identifiers to the AST for TypeLiteralNode
=> Added parsing for TypeLiteralNode

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryTable.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/OptionSetTests.cs
Fixes https://github.com/microsoft/Power-Fx-Dataverse/issues/300
=> Fix issue with Option Set Value inside Filter()

src/strings/PowerFxResources.ca-ES.resx, src/strings/PowerFxResources.de-DE.resx, src/strings/PowerFxResources.es-ES.resx, src/strings/PowerFxResources.et-EE.resx, src/strings/PowerFxResources.eu-ES.resx, src/strings/PowerFxResources.fr-FR.resx, src/strings/PowerFxResources.hi-IN.resx, src/strings/PowerFxResources.kk-KZ.resx, src/strings/PowerFxResources.lt-LT.resx, src/strings/PowerFxResources.lv-LV.resx, src/strings/PowerFxResources.pt-BR.resx, src/strings/PowerFxResources.pt-PT.resx, src/strings/PowerFxResources.sk-SK.resx, src/strings/PowerFxResources.sl-SI.resx, src/strings/PowerFxResources.sr-Cyrl-RS.resx, src/strings/PowerFxResources.sr-Latn-RS.resx, src/strings/PowerFxResources.sv-SE.resx, src/strings/PowerFxResources.uk-UA.resx, src/strings/PowerFxResources.vi-VN.resx
=> [[Power-Fx]] Localization hand-back [CTAS - RunID=20230815-160143-gs00pxjkj1]

src/libraries/Microsoft.PowerFx.Core/Public/Config/Features.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/SetFunction.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/DatabaseSimulationTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/1764.
New feature: `PowerFxV1AllowSetExpandedTypes`
=> New feature to loosen Set function check semantics

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/SetFunction.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Interpreter.Tests/DatabaseSimulationTests.cs
Complement of https://github.com/microsoft/Power-Fx/pull/1765
=> Set expandable types warning message

src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTableExtensions.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseData/IntellisenseData.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseHelper.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterSuggestTests.cs
Fixes https://github.com/microsoft/Power-Fx/issues/1278
=> Do not suggest User in intellisense

src/libraries/Microsoft.PowerFx.Interpreter/CustomFunction/CustomFunctionUtility.cs, src/libraries/Microsoft.PowerFx.Interpreter/CustomFunction/CustomSetPropertyFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/CustomFunction/CustomTexlFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/CustomFunction/FunctionDescr.cs, src/libraries/Microsoft.PowerFx.Interpreter/CustomFunction/ReflectionFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/UDF/UserDefinedTexlFunction.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/CustomFunctions.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/IntellisenseTests/CustomFunctionSignatureTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/IntellisenseTests/TestSignatures/10001.json, src/tests/Microsoft.PowerFx.Interpreter.Tests/IntellisenseTests/TestSignatures/10002.json, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
=> Get Arg names from Function Signature

src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
This adds user defined types to recalc engine, and provides a entrypoint to be able to register new user defined types that work with user defined functions
=> Add User Defined Types to Recalc Engine

src/libraries/Microsoft.PowerFx.Core/Functions/CommonErrors.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/arithmetic.txt
Fixes https://dynamicscrm.visualstudio.com/OneCRM/_workitems/edit/3558410
=> Update error message for converting to number.

src/libraries/Microsoft.PowerFx.Core/Public/Values/PrimitiveValueConversions.cs, src/tests/Microsoft.PowerFx.Core.Tests/PrimitiveValueConversionsTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/MarshalTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/PADRobinExecutionContextTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/PrimitiveMarshallerProviderTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/Scenarios/ScenarioCustomMarshaler.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ServiceProviderTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SetFunctionTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ValueTests.cs
Follow up to https://github.com/microsoft/Power-Fx/pull/1813
=> Fix Type Marshaller

src/libraries/Microsoft.PowerFx.Core/Public/Values/PrimitiveValueConversions.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/MarshalTests.cs
Follow-up to https://github.com/microsoft/Power-Fx/pull/1827
=> Fixes Type conversion

src/libraries/Microsoft.PowerFx.LanguageServerProtocol/LanguageServer/LanguageServer.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Protocol/CustomFx2NLParams.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Protocol/CustomGetCapabilitiesRequest.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Protocol/CustomNL2FxParams.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Protocol/CustomProtocolNames.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Protocol/IHasTextDocument.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Public/NLHandler.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/LanguageServerTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Json.Tests/TypeSystemTests/FormulaTypeSerializerSnapshotTests.cs
Add Capabilities flag to LSP. 
Add Fx2NL hook on NLHandler. 
Update NL2Fx messages .
=> Add Capabilities flag to LSP 

src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IIntellisenseContext.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseContext.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseData/IntellisenseData.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/SuggestionHandlers/FunctionRecordNameSuggestionHandler.cs, src/tests/Microsoft.PowerFx.Core.Tests/CheckResultTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs
Fixes https://dynamicscrm.visualstudio.com/OneCRM/_workitems/edit/3582459
=> Intellisense when ExpectedReturnType is Record to help DV

src/strings/PowerFxResources.el-GR.resx, src/strings/PowerFxResources.et-EE.resx, src/strings/PowerFxResources.sr-Cyrl-RS.resx, src/strings/PowerFxResources.sr-Latn-RS.resx
=> [[Power-Fx]] Localization hand-back [CTAS - RunID=20230919-155425-2xnhd3wbe6]

src/libraries/Microsoft.PowerFx.Connectors/OpenApiParser.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/Swagger/MSNWeather.json
Accept those connector extensions to support the new version of MSN Weather swagger file
=> Accept x-ms-keywords and x-ms-openai-data extensions

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/PatchFunction.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/Patch.txt
=> Patch to coerce GUID to STR.

src/libraries/Microsoft.PowerFx.Repl/Repl.cs
[REPL will throw an exception for an illegal named formula · Issue #1929 · microsoft/Power-Fx (github.com)](https://github.com/microsoft/Power-Fx/issues/1929).
=> Catch exceptions for SetFormula in the REPL

src/strings/PowerFxResources.bg-BG.resx
=> [[Power-Fx]] Localization hand-back [CTAS - RunID=20231010-191605-kr06cm9rw4]

src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/DropColumns.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/ShowColumns.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryTable.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ShowColumns.txt, src/tests/Microsoft.PowerFx.Core.Tests/Helpers/TestUtils.cs, src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs
Issue #121.
`ShowColumns` function will leverage `DropColumns` function implementation.
=> ShowColumns function implementation

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Public/Logging/ITracer.cs, src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Trace.cs, src/libraries/Microsoft.PowerFx.Core/Types/Enums/BuiltInEnums.cs, src/libraries/Microsoft.PowerFx.Core/Types/Enums/EnumStoreBuilder.cs, src/libraries/Microsoft.PowerFx.Core/Utils/LanguageConstants.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Trace.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Trace_StronglyTypedBuiltinEnums.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Trace_StronglyTypedBuiltinEnumsDisabled.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestHelpers/TestRunner.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/Docs/InterpreterBase.json, src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterSuggestTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/PowerFxEvaluationTests.cs
-This also moves Trace() signature from PA, so will need to refactor PA.
=> Adds Trace Function.

src/libraries/Microsoft.PowerFx.Core/Entities/External/IExternalCdsDataSource.cs, src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/CollectFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/MutationUtils.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/PatchFunction.cs, src/strings/PowerFxResources.en-US.resx
=> Compilation error when mutating read-only fields

src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/Responses/Dataverse_Response_3.json
Fix an issue in connector dynamic list management
=> Connectors: Fix dynamic list issue

src/libraries/Microsoft.PowerFx.Core/Utils/TextFormatUtils.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text_ExcelCompat.txt
=> Fix Text encoding of am/pm with subsecond specifiers

src/libraries/Microsoft.PowerFx.Repl/Functions/ExitFunction.cs, src/libraries/Microsoft.PowerFx.Repl/Repl.cs, src/libraries/Microsoft.PowerFx.Repl/Services/StandardFormatter.cs, src/tests/Microsoft.PowerFx.Repl.Tests/ReplTests.cs, src/tools/Repl/Program.cs
Fixes for:
- https://github.com/microsoft/Power-Fx/issues/1994
- https://github.com/microsoft/Power-Fx/issues/1983
- https://github.com/microsoft/Power-Fx/issues/1944
- https://github.com/microsoft/Power-Fx/issues/1943
- https://github.com/microsoft/Power-Fx/issues/1942
- https://github.com/microsoft/Power-Fx/issues/2013
=> Updates to REPL

src/tests/Microsoft.PowerFx.Interpreter.Tests/TimeTests.cs
=> Fix time test

src/libraries/Microsoft.PowerFx.Connectors/Execution/FormulaValueSerializer.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/OpenApiJsonSerializerTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/2028.
=> HttpFunctionInvoker to handle blank values

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/AddColumns.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/RenameColumns.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/ShowDropColumnsBase.cs
The logic was used in many functions, moved it to the base class to be reused.
=> Refactor logic to retrieve column names depending on features

src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/2047
=> Adding test case against ConnectorCompatibility suggestions

src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/CollectFunctionTests.cs
Fixes https://github.com/microsoft/Power-Fx/issues/2089
=> Collect should work with Lazy Aggregate type.

src/libraries/Microsoft.PowerFx.Core/Public/FunctionInfo.cs, src/tests/Microsoft.PowerFx.Core.Tests/FunctionInfoTests.cs
Partial for #2004. 
Not doing categories yet because we need to discuss how to support that longer term. Is there a curated set? Do we expose the category enum?
=> Add Description, HelpIink to FunctionInfo

src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Protocol/MarkupContent.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/LanguageServerTests.cs
=> Followup to PR #2117 - Fixes in MarkupContext class

src/libraries/Microsoft.PowerFx.Core/Localization/ExpressionLocalizationHelper.cs, src/libraries/Microsoft.PowerFx.Core/Parser/ParserOptions.cs, src/libraries/Microsoft.PowerFx.Core/Public/DisplayNames/RenameDriver.cs, src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs, src/tests/Microsoft.PowerFx.Core.Tests/DisplayNameTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/2129.
=> RenameDriver with TextFirst active

src/Directory.Build.props, src/libraries/Microsoft.PowerFx.Interpreter/CustomFunction/ReflectionFunction.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/LivePublicSwaggerTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/SemanticTokensEncoderTests.cs
Update Microsoft.CodeAnalysis.NetAnalyzers and AnalysisLevel to version 8.0.0
Fix couple of issues newly identified
=> Net analyzers update to version 8.0.0

src/Directory.Build.props, src/libraries/Microsoft.PowerFx.Connectors/PowerPlatformConnectorClient.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorTests.cs
Add userAgent to PowerPlatformConnectorClient to generate a User Agent when calling APIM like below
`MyProduct/v1.2 PowerFx/1.3.0-build.20240110-1001`
Following RFC9110
=> User agent normalization

src/libraries/Microsoft.PowerFx.Core/Functions/Utils.cs, src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Public/FunctionInfo.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/FunctionInfoTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/FunctionTests.cs
Addressing part 1 of https://github.com/microsoft/Power-Fx/issues/2151.
> ...extend the function info, with the localized function category names.
=> Get function category names

src/libraries/Microsoft.PowerFx.Core/Lexer/ITextFirstFlag.cs, src/libraries/Microsoft.PowerFx.Core/Lexer/TexlLexer.cs, src/libraries/Microsoft.PowerFx.Core/Lexer/Tokens/StrInterpEndToken.cs, src/libraries/Microsoft.PowerFx.Core/Lexer/Tokens/StrInterpStartToken.cs, src/libraries/Microsoft.PowerFx.Core/Lexer/Tokens/StrLitToken.cs, src/tests/Microsoft.PowerFx.Core.Tests/LexerTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/2161
=> New TextFirst flag for syntax highlight

src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/TokenTextSpan.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/Tokenization.cs, src/tests/Microsoft.PowerFx.Core.Tests/LexerTests.cs
Complementing issue https://github.com/microsoft/Power-Fx/issues/2161 fixes.
=> New IsTextFirst flag to TokenTextSpan

src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/TokenTextSpan.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/TokenType.cs, src/tests/Microsoft.PowerFx.Core.Tests/LexerTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs
Complement for https://github.com/microsoft/Power-Fx/issues/2161.
=> Intellisense tokens made public

src/libraries/Microsoft.PowerFx.Core/Lexer/TexlLexer.cs, src/tests/Microsoft.PowerFx.Core.Tests/LexerTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/TextFirstTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/2178.
=> Empty script when TextFirst is active

src/libraries/Microsoft.PowerFx.Connectors/Execution/HttpFunctionInvoker.cs, src/libraries/Microsoft.PowerFx.Connectors/PowerPlatformConnectorClient.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/Responses/AzureBlobStorage_Response2.json, src/tests/Microsoft.PowerFx.Connectors.Tests/Responses/MSNWeather_Response2.json
Fix 1: HttpRequestException: Request headers must contain only ASCII characters.
Fix 2: Management of "Content-Type" parameter was incorrect
=> Two connector fixes

src/strings/PowerFxResources.bg-BG.resx, src/strings/PowerFxResources.et-EE.resx, src/strings/PowerFxResources.eu-ES.resx, src/strings/PowerFxResources.ko-KR.resx, src/strings/PowerFxResources.pt-BR.resx
=> [[Power-Fx]] Localization hand-back [CTAS - RunID=20240214-205202-tp0gj0zzb2]

src/libraries/Microsoft.PowerFx.Core/Logging/StructuralPrint.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/UserDefinitions.cs, src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/tests/Microsoft.PowerFx.Core.Tests/CheckResultTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/FormatterTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/2210.
=> Anonymizing unknown functions

src/libraries/Microsoft.PowerFx.Core/Public/FunctionInfo.cs, src/libraries/Microsoft.PowerFx.Core/Public/Reflection/FunctionInfo.cs, src/libraries/Microsoft.PowerFx.Core/Public/Reflection/FunctionInfoSignature.cs, src/libraries/Microsoft.PowerFx.Core/Public/Reflection/ParameterInfoSignature.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseResult.cs, src/tests/Microsoft.PowerFx.Core.Tests/FunctionInfoTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs
Allow public surface to get the parameter help for each param.
=> Get parameter help 

src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/SuggestionHandlers/FunctionRecordNameSuggestionHandler.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterSuggestTests.cs
=> don't suggest fields that are already specified

src/libraries/Microsoft.PowerFx.Core/Utils/Extensions.cs, src/tests/Microsoft.PowerFx.Core.Tests/CheckResultTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/2263.
=> Get literal value from parsed expression

src/strings/PowerFxResources.ca-ES.resx, src/strings/PowerFxResources.de-DE.resx, src/strings/PowerFxResources.eu-ES.resx, src/strings/PowerFxResources.gl-ES.resx, src/strings/PowerFxResources.kk-KZ.resx, src/strings/PowerFxResources.nb-NO.resx, src/strings/PowerFxResources.pt-BR.resx, src/strings/PowerFxResources.uk-UA.resx, src/strings/PowerFxResources.vi-VN.resx, src/strings/PowerFxResources.zh-TW.resx
=> [[Power-Fx]] Localization hand-back [CTAS - RunID=20240329-201125-qvkbq21mj6]

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Patch.cs, src/tests/Microsoft.PowerFx.Core.Tests/AssociatedDataSourcesTests/TestDVEntity.cs, src/tests/Microsoft.PowerFx.Core.Tests/Helpers/TestTabularDataSource.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationFunctionsTests.cs
An extra semantic check missing in https://github.com/microsoft/Power-Fx/pull/2269.
=> Adding semantic check to Patch V1

src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/Swagger/Eden AI.json
This is a particular condition we don't support and should detect
Otherwise we end up with this exception
=> Detect when a body has multiple parameters and when one of them is blob

src/strings/PowerFxResources.et-EE.resx, src/strings/PowerFxResources.fi-FI.resx
=> [[Power-Fx]] Localization hand-back [CTAS - RunID=20240410-211903-d2w1kr1s86]

src/strings/PowerFxResources.bg-BG.resx, src/strings/PowerFxResources.it-IT.resx, src/strings/PowerFxResources.ja-JP.resx, src/strings/PowerFxResources.tr-TR.resx
=> [[Power-Fx]] Localization hand-back [CTAS - RunID=20240502-164759-02vvr0kdh1]

src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Rand.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Rand_DecimalSupport.txt
One test from Rand.txt assumes that numbers are decimal; this moves it to a separate file.
=> Moved test from Rand.txt that depended on number being decimal

src/libraries/Microsoft.PowerFx.Core/Annotations/GuardSingleThreaded.cs, src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunctionSet.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/ComposedReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/ReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTable.cs, src/tests/Microsoft.PowerFx.Core.Tests/GuardSingleThreadedTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/SymbolTableTests.cs
Add more guards against threading misuse and races.
No functional changes.
=> Add more guards against threading misuse and races.

src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Decimal.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Float.txt
There are no tests specifically for those functions; this splits the Value tests and adds those.
=> Add tests specific for the Decimal and Float functions

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Summarize.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Summarize.txt
Issue https://github.com/microsoft/Power-Fx/issues/2370.
=> Summarize should have a compile time error for Identifier as Name

src/strings/PowerFxResources.en-US.resx
The localization team asked us to update the locked directive for one resource, as it was having errors in a few languages.
=> Update resource lock directive per request from the localization team

src/libraries/Microsoft.PowerFx.Connectors/Obsolete/ODataParameters.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorTableValue.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/Services/ConnectorTable.cs, src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Logging/StructuralPrint.cs, src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/DelegationParameters.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/ODataParametersTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/CheckResultTests.cs
Fixes Assert: #2414, 
Fixes getting rows in tabular Connectors:   #2441
Fixes OdataParameter handler, which is needed for 2441.
=> Connector Fixes

src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Visitors/ListFunctionVisitor.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ListFunctionVisitorTests.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/PublicSurfaceTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/2455.
=> Public API to get list of functions call

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/BlobValue.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/PowerFxFileInfo.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/FileInfo.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/PowerFxConfigExtensions.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/FileInfoImpl.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests.Shared/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/BlobTests.cs
=> FileInfo functions 

src/libraries/Microsoft.PowerFx.Core/Public/Config/Features.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/SetFunction.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/DatabaseSimulationTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/2461.
=> Removing unnecessary code

src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/ParseJson.txt
Issue https://github.com/microsoft/Power-Fx/issues/2520.
=> UO field coercion

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Collect.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseHelper.cs, src/libraries/Microsoft.PowerFx.Core/Types/DTypeExtensionsCore.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/IntellisenseTests/SuggestTest.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/LazyRecursiveRecordTypeHelper.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/RecursiveRecordTypeTest.cs
We are extending the range for https://github.com/microsoft/Power-Fx/issues/2456.
=> Stackoverflow when calling DType.ContainsDataEntityType

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Summarize.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/Summarize.txt
Issue https://github.com/microsoft/Power-Fx/issues/2527.
=> Summarize to support GUID type

src/libraries/Microsoft.PowerFx.Connectors/Obsolete/ODataParameters.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/CdpTableValue.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/DelegationParameters.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/ODataParametersTests.cs
ODataParameters: Update OrderBy
DelegationParameters: Add GetOrderBy()
=> Add OrderBy

src/libraries/Microsoft.PowerFx.Core/Localization/StringResources.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/AnalyzeThreadSafety.cs
Fix for #2528 . See issue for description
=> Fix nullref race in StringResources

src/libraries/Microsoft.PowerFx.Core/Public/Values/FormulaValueNew.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/UntypedObjectValue.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/UntypedObject.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/SetFunction.cs, src/libraries/Microsoft.PowerFx.Json/Functions/JsonUntypedObject.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/DateTimeUTCTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/MutationScripts/Set_DeepMutation_V1Compat.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/PadUntypedObjectTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/PowerFxEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/Scenarios/PrimitiveWrapperAsUnknownObject.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/Scenarios/ScenarioMutation.cs
Issue https://github.com/microsoft/Power-Fx/issues/2501.
=> UO set property

src/libraries/Microsoft.PowerFx.Core/Lexer/TexlLexer.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/IntellisenseTests/SuggestTest.cs
Issue https://github.com/microsoft/Power-Fx/issues/2549.
=> Escaping reserved words when suggested

src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/PadUntypedObjectTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/2503.
This scenario is already supported. Adding test cases.
=> Read untyped value with Index function

src/libraries/Microsoft.PowerFx.Connectors/Texl/ConnectorTexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Public/Reflection/FunctionInfoSignature.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Formula.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Boolean.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/Intellisense.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseData/DefaultIntellisenseData.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseData/IIntellisenseData.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseData/IntellisenseData.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseResult.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/FunctionInfoTests.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/FunctionTests.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/IntellisenseTests/IntellisenseTestBase.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/IntellisenseTests/SuggestTest.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ResourceValidationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/LanguageServiceProtocol/LegacyLanguageServerTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/2576.
=> Localize intellisense messages

src/libraries/Microsoft.PowerFx.Core/Public/Values/UntypedObjectValue.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/PadUntypedObjectTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/2591.
=> UO.TryGetProperty should determine the result value

src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Visitors/ListFunctionVisitor.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ListFunctionVisitorTests.cs
Avoids breaking change at https://github.com/microsoft/Power-Fx/pull/2597.
=> Adjusting "Option to anonymize unknown public functions"

src/libraries/Microsoft.PowerFx.Connectors/OpenApiParser.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/OpenApiParserTests.cs
Add new methods to OpenApiParser to fetch triggers from OpenApi definitions
=> Add ability to get trigger operations from an OpenApi definition

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseHelper.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseResult.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseSuggestion.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/IntellisenseTests/SuggestTest.cs
Issue https://github.com/microsoft/Power-Fx/issues/2576. There were uncovered cases.
=> Localizing intellisense signatures

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/PadUntypedObjectTests.cs
'Column' and 'CountRows' functions now support PAD UO values.
=> UO support for functions

src/libraries/Microsoft.PowerFx.Core/Public/Values/CompileTimeTypeWrapperRecordValue.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/PowerFxConfigExtensions.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/Helpers/TestTabularDataSource.cs
Issue https://github.com/microsoft/Power-Fx/issues/2416.
=> Environment variables helper

src/libraries/Microsoft.PowerFx.Connectors/Microsoft.PowerFx.Connectors.csproj, src/libraries/Microsoft.PowerFx.Json/Microsoft.PowerFx.Json.csproj, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Microsoft.PowerFx.LanguageServerProtocol.csproj
https://github.com/dotnet/announcements/issues/329
=> Microsoft Security Advisory CVE-2024-43485

src/libraries/Microsoft.PowerFx.Core/Public/Config/PowerFxConfig.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/ReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTable.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/DisplayNameOptionSetTests.cs
Add AddOptionSet API to SymbolTable
#1867
=> Add SymbolTable AddOptionSet

src/libraries/Microsoft.PowerFx.Core/Public/Config/ComposedReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/ReadOnlySymbolTable.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/SymbolTableTests.cs
Make sure composed tables return all option sets
=> Fix OptionSets in symbol tables

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs
Found doing some cleanup on PA Client
=> Clean up some dead code

src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorType.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/CdpTableResolver.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/CompatibilityTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PowerPlatformTabularTests.cs
=> CDP - Remove SQL relationships

src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/LanguageServiceProtocol/RedesignedLanguageServerTests/CancellationTests.cs
See #2755 
Get a real fix next
=> Disable flaky test 

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Join.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/ArgumentSuggestions.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryTable.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/Join.txt, src/tests/Microsoft.PowerFx.Core.Tests.Shared/IntellisenseTests/SuggestTest.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/MutationScripts/Join.txt
-  Fixing span information for error messages.
- Scope fields suggestions.
=> Join suggestions and error span

src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorParameter.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorSchema.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorSettings.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorType.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/CdpTableResolver.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/CompatibilityTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/InternalTesting.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Microsoft.PowerFx.Connectors.Tests.Shared.projitems, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PowerPlatformConnectorTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Swagger/Dime.Scheduler.json, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/ThreadingTests.cs
Add ConnectorSettings SupportXMsEnumValues
Add management for numeric value based OptionSets
=> Add ConnectorSetting SupportXMsEnumValues

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryTable.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/Join.txt
Issue https://github.com/microsoft/Power-Fx/issues/2796.
=> Join with Blank() bug fix

src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorType.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PowerPlatformConnectorTests.cs
Add modelAsString management in x-ms-enum extension
Spec https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/creating-swagger.md#Enum-x-ms-enum
=> Add modelAsString management in x-ms-enum extension

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Summarize.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/DisplayNameTests.cs
To support https://github.com/microsoft/Power-Fx-Dataverse/issues/580.
=> Summarize display name fix

src/strings/PowerFxResources.en-US.resx
The localization team will bring other language files up to date.
=> Removing dup resource

src/libraries/Microsoft.PowerFx.Connectors/ConnectorConstants.cs, src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorSchema.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorType.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Microsoft.PowerFx.Connectors.Tests.Shared.projitems, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PowerPlatformConnectorTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Swagger/SendMail_Modified.json
Add support for x-ms-property-entity-type extension
Expose it on all parameters, when available
Different from display name as it's a non-localized extension
=> Add support for x-ms-property-entity-type

src/libraries/Microsoft.PowerFx.Core/IR/Visitors/IRPrettyPrinter.cs, src/libraries/Microsoft.PowerFx.Repl/PsuedoFunctions.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/Extensions.cs, src/tests/Microsoft.PowerFx.Repl.Tests.Shared/ReplTests.cs, src/tools/Repl/Program.cs
=> Compact IR pseudo function

src/Directory.Build.props, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/SymbolValueTests.cs
=> Update Microsoft.CodeAnalysis.NetAnalyzers to v9

src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs
=> Fix NullRef in CDP / get capabilities

src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorType.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/Services/CdpTable.cs
Avoids a NullRef in DisplayNameProvider creation
Update ConnectorType error message
Expose ConnectorType in CdpTable
=> ConnectorType fix

src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorType.cs
Don't allow leading or trailing spaces
=> Check ConnectorType name validity 

src/strings/PowerFxResources.sr-Cyrl-RS.resx
This is the pull request automatically created by the OneLocBuild task in the build process to check-in localized files generated based upon translation source files (.lcl files) handed-back from the downstream localization pipeline. If there are issues in translations, visit https://aka.ms/icxLocBug and log bugs for fixes. The OneLocBuild wiki is https://aka.ms/onelocbuild and the localization process in general is documented at https://aka.ms/AllAboutLoc.
=> Localized file check-in by OneLocBuild Task: Build definition ID 12757: Build ID 2225561
