src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/IntellisenseTestBase.cs
The Get function in StringResources.cs throws exceptions when resources are not found. Line 55 in Intellisense.cs silently ignores exceptions and returns an empty suggestion list.
This change rethrows any intellisense exceptions in the unit tests so that the error messages will be more useful in the case where those tests fail because of an exception.
=> Rethrow intellisense exceptions in IntellisenseTestBase

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Acos.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Acot.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Asin.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Atan.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Atan2.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Cos.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Cot.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Degrees.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Exp.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Ln.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Log.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Mod.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Radians.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Sin.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Tan.cs
We want to add error context to math functions in Power Apps Canvas apps, and that require those functions to be tagged with requiring error context.
=> Add error context declaration to math functions

src/libraries/Microsoft.PowerFx.Core/Entities/QueryOptions/ExpandQueryOptions.cs
Code had consideration for a null parentDataSource but would still crash in the scenario.
=> Fix crash in ExpandQueryOptions

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Concatenate.cs, src/strings/en-US/PowerFxResources.resw
There is a bug in both the C# and TypeScript interpreters caused by certain inputs to the Concatenate function. The bug occurs when Concatenate expects a table (according to the type checker) but gets a Blank() value at runtime. For example:
Concatenate("a", If(1<0, ["txt"]))
The type checker expects the result of this call to be a table. However, at runtime the actual return value is the string "a". This is because the result of the call to If returns Blank() instead of a table. The Blank() is considered a scalar value equivalent to the empty string by the runtime.
This PR adds a ConcatenateT variant so that the runtime knows the return type needs to be a Table. Further changes will need to be made to the TypeScript backend to always return a table from ConcatenateT, creating an empty …
=> Add a table variant of the Concatenate function

src/libraries/Microsoft.PowerFx.Core/Types/Enums/EnumStore.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs
Enum storage is order sensitive. The call to ToImmutableDictionary was shuffling the order, leading to errors in some unit tests most of the time.
=> Remove call to ToImmutableDictionary from EnumStore

src/libraries/Microsoft.PowerFx.Core/Lexer/TexlLexer.cs, src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/strings/en-US/PowerFxResources.resw, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/string.txt
The Lexer currently does not gracefully handle unmatched curly brackets, and has the potential to throw exceptions without useful error messages. This change removes the call to Pop on the lexer mode stack when the stack is empty, and provides error messages in the token stream when mismatched curly brackets are detected, including just before EoF is added to the token stream.
=> Add an error message that appears for unmatched curly brackets

src/libraries/Microsoft.PowerFx.Core/Public/ErrorKind.cs, src/libraries/Microsoft.PowerFx.Core/Types/Enums/EnumStore.cs, src/strings/en-US/PowerFxResources.resw
When a function in an app is waiting on async operation (promise), and the promise is canceled, the function returns an error - and it is currently being displayed to the user. But this is a case where we decided that the operation is not necessary anymore, so that should not be a user-visible error. Adding a new error kind for canceled operations will allow the app runtime to decide what to do with it, including not showing it to the user.
=> Add new error kind enum value (canceled)

src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs
Notably:
IndexFunction_CO
ParseJsonFunction
Just setting IsHidden=true is insufficient to hide from canvas. We can't add them to _library at all.
Still include in the interpreter by default. 
This is blocking integrating into PAClient.
=> Ensure that new functions don't show up in Canvas apps:

src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Table.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Text.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/UntypedObject.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Value.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs
Cleans up the _CO prefix to use _UO instead.
=> Rename _CO functions to use the _UO suffix

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt
This change moves the Value and Text functions for UntypedObject instances towards a "type casting" style and away from parsing. Now the Text_UO and Value_UO functions only allow String and Number types on the UO impl. Tests have been updated to reflect the new RuntimeTypeMismatch errors.
=> Remove runtime type coercions from Value, Text functions

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Entities/External/IExternalEntity.cs, src/libraries/Microsoft.PowerFx.Core/Entities/External/IExternalOptionSet.cs
This change is to remove more properties from Entity/OptionSet interfaces, to allow creating clean public OptionSet implementation for Interpreter clients. As part of that,  some fields specific to Dataverse have been pulled off of the general option set definition, and checks for Canvas specific logic have been moved out of binder and into Canvas.
=> [Option Set Cleanup 3/4] Remove more properties from IExternalEntity and IExternalOptionSet

src/libraries/Microsoft.PowerFx.Core/Entities/External/IExternalOptionSet.cs, src/libraries/Microsoft.PowerFx.Core/Public/DisplayNames/DisabledDisplayNameProvider.cs, src/libraries/Microsoft.PowerFx.Core/Public/DisplayNames/DisplayNameProvider.cs, src/libraries/Microsoft.PowerFx.Core/Public/DisplayNames/SingleSourceDisplayNameProvider.cs, src/libraries/Microsoft.PowerFx.Core/Types/DType.cs
This last refactor eliminates the generic param from IExternalOptionSet, and moves to a common Display Name pattern that will be used going forward for all display name work.
=> [Option Set Cleanup 4/4] Move IExternalOptionSet to use DisplayNameProvider

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryTable.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/First.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Last.txt
Last/First are returning an error for the empty table returned by Filter. This should be a blank record, consistent with Canvas.
=> Update First/Last functions to return blank on empty tables

src/libraries/Microsoft.PowerFx.LanguageServerProtocol/AssemblyProperties.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/JsonRpc/FormulaTypeJsonConverter.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/LanguageServerTests.cs
We shouldn’t be getting types into powerfx via JSON generally, we have a cleaner C# api for constructing types. This is only used for notifying clients of the types. Move to throwing an exception instead of allowing reads using this serializer.
=> Enforce that FormulaTypeJsonConverter is one-way

src/libraries/Microsoft.PowerFx.Core/IR/Nodes/UnaryOpKind.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/FormulaType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/OptionSetValueType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/IValueVisitor.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/OptionSetValue.cs, src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/libraries/Microsoft.PowerFx.Core/Utils/GetTokensUtils.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/OptionSet.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUnary.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/ResolvedObjectHelpers.cs, src/libraries/Microsoft.PowerFx.Interpreter/ParsedExpression.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/libraries/Microsoft.PowerFx.Interpreter/SymbolContext.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/JsonRpc/FormulaTypeJsonConverter.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OptionSet.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestHelpers/BaseRunner.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestHelpers/ExpressionTestCase.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestHelpers/TestCase.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestHelpers/TestRunner.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestHelpers/TxtFileDataAttribute.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/FileExpressionEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/GetTokensUtilsTest.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/PowerFxEvaluationTests.cs
This adds support for Option Set values to the interpreter visitor, as well as adding an interface for defining fields of option set types.
To test this, it also adds the ability to define a test setup handler for .txt files.
=> Implement Option Set Support in the interpreter

src/libraries/Microsoft.PowerFx.LanguageServerProtocol/LanguageServer/LanguageServer.cs
I believe this was omitted by accident. Was causing all diagnostic responses from the language server to have severity 0.
=> Set diagnostic severity on language server publish diagnostics notification

src/libraries/Microsoft.PowerFx.Core/Localization/StringResources.cs
CurrentLocaleInfo.CurrentUILanguageName is set by the host, and may be null/empty. In those cases, we should fall back to en-US for our string resources.
=> Remove non-empty locale assert in StringResources

src/libraries/Microsoft.PowerFx.Core/Types/Enums/EnumStore.cs
This change caches the enum objects and re-uses them for Suggestion api.
The following test takes 320 seconds in master and only 12s with the proposed change
[Fact]
public void TestSuggestdf()
{
var eng = new RecalcEngine();
for (int i = 0; i < 1000; i++)
{
eng.Suggest("Abs", null, 3);
}
}
=> Improve Suggest api performance

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/TokenizerConstants.cs
Adding patterns that literals already support, for use in Tokenizer.cs in document server.
=> Add a new function to the binder to access string interpolation nodes

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/CountIf.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Lookup.cs
Filter coerces yes/no columns in Dataverse to Boolean, but CountIf and LookUp do not do the same thing. This PR remedies that.
Test App:
Formulas used:
=> Allow CountIf and LookUp to coerce yes/no to Boolean

src/libraries/Microsoft.PowerFx.Interpreter/Functions/StandardErrorHandling.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/string.txt
Other while loops in the C# interpreter converge in all branches (if any). The exception was the Mid function which had a while loop with a missing else branch.
=> Fix while loop bug in the Mid function

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Lexer/Tokens/IdentToken.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Nodes/ErrorNode.cs
This change makes the binder aware of generated call nodes. This will allow querying of call nodes in the future, for example in JsTranslator.
=> Add new method to TexlBinding for generating transient Concatenate

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs
For some reason the constructor of CallInfo will allow creating instances with a null TexlFunction.
=> Add function info to generated call info

src/Directory.Build.props
Update local package version number to a version higher than the public one, so that it can be used with dependencies that require a version higher than one of the public releases.
=> Update local package version number

src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestHelpers/BaseRunner.cs, src/tests/Microsoft.PowerFx.Core.Tests/TestRunnerTests/TestRunnerTests.cs
The matching for the kind property of errors is not working properly; this fixes the regex that is used to validate it (and adds test cases to guard against regressions)
=> Fix error kind matching in test cases

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs, src/strings/en-US/PowerFxResources.resw, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/StringInterpolate.txt
Empty islands such as $"{}" are an error in C# and should be an error in PowerFx.
=> Add new error for empty Islands

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/StandardErrorHandling.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Concat.txt
Currently the Concat function declares that it accepts three parameters, but the C# interpreter can only handle two (and will throw an exception if the third one is passed). This adds support for it.
=> Add support for Concat's third parameter (separator)

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryMath.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Rand.txt
The function RandBetween takes two parameters, and it should return _an integer_ greater than or equal to the first argument, and smaller than _or equal to_ the second argument (i.e., inclusive). The current implementation was not returning the second argument, nor was it working properly if the first argument was not a whole number. This change brings it to parity with Excel.
=> Fix RandBetween to be equivalent to Excel

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs
We are generating a call node in the binder so that it exists in later phases. This call node previously obtained clones of all the children by calling the Clone method. The Clone method was used because the children could not have multiple parents, and using the arguments directly would result 2 parents: the StrInterp node itself and the generated CallNode.
It appears that the Clone method was not intended to be used in this way, and it fails for error inputs.
This change removes the children from the generated CallNode. They were only being used by JsTranslator, and I can modify JsTranslator to get the arguments from the StrInterpNode instead of the CallNode. The CallNode just needs to exist.
=> Remove all arguments from the generated call node

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/CountIf.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Lookup.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/CountFunctions.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Lookup.txt
Re-do of this PR: 
https://github.com/microsoft/Power-Fx/pull/187
But instead only coercing OptionSetValue.
=> Coercing only OptionSetValues to boolean for CountIf and LookUp

src/libraries/Microsoft.PowerFx.Core/Public/Types/FormulaType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/OptionSetValueType.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
Fix #226.
When adding proper option set support, FormulaType.Build wasn't updated to ensure that the internal option set type gets properly converted back to the public FormulaType. This also exposes the name of the option set publicly on the OptionSetValueType, for use in hosts.
=> Expose OptionSet name, and correctly marshal in FormulaType.Build

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/FormulaValue.cs, src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/UntypedObject.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryJson.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/strings/en-US/PowerFxResources.resw, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt
Rename ParseJson to ParseJSON to be consistent with the existing JSON function.
=> Rename ParseJson to ParseJSON

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/ColorFade.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/ColorFadeT.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/DateTime.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Error.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Sort.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/SortByColumns.cs
Part 1 of a series of changes that will allow required enums to be automatically configured for a given function library. This change adds a new method, GetRequiredEnumNames, to the TexlFunction base class. It overrides this method for functions within our library which require enums.
=> Add GetRequiredEnumNames method to TexlFunction

src/libraries/Microsoft.PowerFx.Core/FeatureFlags.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/ThreadingTests.cs
At present, a host can't modify the feature flags.  They should be able to.  For example, I'd like to be able to `FeatureFlags.StringInterpolation = true;` when instancing a new engine in the ConeoleREPL sample, to test out this feature without needing to build the libraries.
=> Make FeatureFlags accessible to hosts

src/libraries/Microsoft.PowerFx.Core/Public/IExpression.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryDate.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryLogical.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryMath.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryOperators.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryTable.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUnary.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/StandardErrorHandling.cs, src/libraries/Microsoft.PowerFx.Interpreter/Microsoft.PowerFx.Interpreter.csproj, src/libraries/Microsoft.PowerFx.Interpreter/ParsedExpression.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngineWorker.cs, src/libraries/Microsoft.PowerFx.Interpreter/ReflectionFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Utility.cs, src/libraries/Microsoft.PowerFx.Interpreter/Values/LambdaFormulaValue.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/LanguageServerTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineAsyncTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
Add EvalAsync() to Interpreter and plumb async through EvalVisitor and functions.
Add tests demonstrating true async. 
Still a few .Results to chase down.
=> Async support for interpreter.

src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryMath.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Index.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Record.txt
The [] syntax always creates a single column table, even if it contains records. Adds capability to force single column tables to the helper functions, and adds test coverage for this use.
=> Fix inline table+record bug

src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/DateTime.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryDate.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/strings/en-US/PowerFxResources.resw, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/DateTime.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestHelpers/TestRunner.cs
Currently the only way to create a DateTime object is to add together a date object and a time object. Since all other types have a "constructor function", adding it will make expressions that need to create a DateTime object simpler.
=> DateTime function definition / implementation

src/libraries/Microsoft.PowerFx.Core/Syntax/Visitors/FindNodeVisitor.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/StringInterpolate.txt, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs
Change TableNode FindNodeVisitor to use the commas instead of the children. The previous implementation should have never worked.
=> Change TableNode FindNodeVisitor to use the commas

src/libraries/Microsoft.PowerFx.Core/Entities/External/IExternalViewInfo.cs, src/libraries/Microsoft.PowerFx.Core/Types/DType.cs
DisplayNameProvider is the preferred approach to handling display names. This PR continues the work of several previous ones, moving away from the approach of` IDisplayMapped<T>` for another IExternal type.
=> Move IExternalViewInfo to DisplayNameProvider pattern

src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/Intellisense.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseData/IntellisenseData.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseProvider.cs, src/libraries/Microsoft.PowerFx.Core/Types/Enums/EnumStore.cs, src/libraries/Microsoft.PowerFx.Core/Types/Enums/EnumStoreBuilder.cs, src/libraries/Microsoft.PowerFx.Core/Types/Enums/IEnumStore.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
Continuing the story of cleaning up EnumStore, this change introduces the IEnumStore interface and changes Intellisense classes to use the new interface. The old EnumStore will be added to PA Client with a new class named LegacyEnumStore, which will implement IEnumStore. This old code was fragile and cannot be changed.
=> Remove unused methods and fields from EnumStore/Builder

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Text.cs
https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/functions/function-text#datetime
Ensures that the Text function brings in the corresponding enums.
=> Add GetRequiredEnums to Text function

src/libraries/Microsoft.PowerFx.Core/Localization/StringResources.cs, src/tests/Microsoft.PowerFx.Core.Tests/ResourceValidationTests.cs
Basic strings looked up using the correct locale, but error resources were using the fallback. This fixes the issue and adds a test to catch that.
=> Fix ErrorResource locale bug

src/libraries/Microsoft.PowerFx.Core/Parser/ParseResult.cs, src/libraries/Microsoft.PowerFx.Core/Parser/ParserOptions.cs, src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs, src/libraries/Microsoft.PowerFx.Core/Public/ExpressionError.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/ErrorValue.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Formula.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/LanguageServer/LanguageServer.cs, src/tests/Microsoft.PowerFx.Core.Tests/BindingEngineTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionErrorTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestHelpers/BaseRunner.cs, src/tests/Microsoft.PowerFx.Core.Tests/ParseTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
This was a bit non-trivial because:
1. Use existing ParseResult class rather than create a new one. The existing FormulaClass doesn't have the right surface and is kept internal.  PAClient uses FormulaClass, not ParseResult.
2. Have consistency between CheckResult and ParseResult, particularly around error handling
3. consistent semantics of null vs empty enumerables.
4. Consistent error vs. warning settings - creating a default ErrorObject leaves the severity enum empty which defaults to warnings.
5. Needed to allow ParserOptions.
6. added some xml comments
7. There are multiple error objects. (public vs. internal) and need to expose public ones for ParseResult, but keep internal accessible for unit tests.
Add some tests.
=> Expose ParseResult.

src/libraries/Microsoft.PowerFx.Core/Functions/DLP/RequiredDataSourcePermissions.cs, src/libraries/Microsoft.PowerFx.Core/Functions/Publish/Capabilities.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs
Transport Generation now supports internals, and these shouldn't be on our public surface.
=> Remove two unneeded transport publics

src/libraries/Microsoft.PowerFx.Core/Public/Config/PowerFxConfig.cs, src/libraries/Microsoft.PowerFx.Interpreter/ReflectionFunction.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/CustomFunctions.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
We deal with function overloading via suffixes. For builtins, it's easy to come up with a suffix ("Find" vs. "Find_T"). But for customer builtins, we need to generate the suffix automatically using param types.
=> Allow custom functions to be overloaded.

README.md, src/build/PublishToCoveralls.ps1
This allows the PowerFx-PR pipeline to publish coverage to coveralls.io.
It also sets up a coverage badge in the readme.
(After this PR is merged, a pipeline run, then another PR will finalize the badge.)
=> Add PublishToCoveralls.ps1 and coverage badge

src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IIntellisenseContext.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/Intellisense.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseContext.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseData/IntellisenseData.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/SuggestionHandlers/CleanupHandlers/ISpecialCaseHandler.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/SuggestionHandlers/CleanupHandlers/StringSuggestionHandler.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/TokenTextSpan.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/TokenType.cs
They're internal classes, and PAClient relies on their specific namespaces because of JS codegen.
=> Fixup internal intellisense namespaces.

src/libraries/Microsoft.PowerFx.Core/Errors/BaseError.cs, src/libraries/Microsoft.PowerFx.Core/Errors/IDocumentError.cs, src/libraries/Microsoft.PowerFx.Core/IR/IRContext.cs, src/libraries/Microsoft.PowerFx.Core/Localization/Span.cs, src/libraries/Microsoft.PowerFx.Core/Public/ExpressionError.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionErrorTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs
Move Span from : 
`Microsoft.PowerFx.Core.Localization.Span` to `Microsoft.PowerFx.Syntax.Span`.
This is part of a set of namespace changes. see #361 for details.  
This is part of the public  surface area and many products will depend on it. 
This is primarily provided by Syntax nodes, as well as for error ranges. 
This is a public class.
It also has [TransportAttribute] on it.
=> Move Span to the Microsoft.PowerFx.Syntax namespace.

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/PowerFxConfigExtensions.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/ResolvedObjectHelpers.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/SetFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngineWorker.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcFormulaInfo.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterExpressionTestCases/ParallelAsync.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/PowerFxEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SetFunctionTests.cs
Allow interpreter to add Set() function which just maps to RecalcEngine.UpdateVariable.
- must be explicitly enabled by the host (since many hosts will not want this). 
- only works for firstname nodes.  
- requires that the variable was already declared. 
- type or arg1 must match exactly  to arg0.
=> Set function 

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Functions/Delegation/DelegationStrategies/InOpDelegationStrategy.cs, src/libraries/Microsoft.PowerFx.Core/Types/DType.cs
MultiSelect Optionsets are currently not supported with the **in** operator, so customers didn't have an easy way to filter records based on the multi-select optionset column, with this change we will now be able to support In operator filtering on these columns in both delegated and non delegated queries.
example: If we need to filter a column - > states visited by a contact (multiselectoptionset) 
The formula would look like this:
**Filter(Contacts,multiselect_state in SelectedStates)**
with this PR we support the both delegated and non delegated scenarios:
1. Delegated query :https://org7c2cf9ed.crm10.dynamics.com/api/data/v9.0/contacts?$filter=Microsoft.Dynamics.CRM.ContainValues(PropertyName=%27cr7fe_multiselect_state%27,PropertyValues=[%27304050000%27])%20and%20Microsoft.Dynamics.CRM …
=> Adding support for MultiSelect optionset with In operator

src/Directory.Build.props
Our URLs on nuget.org point to our now-deleted staging repo from before open sourcing the language. This fixes that.
=> Fix nuget package URLs

src/libraries/Microsoft.PowerFx.Core/Utils/CharacterUtils.cs, src/libraries/Microsoft.PowerFx.Core/Utils/DName.cs, src/tests/Microsoft.PowerFx.Core.Tests/DNameTests.cs
CJK languages use full-width space characters along-side the regular space (half-width in CJK), these should also be allowed in DNames. Switching to disallow line breaks and tabs rather than restrict most whitespace characters
=> Only disallow line breaks and tabulation

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/UntypedObject.cs
This flag should never have been set to true on these functions.
=> Remove the hidden flag from ParseJSON, Index_UO

src/libraries/Microsoft.PowerFx.Interpreter/Functions/CommonErrors.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUnary.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/BasicCoercion.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Boolean.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text.txt
Text(Blank()) will now return Blank() instead of ""
Boolean("True") => true, but Boolean(" true") => Error
=> Update Boolean and Text functions to have parity with TS

src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs, src/tests/Microsoft.PowerFx.Core.Tests/BindingEngineTests.cs
Engine has two `Check` overloads:
- `Check(string, ...)` and
- `Check(ParseResult, ...)`
The first one takes `ParserOptions` as an argument, while the second does not. This seems intuitive since the second one does not perform any parsing. However, `ParserOptions` have `AllowsSideEffects` property, which is in the first case passed down to the binder, and in the second is not.
=> Add option param to Engine.Check overload

src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Boolean.cs, src/tests/Microsoft.PowerFx.Core.Tests/FunctionTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/ThreadingTests.cs
This test can fail in PAClient even though the change was in PowerFx and the PowerFx build passed. This change adds this test to PowerFx so that we can catch the failures here, instead of in the PAClient pipeline.
=> Port TestAllBuiltinFunctionsHaveParameterDescriptions from PAClient

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Entities/QueryOptions/TabularDataQueryOptions.cs
Intention is to have the limit on selects handled on the client rather than the server in case we have a large url generated.
This change would help with an edge case where we don't see lookup fields in player when we have a large number of selects.
=> Remove max selects limit

src/libraries/Microsoft.PowerFx.Core/Public/Config/PowerFxConfig.cs
Fix a binary breaking change from #444 
Adding a default param to a ctor is a binary breaking change.
=> Fix a breaking change from #444.

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/ColorValue.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/DateTime.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/GUID.cs
Not sure how we missed this. The JS translator was producing the wrong output when tested locally.
=> Fix missing overrides in new UO functions

src/build/yaml/powerfx-ci.yml
This allows the packages and contract version for API valiadation to be defined in the [Azure DevOps pipeline definition](https://dev.azure.com/FuseLabs/SDK_v4/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=1470&view=Tab_Variables). That way, .yml code revisions are not required to update those values.
=> Define vars PackagesToValidate, ApiContractVersion in Azure

src/libraries/Microsoft.PowerFx.Core/IR/BinaryOpMatrix.cs, src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/libraries/Microsoft.PowerFx.Core/IR/Nodes/BinaryOpKind.cs
Today, the Coercion Matrix is shared with the JS code generation logic, without going through the IR. This separates out the Binary Op matrix as well, and enables sharing that with JS. 
This makes the eventual work of converging IR and JS easier, and also will make #380 easier to integrate.
=> Separate out BinaryOp IR Matrix to be sharable with JS code generator

src/build/yaml/ci-post-to-github-steps.yml, src/build/yaml/powerfx-ci.yml
Add a task to the CI pipeline that deletes outdated API compatibility results from the PR when new results are published. This prevents a PR from accumulating multiple sets of compatibility results.
=> Add task to delete outdated API compat results

src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/ReflectionFunction.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/CustomFunctions.cs
Binds as:
SetProperty(source.Prop, newValue)
But invokes as:
SetProperty(source, "Prop", newValue)
This is tactical and avoids new public surface, but should be handled by TypeRules.
=> Extend ReflectionFunction to handle SetProperty().

src/libraries/Microsoft.PowerFx.Core/Types/DType.cs
This was accidentally removed in #471, caught by tests in PA Client
=> Add back missing condition for Accepts

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryMath.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Round.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/RoundDown.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/RoundUp.txt
- Issue was caused by floating point error due to multiplication. 
- Changed multiplication of "m" to division. Also added new test cases!
=> Rouding error fixed (#488)

src/build/yaml/powerfx-ci.yml
In the [experimental]PowerFx-CI pipeline, API validation against our private Azure feed does not work for a fork because forks do not have OAuth access.
This skips validation for those cases.
=> Add a skip API validation for forks

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Types/DType.cs
This change basically restricts a scalar value like optionsetvalue to be used in the IN operator with a MultiselectOptionset Table, this has resulted in issues where formulas in App don't work in edit mode until they are forced to be reevaluated
=>  prevent support scalar in MultiselectOptionset table

src/build/yaml/feed-setup-step.yml, src/build/yaml/get-contract-version-step.yml, src/build/yaml/powerfx-ci.yml
Allow API validation for forks in the [experimental]PowerFx-CI pipeline: the Azure feed is public, so no secret is used there.
(We still must skip pushing results to the PR for forks. A secret is used there.)
=> Remove skip API validation for forks

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Functions/Delegation/DelegationStrategies/InOpDelegationStrategy.cs, src/libraries/Microsoft.PowerFx.Core/Functions/Delegation/DelegationStrategies/OpDelegationStrategy.cs
From the test case, TableA.Optionsetcolumn in multiselectOptionset was supported previously as a delegable call to dataverse resulting in errors, this PR makes it non-delegable.
Ex: Filter(Accounts, optionsetValue in MultiselectTable)  // is now non delegated, instead of being a delegable call.
Filter(Accounts, 'Primary Contact'.optionsetcolumn in MultiselectTable) supported.
=> scalar in table optionset

src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs, src/libraries/Microsoft.PowerFx.Connectors/PowerPlatformConnectorClient.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/OpenApiExtensionTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorTests.cs
Connectors: 
- allow use of Swagger document in lieu of endpoint (retrieve it automatically, when available)
- disallow endpoints starting with http://
=> Power Fx connector improvements

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt
An issue uncovered in the bug bash. DateValue and DateTimeValue both need to work with the output of the other function.
=> Update DateValue_UO and DateTimeValue_UO to use TS semantics

src/build/PublishToCoveralls.ps1
This fixes PublishToCoveralls.ps1 which was installing a Powershell patch that fixed a path separator bug. 
The patch is no longer available. That broke PublishToCoveralls.ps1, making the "Upload Coverage Files" task fail in the PowerFx-PR pipeline.
Also implement codecoverage.exe access for VS 2022 installations.
=> Fix PublishToCoveralls.ps1

src/build/PublishToCoveralls.ps1
PowerFx-PR pipeline still fails to upload coverage report to coveralls.io.
The fix: upgrade coveralls.net to 4.0.1 in src/build/PublishToCoveralls.ps1.
=> Fix the Upload coverage files task

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Time.txt
Date/Time implicitly are comparable, however the binder does not mark this as a coercion to DateTime, even though it should. This fixes that, and allows the binary op matrix to correctly generate IR for this.
=> Mark Date <-> Time Coercions in binder

src/libraries/Microsoft.PowerFx.Connectors/OpenApiHelperFunctions.cs, src/libraries/Microsoft.PowerFx.Connectors/OpenApiParser.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorTests.cs
To be consistent with Power Apps, we need to remove unsupported characters like underscore, dashes, ...
=> Fix OperationId name

src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs
This change moves the UO funcitons into the Library dictionary. Prep required for PAClient clean up tasks before shipping to Prod.
=> Move UO functions into the library dictionary

src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterSuggestTests.cs
- display name for records in RowScope
- display name for option sets.
=> Add new intellisense test for top-level  display names

src/libraries/Microsoft.PowerFx.Interpreter/Environment/ReadOnlySymbolValues.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/IRandomService.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryMath.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryTable.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/StandardErrorHandling.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
This PR shows how we can use the new Dependency Injection support from #503 to have Rand() use a rand service, rather than just call Random directly. 
See the new unit test.
=> Use ServiceProvider for Rand() 

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryDate.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/DateValue.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Value.txt
Existing function was always using System's Culture info, and did not take in account that culture info can be passed in the argument.
=>  DateTimeValue error fixed (Issue #493)

src/libraries/Microsoft.PowerFx.Interpreter/Functions/CommonErrors.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryDate.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/DateValue.txt
The expected error for when an invalid language code is passed to functions should be BadLanguageCode. This also updates expected results in DateValue tests to not rely on being run on en-US locale.
=> Update error for invalid language code + expected value for date tests

src/libraries/Microsoft.PowerFx.Core/Public/Config/PowerFxConfig.cs, src/tests/Microsoft.PowerFx.Core.Tests/CompatTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/DateValue.txt
Add back some deprecated functionality that Prose depends on. 
Add tests.
=> Fixes to integrate into PowerApps

src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/SuggestionHandlers/ErrorNodeSuggestionHandlerBase.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs
If the parent of the current node is a string interpolation node, we won't provide any error suggestions - suggestions should only be provided inside the island.
=> Do not provide Intellisense error suggestions in string interpolation

src/libraries/Microsoft.PowerFx.Core/Public/Types/AggregateType.cs, src/libraries/Microsoft.PowerFx.Core/Types/BuiltInLazyTypes/AttachmentType.cs, src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/libraries/Microsoft.PowerFx.Core/Types/LazyTypeProvider.cs, src/tests/Microsoft.PowerFx.Core.Tests/LazyTypeTests.cs
This allows derived record types a bit more control over how they're referred to in Error Messages.
=> Add user-visible type name for derived record types

src/nuget.config
Project was missing a nuget.config, and was using only the local configuration. This removes a point of dependency on local environments.
=> Add nuget.config to pull from Nuget.Org

src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/tests/Microsoft.PowerFx.Core.Tests/DTypeTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/LazyTypeTests.cs
Found from integrating #520, dropping a type should be allowed even if it's not present (it's just a no-op in that case)
=> DType.DropMatching should be non-erroneous to call if the type isn't present

src/libraries/Microsoft.PowerFx.Interpreter/Functions/StandardErrorHandling.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/SqrtT.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/SqrtT_ConsistentOneColumnTableResult.txt
Single column table functions should work with any table that has a single column. Currently it is only working for tables where the column is named 'Value'
=> Fix StandardSingleColumnTable to work with different input schemas

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/RoundTable.txt
Missing functionality in the interpreter. This function will be useful for adding tests for tabular versions of other numeric functions.
=> Add implementation for tabular version of Round function

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Binding/BinderCheckTypeResult.cs
Small change to CheckType in Binder.cs to move the main logic to a static helper, which is more functional (a mapping of inputs to outputs).
=> Make CheckType more functional

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Binding/BinderCheckTypeResult.cs
A big one, this changes PostVisitBinaryOpNodeAddition to be a mapping of inputs to outputs. This change also makes BinderCheckTypeResult a class instead of a readonly struct. This allows the Coercions property to default to an empty list instead of defaulting to null, removing the need to check for null when consuming the coercions list.
=> Make PostVisitBinaryOpNodeAddition more functional

src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/tests/Microsoft.PowerFx.Core.Tests/DTypeTests.cs
This DType overload is rarely used, and appeared untested in this repo. Fixes a recent break caused by #599 and adds test
=> Fix TryGetType DPath overload

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs
This started failing with #610.
Note in debug tests, we hit an Contract assert in binder in _binding.ResultType.
In PAClient, it uses retail FxCore, so contracts are disable, and hence we fail in
=> Port TexlTest.cs to FxCore.

src/libraries/Microsoft.PowerFx.Core/Public/Types/AggregateType.cs, src/tests/Microsoft.PowerFx.Core.Tests/TypeTests.cs
-Updates TryGetFieldType to check for null/empty DNP in-case derived types did not provide DisplayNameProvider.
=> Updates TryGetFieldType to check for null/empty DNP

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs
CheckEqualArgTypes
CheckComparisonArgTypes
CheckComparisonOneOf
These functions are all used by the PostVisit method for Binary op nodes and need to be made functional.
Also makes the PostVisit functions for both Binary and Unary op nodes more functional.
=> Make outstanding binary op node dependencies more functional

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/CollectionTableValue.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/TableValue.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/PowerFxConfigExtensions.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/RemoveFunction.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Remove.txt, src/tests/Microsoft.PowerFx.Core.Tests/TableValueMutationTest.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RemoveFunctionTests.cs
Initial push for [**Remove( DataSource, Record1 [, Record2, ... ] [, All ] )**](https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-remove-removeif#syntax) implementation.
- Still working on a better way to find matching records.
- Working on adding extra test cases for SDK, compiler and interpreter.
- RemoveAsync returns a Boolean. Maybe there is a better way.
- Good approach to get a range of elements from array.
- Any other improvements.
=> Remove function initial draft

src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/IRTests.cs
EvalVisitor is not implemented on AggregateCoercionNode for records, but the coercion matrix frequently produces this node in expressions like 'Patch(MyTable, { Currency: 1.2 }, { Currency: 1.5 })' when the Currency column is a DType.Currency.
We should eventually implement RecordToRecord coercion, but as a first stop, don't emit this coercion node if there actually aren't any coercions used
=> IR translator update - don't add unneeded AggregateCoercionNode

src/libraries/Microsoft.PowerFx.Core/Binding/BinderUtils.cs
Dataflow Analysis uses IErrorContainer instead of ErrorContainer. The Binder utils does not need to use anything on the concrete class. So we use the interface instead.
=> Change ErrorContainer to IErrorContainer in BinderUtils

src/libraries/Microsoft.PowerFx.Core/Public/Config/ComposedReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/PowerFxConfig.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/ReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseProvider.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs
If the config has a chained symbol table:
powerFxConfig.SymbolTable = new SymbolTable() { Parent = dataverseConnection.Symbols };
Then expressions like this get a null ref:
(IEnumStore) config.EnumStoreBuilder.Build(),
because config.EnumStoreBuilder is just config.SymbolTable.EnumStoreBuilder, which is null.
It's not enough to just initialize SymbolTable.EnumStoreBuilder to non-null, we need to ensure the symbols are actually composing.
This runs all Suggest tests in both configurations.
Marking config.EnumStoreBuilder as obsolete.
PowerApps doesn't call config.EnumStoreBuilder.
Dataverse does, but those call should config.EnumStore instead.
This was related to #503.
=> Fix crash in enumbuilder.

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs
As a part of the feature I am working on , I need to modify the script as below for all the tables, for that I will need all the table nodes.
`[{a: 1}, {a: 2}] -> [{value: {a:1}}, {value: {a:2}}]`
=> Added GetTableNodes() to binder

src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/PatchFunction.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Patch.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/DatabaseSimulationTests.cs
Such expression requires record to record coercion which wasn't implemented
Patch(Table2, Lookup(Table2, Table2=GUID("802dcedc-492f-ed11-9db2-0022482aea8f")), {MyDate:  "2022-9-14 7:11:04 pm" })
Before this fix, the error message we were returning was "unknown error", now, it will provide a clear error message, asking for MyDate to be a DateTime and not a string.
=> Fix error message when record to record coercion might be needed

src/libraries/Microsoft.PowerFx.Core/Functions/Delegation/DelegationStrategies/InOpDelegationStrategy.cs
A recent change to prevent delegation of Filter(TableA.Optionsetcolumn in multiselectOptionset) (https://github.com/microsoft/Power-Fx/pull/522 ) regressed a delegable scenario for singleSelectOptionSet in Collection to be non delegable, adding an explicit check to not delegate if the in operator is used on a async node instead of checking for !IsAggregate.
TestCases added in Client repo
=> Fix delegation warning to be only if Async Nodes when In operator is used.

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/DateTime.cs, src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs
A recent change caused an exception to be thrown if an invalid tabular DateAdd function was used. This fixes it and adds a new test to check this scenario.
=> Check invocation result fail prior to get tabular result

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/IsNumeric.txt
The IsNumeric function should return true for string values that represent, as well as to date, time and date/time values (which has a natural conversion to numbers)
=> Fix IsNumeric implementation

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/UntypedObject.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt
Index_UO was implemented before Index, and was implemented incorrectly. This change adds a runtime suffix for Index_UO.
=> Add runtime suffix for Index_UO

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Functions/FunctionScopeInfo.cs, src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/ForAll.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/StandardErrorHandling.cs, src/libraries/Microsoft.PowerFx.Interpreter/IScope.cs, src/libraries/Microsoft.PowerFx.Interpreter/SymbolContext.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt
Adds the ForAll function for UntypedObjects. A very bizarre change with some hacky type checking.
The problem is that overloaded functions with lambdas are not evaluated bottom-up. This is because some of the arguments may be lambdas. It leads to a chicken and egg problem: you need to know the override before you can determine that an argument is a lambda, but you need to know which arguments are lambdas in order to pick an override.
Thus we enforce that only a single override is allowed to have a lambda. It is assumed to be a table, and we type check the first argument quite late.
This implementation piggybacks off of all existing code paths by "tricking" the type checker into thinking that there is only 1 override. It will then "switch" the selected override at the last second if it's …
=> Initial work on UntypedObject ForAll

src/libraries/Microsoft.PowerFx.Core/Functions/BuiltinFunction.cs, src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/ColorFadeT.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/LeftRight.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Log.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Mid.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Power.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Replace.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Round.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/StringOneArgFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Substitute.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Trunc.cs, src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs
- Fixes #709 where multiple functions did not return consistent result even with  ConsistentOneColumnTableResult flag enabled.
- Fixes #710 Added tests for checking the same in TexlTests.
=> Inconsistent result with ConsistentOneColumnTableResult flag enabled.

src/libraries/Microsoft.PowerFx.Core/Public/Values/RecordValue.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Escaping.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestHelpers/TestRunner.cs
The record serialization was escaping property names incorrectly. This fixes it.
=> Updated serialization to properly escape record property values

src/libraries/Microsoft.PowerFx.Interpreter/ParsedExpression.cs
Null values can be passed in; once we find out all the places where this is happening, we can tighten up the .ctor again.
=> Allow null culture info in ParsedExpression .ctor

src/libraries/Microsoft.PowerFx.Interpreter/Environment/ComposedReadOnlySymbolTableValues.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/ReadOnlySymbolValues.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/RowScopeSymbolValues.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/PowerFxEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SymbolValueTests.cs
This is critical in dataverse scenarios, since those are lazy RecordType/RecordValues, and loading all the fields is expensive.
Also includes Compose() functionality for chaining symbol tables.
=> Make ReadOnlySymbolValues.NewRowScope be lazy.

src/libraries/Microsoft.PowerFx.Core/Types/DType.cs
Breaking internals, as part of a PR in PAClient to no longer drop attachments in Update/UpdateIf, etc. Interestingly, we do not appear to have code coverage for this code path.
=> No longer drop attachments in DType

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/CollectFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/RemoveFunction.cs
Removes the other places where Attachments were being dropped. Once again, these did not have code coverage.
=> Do not drop attachments in Remove, Collect

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/StandardErrorHandling.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/EndsWith.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Find.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Index.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Replace.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/StartsWith.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Substitute.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/string.txt
Blank values should be coerced to empty strings (`""`) or zero (`0`) when passed as inputs to string or numeric arguments in functions. This change updates text functions to do so.
=> Update blank value handling for text functions in the C# interpreter

src/libraries/Microsoft.PowerFx.Core/Public/Values/PrimitiveValueConversions.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/MarshalTests.cs
- fixes #737 .
- Added test for the same.
=> Fixes Nullable fields cause symbol generation to fail when using marshaller

src/libraries/Microsoft.PowerFx.Core/Parser/ParseResult.cs, src/tests/Microsoft.PowerFx.Core.Tests/FormatterTests.cs
Issue #766.
New **ParseResult.GetAnonymizedFormula()** method is public but interfaced used to inject behavior to **StructuralPrint** aren't:
- **TexlBinding**
- **ISanitizedNameProvider**
What's the best approach?
Update: checked internally. Injection classes won't be exposed (for now).
=> Exposing anonymized method for logging 

src/libraries/Microsoft.PowerFx.Core/Public/ErrorKind.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Concatenate.cs, src/libraries/Microsoft.PowerFx.Core/Types/Enums/EnumStoreBuilder.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/StandardErrorHandling.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Concatenate.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Concatenate_ConsistentOneColumnTableResult.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/FindT.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/FindT_ConsistentOneColumnTableResult.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/RoundTable.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TableStringFuncs_ConsistentOneColumnTableResult.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TableStringfuncs.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TabularOverloadsBlanksAndErrors.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TabularOverloadsBlanksAndErrors_ConsistentOneColumnTableResult.txt, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/FunctionDefinitionTests.cs
```
Semantics of tabular overloads of scalar functions with errors / blanks / empty tables (and examples)
•	Functions with single arguments:
o	F(<err>) ==> <err>
	Sqrt(If(1/0<2,[1,2,3])) ==> #Error(Kind=Div0)
o	F(<blank>) ==> <blank>
	Sqrt(If(1<0,[1,2,3])) ==> Blank()
o	F(<empty table>) = <empty table>
	Sqrt(Filter([1,2,3], Value > 10)) ==> []
•	Functions with multiple arguments, errors
o	F(<error table>, <scalar>) ==> <error table>
	Power(If(1/0<2,[1,2,3,4]), 2) ==> #Error(Kind=Div0)
o	F(<table>, <error scalar>) ==> ForAll(<table>, F(<value>, <error scalar>))
	Power([2,3,4], 1/0) ==> [<div0>, <div0>, <div0>]
o	F(<error scalar>, <table>) ==> ForAll(<table>, F(<error scalar>, <value>))
	Power(1/0, [2,3,4]) ==> [<div0>, <div0>, <div0>]
•	Functions with multiple arguments, blanks
o …
```
=> Fixes Multi arg table function to be compatible with Excel

src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorTests.cs
Getting some test failures because we compare \r\n to \n. 
Just ignore the \r
=> fix tests - ignore comparing \r.

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/AsType.cs
Fixes a bug in the AsType type checking, where it was calling Single without checking the size of the list first. Unfortunately, the AsType function does not appear to have any code coverage.
=> [Bug] AsType type checking array size guard

src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Remove.txt
Locks `All` in the error string. Also, changes this to use the fully qualified enum in the error message.
=> RemoveFlags.All should be locked in error string

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs
Adds the Obsolete attribute to CheckInvocation, to prevent it from being overridden or invoked within PowerFx.
=> Mark CheckInvocation as Obsolete

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Parser/ParserOptions.cs, src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/Features.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/PowerFxConfig.cs, src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseData/IntellisenseData.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/SuggestionHandlers/FirstNameNodeSuggestionHandler.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/FlagTests.cs
Fixes #698 
- Removed support for row-scope disambiguation syntax.
- Removed support from intellisense for the same.
Now, user would need to use
`Filter(A, ThisRecord.Value = 2)` or `Filter(A As Foo, Foo.Value = 2)`
instead of 
`Filter(A, A[@Value] = 2)`
=> Removed support for row-scope disambiguation syntax.

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Entities/External/IExternalDataSource.cs, src/libraries/Microsoft.PowerFx.Core/Entities/External/IExternalDelegable.cs, src/libraries/Microsoft.PowerFx.Core/Entities/External/IExternalNamedFormula.cs, src/libraries/Microsoft.PowerFx.Core/Functions/FunctionArgValidators/ConnectedDataSourceInfoArgValidator.cs
This change adds ability for named formula rules to participate in pageability/delegable checks. This will provide support for extending pageable support for named formula rules. I will have the unit tests added on PaClient once I have that change ready for PR.
=> Delegation support for named formula rules

src/libraries/Microsoft.PowerFx.Core/App/ErrorContainers/LimitedSeverityErrorContainer.cs, src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Binding/BinderUtils.cs
Adds a "record and replay" feature to the error container that is being used by TryGetBestOverload. This is so that, when functions want to use CheckTypes/CheckSemantics instead of CheckInvocation, semantic errors that do not contribute to a type checking error can be "replayed" in the case where type checking succeeds.
A new error container is created per-function, so only the errors generated for a single function are added to the list.
This should greatly reduce the number of failures in PAClient test labs as we migrate functions to use the new methods.
=> Add record and replay feature to LimitedSeverityErrorContainer

src/libraries/Microsoft.PowerFx.Interpreter/ReflectionFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Values/LambdaFormulaValue.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/CustomFunctions.cs
- Fixes #777 
- When Custom function will have error as Arg we would report those errors before trying to invoke the function.
- If Custom function has Blank() as arg and expected type is NumberValue then we would treat it as 0, if expected type is StringValue then we would treat it as empty string.
- Added test to demo the same.
=> Custom function error handling. Fixes #777

src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/DateAdd_TimeZone_Seattle.txt
The use of TimeZoneOffset() is only valid when associated with Now()
If not used with Now(), we need to specify the date/time to which it applies
=> Fix TZI tests

src/libraries/Microsoft.PowerFx.Core/Functions/Delegation/DelegationStrategies/OpDelegationStrategy.cs
There was a regression related to the change :https://github.com/microsoft/Power-Fx/pull/638 , that caused NullreferenceException with the FilterFunctionTranslator when using formula's like : Filter(Table,ColA in Trim(Split(ColB, ",")))
=> Fix issue with IsRowScope check in  delegation with "in" operator

src/libraries/Microsoft.PowerFx.Core/App/ErrorContainers/LimitedSeverityErrorContainer.cs
The original changes to LimitedSeverityErrorContainer did not include support for the Errors function call. This change adds support for Errors with a new FrozenInvocation.
=> Add support for Errors FrozenInvocation

src/tests/Microsoft.PowerFx.Connectors.Tests/Helpers/LoggingTestServer.cs
Suppress the error from latest .NET code analyzer so builds can succeed.
=> suppress error from latest analyzer.

src/tests/Microsoft.PowerFx.Interpreter.Tests/Scenarios/CustomRecordTypeWithUndefinedFields.cs
- Fixes #833 
- Fixed Equals method on `TreatMissingFieldAsUntypedRecordType`
- Added the test as mentioned in #833
=> Accept on Custom Records was failing due to incorrect equals method.

src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt
Accessing a field in an untyped object which is not a record is currently returning an error with kind BadLanguageCode. That kind is used when an argument is the language/locale to functions such as Value and Text. The correct error kind should be InvalidArgument.
=> Update error kind for accessing field in untyped object

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryMath.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Dec2Hex.txt
`#NUM` errors from Excel should map to Numeric error kinds. The new Dec2Hex function doesn't follow that. This change updates it.
=> Update expected error kind for Dec2Hex function

src/libraries/Microsoft.PowerFx.Core/Binding/BinderUtils.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Text.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Value.txt, src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs
The Text function has a static check that the format argument should not have both numeric and date/time specifiers. This logic will change (once we support `0` as the specifier for fractional seconds, as Excel does), and it isn't implemented correctly. This change updates it to cover more constant values. Notice that this should not be a replacement for a runtime check, since the format can come from expressions, variables, which are not captured by a static check.
=> Update static format check for Text function

src/libraries/Microsoft.PowerFx.Core/IR/Nodes/ResolvedObjectNode.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/ComposedReadOnlySymbolValues.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/ReadOnlySymbolValues.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SymbolValueTests.cs
Ran through Codecoverage and caught some missing blocks. 
Notably enforce that we can't try to associate 2 SymValues with the same SymTable - and that we give a helpful error mssage.
=> More test coverage on SymbolValues

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Concat.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Lookup.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Concat.txt, src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs
Currently the Concat function disallows coercions to its parameters, but there is nothing that should prevent that from happening. This change removes that restriction, and adds tests to validate that coercions work as intended.
=> Allow coercions in the Concat function

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Value.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ErrorKinds.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Value.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/Scenarios/ScenarioDotNetObjectWrapper.cs
As part design changes to ParseJSON, Boolean, Text, and Number values are supported in all 3 constructors. This change  also fixes tests which were expecting an error, which is a breaking change in PAClient.
=> Allow Boolean, Number, and Text values in respective UO constructors

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/PowerFxConfig.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/ReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/DisplayNames/SingleSourceDisplayNameProvider.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseData/IntellisenseData.cs, src/tests/Microsoft.PowerFx.Core.Tests/DisplayNameOptionSetTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/DisplayNameTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ConfigTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
- Adds support for display name for top level variable via Symbol Table.
- Added tests in src/tests/Microsoft.PowerFx.Interpreter.Tests/ConfigTests.cs/TopLevelVariableDisplayName and src/tests/Microsoft.PowerFx.Core.Tests/DisplayNameTests.cs/CollisionsThrow
- I have ran a buddy build with PA Client and have verified there's no impact of removing/changing the internal methods.
User's can now supply display name via Symbol Table as below:
var symbol = new Symbol Table();
symbol.AddVariable("logicalName", FormulaType, "DisplayName");
Fix #779
=> Add support for display name for top level variables.

src/Directory.Build.props, src/Microsoft.PowerFx.sln, src/libraries/Microsoft.PowerFx.Core/Public/Config/Features.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SymbolValueTests.cs, src/tests/Microsoft.PowerFx.Performance.Tests/Microsoft.PowerFx.Performance.Tests.csproj, src/tests/Microsoft.PowerFx.Performance.Tests/PerformanceTest1.cs, src/tests/Microsoft.PowerFx.Performance.Tests/Program.cs, src/tests/Microsoft.PowerFx.Performance.Tests/UnitTests/PerformanceTests.cs
Add Benchmarck.Net profiling project to measure performance of key PowerFx APIs.
This console app needs to be compiled in release mode and will produce results like the example below.
Notice that these results will depend on the machine used.
| Method |   N |         Mean |      Error |     StdDev |          Min |           Q1 |           Q3 |          Max |
|------- |---- |-------------:|-----------:|-----------:|-------------:|-------------:|-------------:|-------------:|
|  Parse |   1 |     5.634 us |  0.0343 us |  0.0304 us |     5.579 us |     5.625 us |     5.652 us |     5.677 us |
|  Check |   1 |    56.129 us |  1.0138 us |  0.8465 us |    55.568 us |    55.673 us |    56.153 us |    58.825 us |
|   Eval |   1 |    57.456 us |  0.3150 us |  0.2947 us |    56.932 us |    57.324 …
=> Add Benchmarck.Net profiling project

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryColor.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ColorFade.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ColorFadeT.txt
- JS backend maps Blank() color to Color(0, 0, 0, 1) and Blank() fadeDelta to 0.
=> For ColorFade() Blank() should be map to default value.

src/libraries/Microsoft.PowerFx.Core/Public/Config/SlotMap.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTable.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/ComposedReadOnlySymbolValues.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/SymbolExtensions.cs, src/libraries/Microsoft.PowerFx.Interpreter/ParsedExpression.cs, src/tests/Microsoft.PowerFx.Core.Tests/SlotMapTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SymbolValueTests.cs
Add check that eval has SymbolValues that match the SymbolTable it was bound against.
Add tests for SlotMap.
=> Add safety check for SymbolValues

src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/AddColumns.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/DropColumns.txt
Some of the recently added tests for those functions have an extra ';' which is making the error that the test was intended to cover.
=> Fix [Add/Drop]Columns tests

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryColor.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ColorFade.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ColorFadeT.txt
Blank values in a color context should be interpreted as RGBA(0,0,0,0)
=> Update blank handling for ColorFade function

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Text.cs, src/libraries/Microsoft.PowerFx.Core/Utils/TextFormatUtils.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/CommonErrors.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/NotYetReady/Text_Format.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text_Format.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Time.txt
Issue #869. 
This PR expanded from its original scope and now is handling 4 bugs:
> Text function: millisecond format specifier should be '0' not 'f'
> Text function can't handle numbers formatted as dates or dates formatted as numbers
> Text function doesn't handle date format specifiers like Excel
> Text function should return an error if both numeric and date format specifiers are passed to it
=> Text function doesn't handle date format specifiers like Excel

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Text.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text_Format.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterExpressionTestCases/Text_Format_Override.txt
#890 makes some Text() format arguments be compile-time errors (if they're literal).  This is handled in Text.cs and shared by all backends -so it impacts PowerApps.
Previously, they may have been runtime errors - which means each backend handles separately. 
Revert the change to Text.cs because that is shared with PowerApps - the change is making this a compile-time error (instead of runtime), which is causing PA to fail at compile time.  
Reverting this so that in effect 890 has no impact on PowerApps (the rest of 890 is interpreter-only changes). 
Here is a specific expression causing a problem: 
`Text(123.466, "[$-en-US]$#0.0M")`
Interpreter doesn't implement it yet (#932), so adding override to call it out.
=> Revert portion of #890

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Boolean.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Boolean.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/BooleanT.txt
- Fixes #489 
- Now TexlFunction provides an override that can be used via creating IR call node to rewrite the node.
- e.g. this is purely a fix in the IR for Boolean() - for Boolean(x) when x is a bool, it just emits x
=> Boolean(true) shouldn't be invalid

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text_Format.txt
.NET supports up to 7 sub-second digits, so we should support it in the Text function as well.
=> Allow more than 3 subsecond digits in the Text function

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/IR/CoercionKind.cs, src/libraries/Microsoft.PowerFx.Core/IR/CoercionMatrix.cs, src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson_Coercions.txt
Adds initial support for UO to Text, Number, Boolean, Date, Time, and DateTime coercions in functions which do not accept lambdas. Does not add support for UO to Table coercions. Functions which accept lambdas can never accept UO as the first argument without an explicit override. These explicit overrides will be added in future PRs.
=> Initial work on UntypedObject implicit coercions

src/libraries/Microsoft.PowerFx.Interpreter/Environment/BasicServiceProvider.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/ComposedReadOnlySymbolValues.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/ReadOnlySymbolValues.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/RuntimeConfig.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/SymbolExtensions.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/SymbolValues.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/ParsedExpression.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngineWorker.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ConfigTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/CustomFunctions.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/Helpers/AsyncVerify.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/PowerFxEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ServiceProviderTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SetFunctionTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SymbolValueTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/TimeZoneExtensions.cs
Fix #901 .
Breaking change to interpreter. Not impact to Core or PowerApps. 
Separate IServiceProvider from  ReadOnlySymbolValues.
This decouples two unrelated concepts and simplifies the contract. 
It also lets us enforce some stronger invariants - that SymbolValue and SymbolTable are 1:1.
New RuntimeConfig class which captures both SymbolValues and the ServiceProvider. 
This also means service provider helpers like SetCulture() are now moved off SymbolValue.
=> Split IServiceProvider out of SymbolValues

src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTableOverRecordType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/NamedFormulaType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/TableValue.cs, src/libraries/Microsoft.PowerFx.Interpreter/DebugDump.cs
Add new DebugDump* methods which can log SymbolTable, SymbolValues. 
This can help with debugging to provide visibility for these.  (like a text-based visualizer ... eventually ... https://learn.microsoft.com/en-us/visualstudio/debugger/create-custom-visualizers-of-data?view=vs-2022 ) 
For example:
```
CheckResult
x + y
Binding: Number
IR:
BinaryOp(AddNumbers, ResolvedObject('x:FromRecord_55206300'), ResolvedObject('y:Globals_31639720'))
Symbols:
SymbolTable '(FromRecord,Globals,BuiltinFunctions (149),DefaultConfig)_3776722', hash=1776687751
Composed {
SymbolTable 'FromRecord_55206300', hash=954974759
x:n
SymbolTable 'Globals_31639720', hash=954174782
y:n
SymbolTable 'BuiltinFunctions (149)_43315893', hash=954660935
```
=> Add debug logging helpers

.editorconfig
I'd like to tweak our Style Cop rules and disable these restrictions:
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0003-ide0009
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0007-ide0008
IDE003:
Today, we require 'var' instead of more explicit types --> I'd like to turn that off because a) sometimes the types are more readable; b) sometimes it's a nice enforcement check. 
We require:
`var sym = ComputeTables()  // not sure the type `
I want to allow:
`ReadOnlySymbolTable sym = ComputeTables()`
[2] we disallow 'this' qualifiers. --> I'd like to allow them as it also helps readability and being explicit.  
Today:
`var sym = SpecialValue` // I have to think where SpecialValue came from ... is it instance/static/ from …
=> Tweak 2 editor rules.

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/tests/Microsoft.PowerFx.Core.Tests/DisplayNameTests.cs
Single Column Table expressions (dotted names, with the lhs that's a table), are not supported in the interpreter. In Canvas, they have a subtle bug where the display name set for the resulting type is set to the field type rather than the base table's. This is incorrect, and leads to bugs when the base table was not associated with any child record/tables.
=> Fix display name bug for Single Column Table references

src/libraries/Microsoft.PowerFx.Interpreter/Environment/Governor.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Lookup.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/MinMax.txt, src/tests/Microsoft.PowerFx.Core.Tests/TestRunnerTests/InternalSetup.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/Helpers/BasicGovernor.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/Helpers/SingleThreadedGovernor.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/PowerFxEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineAsyncTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SandboxTests.cs
Fix #730 - better protection for expressions that generate large memory usage. 
Add "governor" service that can abort on large memory usage. Host can implement this and use GC functions to check memory usage and abort if an expression consumes too much memory.    Substitute() function has an inefficient implementation which provides one way to quickly consume memory (see #971 )
This coexists with other robustness checks like cancellation token and stack overflow. 
Functions can also "pre-poll" to calculate their memory usage and fail before they start executing. 
Refactored similar tests into a single location, "SandboxTests"
Add #setup so that it can be disabled by tests which intentionally use large memory.
We'll still need to review the rest of the code and enforce the checks are all …
=> Fix 730 - better protection for expressions that generate large memory usage.

src/libraries/Microsoft.PowerFx.Core/App/IExternalEnabledFeatures.cs, src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/strings/PowerFxResources.en-US.resx
Currently when a function property has an optional parameter and that parameter is omitted at reference, there is no error because we allow it. 
This change is to make sure that we throw an invalid reference error when this happens because we want function calls to end with parenthesis with or without parameter going forward.
Note: the added feature gate must be removed once ECS flag is completely rolled out.
=> Enforce parenthesis on reference to function property

src/libraries/Microsoft.PowerFx.Interpreter/CustomFunctionErrorException.cs, src/libraries/Microsoft.PowerFx.Interpreter/ReflectionFunction.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/CustomFunctions.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
Relates #1001  #999 
Before users had to loosen the return type to FormulaValue from Custom Function just to return an error, and due to that they were losing compile time strict type checking and the implementations were prone to errors of returning incorrect types.
Now instead of creating their own error, users can just throw `CustomFunctionErrorException` so they can keep the return type of `Execute` method strict and we populate the error with the correct return type.
Before they would do:
```csharp
public class CustomFunctionError : ReflectionFunction
{
public CustomFunctionError()
: base("CustomFunctionError", FormulaType.Number, FormulaType.Number) 
{
}
public static FormulaValue Execute(NumberValue arg) 
{
if (arg.Value < 0)
{
return CommonErrors.CustomError("arg should be greater …
```
=> Adds error handling via Exception for Custom Function.

src/libraries/Microsoft.PowerFx.Core/Public/Values/FormulaValueNew.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ValueTests.cs
Adds a convenient method to supply IEnumerable of errors to create ErrorValue.
Relates to #1001
=> Adds convenient method to supply IEnumerable of errors to create ErrorValue

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ForAll.txt
Fixes #952 
NOTE: Pretty Printing seems to still fail for the eval of below expression.
`With({L26:Table({x:1, y:2})}, ForAll([99], LookUp(L26, ThisRecord.y = 3)))` Issue filed for it #1028
=> Fixes #952 Crash in interpreter - Blank of record type with multiple fields

src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/tests/Microsoft.PowerFx.Core.Tests/CheckResultTests.cs
Regressed with CheckResult refactor in #993 . It was made private and renamed to AllSymbols.
We have clients that require this property to stay public.
=> CheckResult.Symbol needs to stay public 

src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Public/ExpressionError.cs, src/libraries/Microsoft.PowerFx.Core/Types/DTypeSpecParser.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/ComposedReadOnlySymbolValues.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryColor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/libraries/Microsoft.PowerFx.Interpreter/ParsedExpression.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionErrorTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/Helpers/DoNotUseCulture.cs, src/tests/Microsoft.PowerFx.Core.Tests/TestRunnerTests/TestRunnerTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ConfigTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/LanguageServerTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/TestPowerFxScopeFactory.cs
Allow Errors to be in separate culture info that parser. 
Fix #918, and also #1039. Sets up a fix for #990.  
Make ExpressionError.Message localize lazily.  
- Callers can get the localized message in any culture after the parse/bind
- just checking IsSuccess can then avoid localization since that doesn't read the message property 
Add test to ensure we're not using Thread.CurrentCulture when a culture is provided. 
- Update a bunch of usages.  StartsWith(), EndsWith() ,etc require StringComparison.Ordinal, else they will check current culture. 
- RegEx required CultureInvariant 
Add more tests
- add ExpressionErrorTests to get 100% code coverage on ExpressionError. 
- add MultiCulture* tests to demonstrate how we can set Parse/ErrorMessage/Runtime  cultures independently 
- remove …
=> CultureInfo support for errors

src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/IRTests.cs
Called when patching a record with different types of fields.
Example:
`With({t1:Table({a:stringVar})},Patch(t1,First(t1),{a:5}))`
=> Handling recordtorecord coercion

src/libraries/Microsoft.PowerFx.Core/Microsoft.PowerFx.Core.csproj, src/libraries/Microsoft.PowerFx.Interpreter/Microsoft.PowerFx.Interpreter.csproj
This was only used by System.Text.Json, which was removed in #957 .
=> We can remove Sytem.Memory reference

src/libraries/Microsoft.PowerFx.Core/Public/Config/DeferredSymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/ReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/DisplayNames/DisplayNameProvider.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/ComposedReadOnlySymbolValues.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/SymbolValues.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/IntellisenseTestBase.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs, src/tests/Microsoft.PowerFx.Core.Tests/SymbolTableTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SymbolValueTests.cs
Fix #1017 
Useful when names are known, but getting the list types is expensive -  common for dataverse tables. We can quickly get all tables in the org, but getting the table types requires EntityMetadata which is expensive.
=> Lazy loading of types for symbol tables 

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/StandardErrorHandling.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TabularOverloadsBlanksAndErrors.txt
Currently the implementation of the tabular function handler needs to make two passes over the function arguments to determine whether a blank or error value will be returned (if passed in a tabular context). This is inefficient, so we are updating the implementation to return the first of those values.
This change also simplifies the implementation of the tabular handler, to avoid copying the arguments multiple times.
=> Updated multiarg tabular function handler to return first error or blank tabular arg

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Public/ExpressionError.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Public/EditorContextScope.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/CheckResultTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/EditorContextScopeTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/LanguageServerTests.cs
Fix #958 - see for details. 
Also creates better symmetry between LSP's EditorContextScope and CheckResult.
This makes new CheckResult features (such as this one) available to LSP.
=> Fix #958 - allow LSP to enforce expected types

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/SortByColumns.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseHelper.cs, src/tests/Microsoft.PowerFx.Core.Tests/BindingEngineTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs
The [PR 1036](https://github.com/microsoft/Power-Fx/pull/1036) caused a regression in the intellisense for the SortByColumns function. This PR reverts that change, and adds a test that validates the previous behavior.
=> Revert SortByColumns changes to use identifiers as column names

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryDate.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/DateDiff_TimeZone_Lord_Howe_Island.txt
Fixes #1015 
Now instead of converting to UTC TZ, we subtract 1 hour from the time to accommodate DST.
This helps in cases where TZ has UTC offset.
e.g.
`DateDiff(DateTime(2005,12,31,23,59,59,999), DateTime(2006,1,1,0,0,0), TimeUnit.Hours)`
When converted to UTC from GMT+5:30 (IST), the expression would become
`DateDiff(DateTime(2005,12,31,18,59,59,999), DateTime(2005,12,31,18,30,0), TimeUnit,Hours)`
This would render the Hour the same due to offset having minutes in it.
Instead, Now for example,
`start = DateTime(2023, 3, 12, 0, 0, 0) is in UTC-8`
`end = DateTime(2023, 3, 12, 3, 0, 0) is in UTC-7`
`startUTCOffset - endUTCOffset = -1`
so adding that UTC offset difference to the end(instead of converting both to UTC) will adjust the subtraction for DST
while preserving hours, since cases …
=> Fixes the issue with TZ having minutes in utc offset.

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryDate.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/DateTimeUTCTests.cs
-Fixes `Today()` to honor the engine's timezone.
=> Today() did not honor engine's timezone.

src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/FirstLast.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/FirstLastN.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/ArrayUntypedObject.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt
First/Last for UO returns a UO containing the single item. FirstN/LastN returns a UO containing an array, even if only one item is requested. Should have similar Blank/Error handling semantics to the classic First(N)/Last(N) functions.
=> Implement First/Last and FirstN/LastN for UntypedObject

src/libraries/Microsoft.PowerFx.Core/Functions/ArgPreprocessor.cs, src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Atan2.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Char.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Concatenate.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/DateTime.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Dec2Hex.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Log.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/MathFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Mod.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Power.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/RandBetween.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Rgba.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Round.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Sequence.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Trunc.cs, src/libraries/Microsoft.PowerFx.Core/Types/Enums/ArgPreprocessor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryMath.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/StandardErrorHandling.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SandboxTests.cs
Fixes #1006 
- This moves the Trivial BlankToZero argument handler from interpreter to IR Phase so other backends don't have to implement it.
- BlankToZero is wrapping arg in IR as `arg` => `Coalesce(arg, 0)`
- To Improve efficiency if arg was already wrapped in that fashion we don't wrap it again.
- This PR also improves Concatenate Operator as below
Before: `"1"&"2"&"3"...` => `Concatenate(Concatenate("1", "2"), "3"))...`
Now: `"1"&"2"&"3"...` => `Concatenate("1","2","3",...)`
NOTE:Other Preprocessing will be moved to IRPhase in followup PRs.
=> Moves the blank value handling of function args to the IR

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/FirstLastN.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Index.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/UntypedObject.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/First.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Index.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt
Functions with scalar arguments should support coercions. Currently FirstN/LastN don't, so this PR changes it.
=> Allow parameter coercion in the FirstN/LastN functions

src/libraries/Microsoft.PowerFx.Core/Functions/ArgPreprocessor.cs, src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/LeftRight.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs
Fixes #808 
Follow-up to #1059 
This moves arg truncating for `Right()` and `Left()` which truncates the 2nd arg.
Now. in IR `arg => Truc(Coalesce(arg, 0))`
NOTE: Truncate Preprocessor also means it would add BlankToZero preprocessing as well.
=> Adds truncate arg preprocessing in IR.

src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TrigTableFunctions.txt
The trigonometric tabular tests use functions that don't return whole numbers (such as Pi() and other trig functions). This can make the results not match exactly depending on floating point behavior, so we're adding a Round call to those tests to make sure that the results are the expected ones in all platforms.
=> Add rounding to trig table tests

src/libraries/Microsoft.PowerFx.Core/Functions/FunctionArgValidators/DataSourceArgNodeValidator.cs
As nodes aren't handled when trying to find the Data Source TexlNode from a function call. This breaks legacy analysis ECS in some scenarios.
=> Add missing case to TryGetDataSourceNode

src/libraries/Microsoft.PowerFx.Core/Public/Values/NumberValue.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryMath.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TrigTableFunctions_ConsistentOneColumnTableResult.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterExpressionTestCases/Disabled.txt
We had a test for trig tabular functions that was never enabled, because those functions were not implemented. Added the implementation for the tabular functions, fixed the test and enabled it.
=> Add trig tabular function implementations, enable tests

src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ExpT_ConsistentOneColumnTableResultDisabled.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Exp_ConsistentOneColumnTableResult.txt
The value of an expression such as `Ln(Exp(3))` or `Exp(Ln(3))` is 3, but due to rounding / floating point errors in different platforms it can be a little different. Wrapping the expression with the Round function to make sure that we get the same result everywhere.
=> Wrap Log/Exp tabular tests with Round to avoid rounding errors

src/libraries/Microsoft.PowerFx.Core/Functions/ArgPreprocessor.cs, src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/LeftRight.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Rgba.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryColor.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/RGBA.txt
The first three arguments to the RGBA function are integer values, and as such are truncated when used - `RGBA(123.45, 0, 0, 1)` is the same as `RGBA(123, 0, 0, 1)`. However, the validation is done prior to the truncation, which makes some inputs to be considered invalid that should be valid, such as `RGBA(255.1, 0, 0, 1)`.
=> Proper validation of RGBA arguments

src/libraries/Microsoft.PowerFx.Core/Public/Config/VersionHash.cs, src/tests/Microsoft.PowerFx.Core.Tests/ThreadingTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/VersionHashTests.cs
VersionHashTests used UtcNow which was non-deterministic and were randomly failing in CI. 
Add test to help verify uniqueness.
=> Fix version hash -shouldn't use timer.

src/libraries/Microsoft.PowerFx.Core/Functions/ArgPreprocessor.cs, src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/libraries/Microsoft.PowerFx.Core/IR/Nodes/UnaryOpKind.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Hex2Dec.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Split.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/StringOneArgFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUnary.cs
-Follow up to #1006 #1059 
-This introduces a new UNaryOpKind `BlankToEmptyString`, since no current function satisfies the BlankToEmptyString behavior.
-Note: Other backends must implement this new UNaryOpKind `BlankToEmptyString` for these functions to work.
NOTE: In this PR 3 function are left out purposefully. 
`Concatenate()` due to its frequency of use with `&` operator and because of that it may generate very long IR
`StartsWith()` and `EndsWith()` due to complexity with support of these function in delegation. 
Corrsponding Dataverse PR: https://github.com/microsoft/Power-Fx-Dataverse/pull/81
=> Moves BlankToEmptyString arg preprocessing to IR Phase.

src/libraries/Microsoft.PowerFx.Core/Binding/BinderUtils.cs, src/libraries/Microsoft.PowerFx.Core/IR/BinaryOpMatrix.cs, src/libraries/Microsoft.PowerFx.Core/IR/Nodes/BinaryOpKind.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryOperators.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/BasicCoercion.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson_Arithmetic.txt, src/tests/Microsoft.PowerFx.Core.Tests/Microsoft.PowerFx.Core.Tests.csproj, src/tests/Microsoft.PowerFx.Interpreter.Tests/Scenarios/CustomRecordTypeWithUndefinedFields.cs
Enables coercions from UntypedObject to other types in binary and unary operators. Untyped/Blank combinations often coerce to Number. Includes tests for Blank() for many operators.
=> Initial work on UntypedObject coercions for binary operators

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/CollectFunction.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/Collect.txt
To support https://github.com/microsoft/Power-Fx-Dataverse/issues/79
Date to number is a special kind of coercion that is inconsistent with other conversions.
These changes are meant to prevent this coercion from within a record.
=> Removing coercion date to number within Collect.

src/libraries/Microsoft.PowerFx.Interpreter/Environment/SymbolExtensions.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/libraries/Microsoft.PowerFx.Interpreter/Marshal/TypeCoercionProvider.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/TypeCoercionTest.cs
Fix issue https://github.com/microsoft/Power-Fx/issues/1126
and issue https://github.com/microsoft/Power-Fx/issues/1127
and issue https://github.com/microsoft/Power-Fx/issues/1137
=> Add support for RuntimeConfig in TryCoerceTo and add CanCoerceToStringValue and allow Text(Guid)

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Extensions.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/CollectFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/PatchFunction.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Collect.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/FileExpressionEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/ClearCollect.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/Collect.txt
Supports DV https://github.com/microsoft/Power-Fx-Dataverse/issues/84
Previously Collect, and Patch would handle non-existing fields differently. Collect used to allow, while Patch didn't.
When executing Collect, PA will determine whether the current data source is a DV instance. Then will decide how to behave based on that.
Power Fx will not handle different data source types differently.
=> Collect no longer accepts not existing fields

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson_Coercions.txt
In general, this changes Binder to allow normal type checking to occur in the case where:
1. Lambdas exist on one of the overrides to a function
2. The first argument is UntypedObject
3. There is only a single overload, i.e. no scalar overloads at all
The 3rd item in this list was not true before this change. We would give record scope errors in the binder. Normal type checking will fail for all functions where this error would have been seen before, with a single exception: the IfError function, where type checking will succeed.
This is not a breaking change.
=> Allow IfError to accept UntypedObjects in the first argument

src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TrigTableFunctions_ConsistentOneColumnTableResult.txt
The interpreter handling aggregate coercion for blank / null values is not working. This fixes it.
=> Handle blank / error values in aggregate coercion scenarios

src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseHelper.cs, src/libraries/Microsoft.PowerFx.Core/Types/Enums/EnumStoreBuilder.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs
As none of our builtin enum names are escaped, we have a gap around suggestions, where if a custom enum is created, it isn't properly escaped in the intellisense suggestions. This only applies to canvas, for PCF custom enums. Every other use case is on Option Sets.
=> Ensure custom enum symbol names in intellisense suggestions are escaped

src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs
Following the change to remove support for unqualified enums, we need to update the parameter description for the Sort[ByColumns] argument that controls the sort order, and the Date[Add|Diff] ones that determines the units to use in the addition / difference.
=> Update resource to remove unqualified enum references

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/FormulaType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/ITypeVisitor.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/Void.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/VoidType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/FormulaValueNew.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/VoidValue.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/If.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/With.cs, src/libraries/Microsoft.PowerFx.Core/Types/DKind.cs, src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/libraries/Microsoft.PowerFx.Core/Types/DTypeSpecParser.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/JsonRpc/ObsoleteTypeSerializer/FormulaTypeSchema.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/JsonRpc/ObsoleteTypeSerializer/FormulaTypeToSchemaConverter.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/First.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ForAll.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/If.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/If_AllowsSideEffects.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Last.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/StronglyTypedEnums.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/With.txt, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/SymbolTableTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/TypeSystemTests/DTypeTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ValueTests.cs
- Fixes https://github.com/microsoft/Power-Fx/issues/1092 and #843 
- Corresponding PA PR: https://msazure.visualstudio.com/OneAgile/_git/PowerApps-Client/pullrequest/7705536
- Introduces new `void` DType and corresponding `VoidValue` which currently is only produced by the `If` function when argument type mismatches (useful for behavior function) and removes IsArgTypeInconsequential hackery.
Notes:
- `Void` type is denoted by `-`. 
and it has a corresponding `VoidValue` even though it may sound counterintuitive. This keeps things straightforward.
- `Void` type can't be consumed. Ie `void + 1` is invalid.
- `Void` type isn't allowed in the aggregate type. Ie `[void]` or `{field: void}` is invalid.
- `Void` type can't be accepted by any type or coerced to any type.
- Currently, this PR is …
=> Introduces a new Void type so that we can remove IsArgTypeInconsequential

src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs
We recently had a bug added to the Error function (in #1206), and it was fixed in the next commit (#1224). This adds some additional tests to prevent the error from happening in the first place.
=> Add TexlTest for Error function

src/libraries/Microsoft.PowerFx.Core/Public/Config/Features.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/IsEmpty.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/IsEmpty.txt, src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs
IsEmpty is supposed to check if a table is empty or not, but currently it accepts different types of arguments. Since it doesn't make sense to use it for other types, we will restrict it. But to avoid breaking Power Apps, we will make the change behind a new feature.
Also adding the implementation to the C# interpreter.
=> Restrict IsEmpty arguments to tables only

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Extensions.cs
To support https://github.com/microsoft/Power-Fx-Dataverse/issues/102.
Problem: Power Fx Dataverse would crash when we tried to Collect/Patch a record with a non-existing column. A new validation was placed to prevent this from happening. This validation checked if a column with the same name and type what present. If false, the mutation function returned an error. This new validation could not compare a LookUp field (Dtype.DataEntity) and a record type.
Solution: Expand the DataEntity type into a Record type and then compare the types.
=> Support DataEntity type within mutation functions

src/libraries/Microsoft.PowerFx.Core/IR/Nodes/AggregateCoercionNode.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ArgCoercion.txt
We only add fields to AggregateCoercionNode that require a coercion. But eval only evals the fields listed in AggregateCoercionNode. So a field that doesn't require coercion gets skipped in eval!
This fixes it via eval - but should probalby be fixed at IR level. Since eval processes every time, whereas we know this statically.
=> AggregateCoercionNode  bug.

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Switch.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/If_AllowsSideEffects.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/If_AllowsSideEffects_NumberIsFloat.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/switch.txt
-Fixes #1201 
-Currently in Switch()'s check type we allow usage of the result of the switch statement even when arg is mismatched, we shouldn't be doing that.
e.g. `Set(x, Switch(20, 20, 1, 21, {x:1}))` should not be allowed.
-Return void when the switch() has the arg type mismatch.
=> adds void type support to Switch()

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryTable.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/FilterFunctions.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Lookup.txt
To support https://github.com/microsoft/Power-Fx-Dataverse/issues/119
When calling `LookUp` against a table from a user with missing privileges, DV returns a DValue<ErrorValue>, which was not previously handled by the filter. The final response from the engine was a BlankValue object.
=> FaultException for missing privileges isn't displayed to user

src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TableNodes.txt
Currently the `[...]` notation doesn't work properly (it is incorrectly wrapping record nodes in `{Value:X}`) if there are expressions in the nodes. This change fixes it by updating the IR translator to look at the binding type instead of the parser node.
=> Fix table nodes IR translation

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/FirstLastN.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/FirstLastN_RequiredSecondArgument.txt
Check for validity of calls to the FirstN/LastN function with the new feature flag that requires two arguments was broken. This fixes it.
=> Fix check of FirstN/LastN functions with new feature flag

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Concat.txt
This doesn't work properly today. Fixes #1326
=> Properly pass error and blank rows to Concat expression

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/IfError.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/IfError.txt
-Fixes #1173 
`IfError()` has buggy implementation of CheckType(),
e.g. 
below expression should be an error (now error in the PR):
`IfError(1, {x:1}, {x:1}, {y:1}, 1)` Since it can potentially return a record or a number type
In both cases, it should have been consistent, since the possible result type can be either Number or Time type for both the expression and should have been super typed to the same thing...
`IfError(1, 1, Time(12,0,0)) => Time Type` 
`IfError(1, Time(12,0,0)) => Number Type`
Now Above both are Number Type.
-Also add void type support for mismatched args.
=> adds void type to IfError()

src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/EditorContextScopeTests.cs
Supporting multiple types when Check function is ran with EditorContextScope.
Fix #1332
=> Supporting multiple types

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/IfError.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/IfError.txt
Reverts microsoft/Power-Fx#1230
Reverting because it was a breaking change - not ready to take in Power Apps yet. 
-Previously allowed now error:
expressions such as IfError(1, {x:1}, {x:1}, {y:1}, 1) Since it can potentially return a record or a number type.
=> Revert "adds void type to IfError()"

src/libraries/Microsoft.PowerFx.Core/Binding/BinderUtils.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Eq_DifferentTypes.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Eq_DifferentTypes_PowerFxV1FeatureEnabled.txt
With the new PowerFxV1 feature set, we are stricter with comparing values of different types. Something like `1 = "1"` has always returned false, which is probably not what the maker intended, so we are making them errors. Comparisons between dates and times, however, should be allowed, since for Excel compatibility they are equivalent to numbers. This change relaxes the restriction and makes the equality / inequality comparison between date/time values valid.
=> Allow equality comparison between date/time values

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Error.txt
With the StronglyTypedBuiltinEnums on, the Error function wasn't working properly on its overload that takes a table. This change fixes it.
=> Fix Error function to work with strongly typed enums

src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/CollectFunction.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationFunctionsTests.cs
To mitigate issue #1360.
New error message:
> Incompatible type. The item you are trying to put into a table has a type that is not compatible with the table.
`Union` fails here:
https://github.com/microsoft/Power-Fx/blob/5b890ffe6bd07eff9a7671d01ca100316fcc3c2a/src/libraries/Microsoft.PowerFx.Core/Types/DType.cs#L2813
Then PFx tries to show which column has failed. The problem is that Union fails for a particular reason, but we use a different method to find the problematic column. PFx can accept Polymorphic/Record types. For some reason that I couldn't identify PA Client can't. This will result in `Owner:{e}` and PFx handling this scenario at
https://github.com/microsoft/Power-Fx/blob/5b890ffe6bd07eff9a7671d01ca100316fcc3c2a/src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs# …
=> Collection to display better error message

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/MathFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Statistical.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/StatisticalTableFunction.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Mid.txt
Several functions can now return either DType.Decimal or DType.Number.  Reflecting this, these functions advertise their return type as DType.Unknown in the function info constructor.  This was causing problems for PA Client, and does not appear to actually impact the interpreter, so we are going to change it back to DType.Number which is all PA Client supports at the moment.  It isn't clear how this information would have been used anyway, as CheckTypes for each function ultimately determines the return type.
=> Revert DType.Unknown for native decimal function return type

src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUnary.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ArgCoercion_V1Compat.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ArgCoercion_V1CompatDisabled.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/GUID.txt
Issue https://github.com/microsoft/Power-Fx/issues/1090.
`GUID()` is now supported but `guid` to `string` coercion is only possible when `PowerFxV1` feature is active.
=> GUID() support

src/libraries/Microsoft.PowerFx.Core/App/Controls/IExternalRule.cs, src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs
HasErrors property name is misleading as it also returns true if there are only warnings on the rule. Hence renaming it to increase clarity. Recently we have seen a bug which was caused due to this misunderstanding.
=> Renamed HasErrors to HasErrorsOrWarnings.

src/libraries/Microsoft.PowerFx.Core/Functions/ArgPreprocessor.cs, src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/libraries/Microsoft.PowerFx.Core/IR/Nodes/UnaryOpKind.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Atan2.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Char.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/DateTime.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Dec2Hex.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Hex2Dec.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/LeftRight.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/MathFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Rgba.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Sequence.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Split.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/StringOneArgFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Text.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/DecimalUntypedObject.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/FloatUntypedObject.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUnary.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ParseJson.txt
These arguments are currently not used in any way by the C# interpreter. When the changes are incorporated into PAClient, new tests will need to be added.
=> Add Format/Language arguments to Text_UO

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Table.cs
Follow-up to #1489 - using the 'only coerce to left type' on the Table function either if StronglyTypedEnums is enabled (the root cause of the bug it fixed), or if we are using the Power Fx V1 compat rules (since it moved to a "first-type" rule)
=> Use 'prefer left type' if PFx v1 is enabled as well

src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/Tokenization.cs
The support for semantic tokenization was added in PR https://github.com/microsoft/Power-Fx/pull/1420. I migrated the logic behind tokenization in old formula bar from Canvas App backend to PowerFx. In doing so, i forgot to bring over a very tiny part but important for old formula bar of the logic that computes whether first name tokens can be hidden or not.
=> Adding the very small part of logic behind hiding tokens I forgot to migrate in PR #1420

src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs, src/tests/Microsoft.PowerFx.Core.Tests/FormatterTests.cs
Earlier this week, Customer reached out to us about a bug when trying to format the expression like "Set(Children; true)" in the formula bar. "Children" is not a reserved keyword and unless the disabled reserved keyword flag is not set when invoking Lexer, "Children" gets identified as an ErrorToken. This causes errors in the AST and we don't format when there are errors and just return the same expression.
To solve this, we need to pass in a Flags.DisabledReservedKeyword flag to the parser and ultimately lexer when invoking them before the pretty printing. There was no ability to pass in custom flags so I extended the "Format" function (which is an entry point for pretty printing) with an optional argument to allow passing custom flags. These changes would be later consumed in Canvas …
=> Fxing expression formatting/pretty print bug with reserved keywords

src/libraries/Microsoft.PowerFx.Core/Annotations/NotThreadSafe.cs, src/libraries/Microsoft.PowerFx.Core/Entities/External/IExternalEntityScope.cs, src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/DeferredSymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTableOverRecordType.cs, src/libraries/Microsoft.PowerFx.Core/Public/DisplayNames/DisplayNameProvider.cs, src/libraries/Microsoft.PowerFx.Core/Types/LazyTypeProvider.cs, src/libraries/Microsoft.PowerFx.Core/Types/TypeSymbolTable/DefinedTypeSymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Types/TypedName.cs, src/tests/Microsoft.PowerFx.Core.Tests/AnalyzeThreadSafety.cs, src/tests/Microsoft.PowerFx.Core.Tests/ImmutabilityTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ThreadingTests.cs
Threading tests to help enforce #1519 .
Includes a bunch of little fixes and reducing failure list.
Tests don't aggressively assert yes, too many failures. But we can at least run and drive to 0.
=> Threading tests 

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/tests/Microsoft.PowerFx.Core.Tests/BinderTests.cs
A previous change to tag nodes for mutability didn't take account of connected data source nodes. This updates it.
=> Make data source FirstNameNodes also mutable

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/ForAll.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ForAll.txt, src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs
If a ForAll expression is used within a context where its result is not needed, then it should be able to use void expressions, like in the example below. This change allows it, making the entire result of the ForAll expression a void result.
ForAll(
Sequence(4),
If(
Mod(Value, 2) = 1,
Patch( table, Index(table, Value), { IsOdd: true } ),  // this returns a record, incompatible with tables
Collect( table, { Value: Value, IsOdd: false }, { Value: Value + 1, IsOdd: true }   // this returns a table
)
)
=> Allow Void expressions to be used within ForAll

src/libraries/Microsoft.PowerFx.Core/App/Controls/IExternalControl.cs, src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Binding/INameResolver.cs, src/libraries/Microsoft.PowerFx.Core/Functions/UserDefinedFunction.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/ReadOnlySymbolTable.cs
This change is a breaking-internals change, but it allows for safer testing of ongoing analysis improvements. It should have no impact on non-canvas hosts, other than up taking a new member, if they directly implement INameResolver, and IIRC, they should be using ReadOnlySymbolTable instead of directly using INameResolver.
=> Move expansion of Canvas-Specific control type into INameResolver from IExternalControl

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text_Format.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestHelpers/BaseRunner.cs
Fixing TXT file for tests that are impacting French locale
Fixed an issue with Windows 10 / 11 being inconsistent for the thousand separator
=> Update Text_Format.txt file

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/DeferredSymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/NameSymbol.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolProperties.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTableOverRecordType.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/SetFunction.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/SymbolValueTests.cs
Before, Set() and Collect()  were both tied ot a single IsMutable concept. 
Need to decouple to allow scenarios like:
Set(Accounts, ....)  // Fail
Collect(Accounts, ... ) // Succeed
Set(ThisRecord.field1, ...) // succeed
Collect([1,2,3,4], ..) // fail
Set([1,2,3,4], ..) // fail
Set(namedFormula1, ...); // fail 
Set(x, [1,2,3,4], ..) // Succeed
Collect(x, {5}) // Succeed
=> Allow better mutation controls. 

src/libraries/Microsoft.PowerFx.Core/Public/Config/IUserInfo.cs, src/libraries/Microsoft.PowerFx.Interpreter/CustomFunction/CustomTexlFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/SymbolTableExtensions.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
Fix #1592 
We should be able to revert this change after DV moves off the old surface.
=> Backwards compat shims for Dataverse

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/IsMatch.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/IsMatch.txt
This was the previous behavior - we should revert to what we had before. Since IsMatch doesn't need to know the value of the regular expressions at compile-time (unlike Match[All], which need it to determine the output schema), the constant check can be less strict.
=> Allow constant nodes (not only constant string expressions) to be used in IsMatch

src/Directory.Build.props, src/libraries/Microsoft.PowerFx.Connectors/Microsoft.PowerFx.Connectors.csproj, src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Microsoft.PowerFx.Core.csproj, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/If.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/MathFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Microsoft.PowerFx.Interpreter.csproj, src/libraries/Microsoft.PowerFx.Json/Microsoft.PowerFx.Json.csproj, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Microsoft.PowerFx.LanguageServerProtocol.csproj
System.Text.Json: 5.0.2 (deprecated) -> 6.0.8
System.Collections.Immutable: 5.0.0 (deprecated) -> 6.0.0
Also updated this one which was outdated/in preview
Microsoft.CodeAnalysis.NetAnalyzers: 7.0.1-preview1.23061.1 -> 7.0.3
=> Update nuget versions for deprecated packages

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/strings/PowerFxResources.en-US.resx
In order to support function to function reference, we need to allow component control to be returned as a lookupInfo. This, however, also allows reference to all properties of the component. Since we only want function to function reference, we need to restrict all DottedNameNode in the binder.
=> Component Function property - Block access to all DottedNameNode

src/libraries/Microsoft.PowerFx.Connectors/ArgumentMapper.cs, src/libraries/Microsoft.PowerFx.Connectors/ConnectorType.cs, src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs, src/libraries/Microsoft.PowerFx.Connectors/PowerFxConnectorException.cs, src/libraries/Microsoft.PowerFx.Connectors/Shared/ServiceFunction.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/Helpers/Helpers.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/InternalTesting.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/PublicSurfaceTests.cs
Out of 2515 swagger files: from 678 unsupported files to only 124 where
14 parse errors (duplicate keys or malformed format)
73 unsupported content types (octect-stream, pdf, text, csv, xml, zip, mp3, jpeg...)
14 unsupported parameter format (file)
2 deviation from swagger specification: enum integer (enums are in description field)
1 unsupport OpenApi version
6 duplicated parameters (2 params with same name in different locations)
2 malformatted swagger files
12 OpenApi nuget bug (version string taken for a date)
+
Better handling of unsupported swagger files (detection, error messages...)
Better support for numberIsFloat flag
Refactoring of dynamic intellisense (consolidation of code)
Better support of enums
Better support for option sets
Better support of string and integer formats …
=> Connector swagger parser improvements

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Entities/External/IExternalNamedFormula.cs
Named formulas would always be marked false because of the existing logic for FirstNameNodes always being false unless enum.
=> Allow named formulas to be added to constant cache

src/libraries/Microsoft.PowerFx.Core/App/IExternalEnabledFeatures.cs, src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs
To prepare for future work that would fix dataflow issue with component funciton property. We need to use an ECS to control rollout and rollback of this fix.
=> Add new ECS flag to negate recent changes to function property

src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Filter.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/FilterLookUp_TwoArg_V1Compat.txt
Addressing https://github.com/microsoft/Power-Fx/issues/1514.  
Advantages:
- This brings Filter and LookUp into alignment.  
- Using And to combine predicates is easier to understand and read than knowing that extra arguments are And'd together.
- Limiting to two arguments allows us to add a reduction argument like LookUp has.  Which enables us to push shaping of the result up the stack more easily when making a network call.
For C# clients, the Filter function was already effectively limited to two args because the interpreter couldn't handle it (a bug), so no change there.  
For Canvas, this is a breaking Power Fx 1.0 change (under Power FxV1CompatibiltyRules flag) that we'll need to manage later, but only ~13% of filter calls use the three or more argument form.  A back compat …
=> Filter function limited to two args

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Binding/DelegationWarningProvider.cs, src/libraries/Microsoft.PowerFx.Core/Functions/Delegation/DelegationStrategies/DelegationValidationStrategy.cs, src/libraries/Microsoft.PowerFx.Core/Functions/Delegation/DelegationStrategies/OpDelegationStrategy.cs
In the upcoming months there are plans to add multiple warnings which pertain exclusively to Canvas into Power Fx.  While we decide on a strategy for allowing Canvas to extend the warning capabilities provided by the Binder, I am proposing the creation of a new data structure that extends the allows consumers to add custom delegation hints by providing an abstract class which implements virtual methods and invokes them during delegation warning visitation on an instance provided baller the caller on TexlBinding.Run.
Currently, the data structure implements two virtuals, one to visit callndoes and one to visit binary op nodes.  This decision was a consequence of the needs of [this PR](https://github.com/microsoft/Power-Fx/pull/1627) is reaching an imminent deadline.  The call node visitor …
=> Implement Abstract DelegationHintProvider

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Functions/FunctionScopeInfo.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Distinct.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Distinct_V1Compat.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Distinct_V1CompatDisabled.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/FilterFunctions.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/FilterFunctions_V1Compat.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/FilterFunctions_V1CompatDisabled.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Lookup.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Lookup_V1Compat.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Lookup_V1CompatDisabled.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/UntypedBlankAsTable.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/UntypedBlankAsTable_V1Compat.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/UntypedBlankAsTable_V1CompatDisabled.txt
We updated all other functions to do that, but the statistical functions still behavior still favor the tabular overload: in `Min(Blank(), 1)` the blank value is interpreted as a table (and the operation returns `Blank()`), while there is an overload that takes numbers instead.
=> Update untyped blanks to be treated as scalar when it's possible to be a table or scalar

src/libraries/Microsoft.PowerFx.Interpreter/Environment/PowerFxConfigExtensions.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/PowerFxEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RegExTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/TexlTests.cs
=> Fix #1663 - warn that EnableRegExFunctions is still preview.

src/libraries/Microsoft.PowerFx.Core/Binding/BinderUtils.cs, src/libraries/Microsoft.PowerFx.Core/IR/BinaryOpMatrix.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/inScalar.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/inScalar_V1Compat.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/inScalar_V1CompatDisabled.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/inTable.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/inTable_V1Compat.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/inTable_V1CompatDisabled.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterExpressionTestCases/InScalarOverride.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterExpressionTestCases/InTableOverride.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterExpressionTestCases/inScalar_V1CompatDisabled_Overrides.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterExpressionTestCases/inTable_V1CompatDisabled_Overrides.txt
Untyped blanks, when used in contexts where they can be interpreted as either a scalar or a complex type (record / table), should be interpreted as scalars. This wasn't working for the `in` operator, and this fixes it. Since this is technically a breaking change (although I can't see why someone would use that), the update is made under the PowerFxV1CompatibilityRules feature.
=> Ensure that untyped blank is interpreted as a scalar for the 'in' operator

src/libraries/Microsoft.PowerFx.Core/Syntax/NodeKind.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Nodes/TypeLiteralNode.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Visitors/TexlFunctionalVisitor.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Visitors/TexlVisitor.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs
This adds the TypeLiteralNode so we can use it for future functions `Type` and later possibly `IsType` and `AsType`
=> Added TypeLiteralNode

src/libraries/Microsoft.PowerFx.Core/Binding/BinderUtils.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/inScalar_V1Compat.txt
We already fixed it in most places, but found one more. This fixes #1713
=> Ensure that untyped blank is interpreted as scalar

src/libraries/Microsoft.PowerFx.Connectors/OpenApiParser.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/LivePublicSwaggerTests.cs
Avoid throwing when a connector isn't supported for some reason - use IsSupported/NotSupportedReason instead
Avoid function names with curly brackets or dots (just remove those)
Properly manage httpClient when it has an absolute path (not root/empty)
Fix a NullRef when only HTTP server is provided
=> Several connector updates

src/libraries/Microsoft.PowerFx.Core/App/IExternalEnabledFeatures.cs, src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Binding/BinderUtils.cs, src/libraries/Microsoft.PowerFx.Core/Functions/CheckTypesContext.cs, src/libraries/Microsoft.PowerFx.Core/Functions/Delegation/DelegationStrategies/InOpDelegationStrategy.cs, src/libraries/Microsoft.PowerFx.Core/Functions/Delegation/DelegationStrategies/OpDelegationStrategy.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/AsType.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/CountIf.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/CountRows.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Filter.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Lookup.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Sort.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/SortByColumns.cs, src/tests/Microsoft.PowerFx.Core.Tests/Helpers/TestUtils.cs
Enhanced delegation has been out and enabled by default for a long time now. Considering it's enabled in around 87% of Power Apps and there is confidence in the feature, we're getting rid of it as a setting and just making it the default behavior.
=> Remove enhanced delegation external feature

src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseData/IntellisenseData.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterSuggestTests.cs
-While Suggesting Collect(| do not suggest deferred type, since we only want to suggest Table Types and even though Deferred Type is coercable to Table Types, it has no real meaning in this case.
-This also helps with not suggesting row scope symbols since they are also deferred types.
=> Do not suggest deferred types in Collect(| Intellisense

src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseData/IntellisenseData.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseHelper.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterSuggestTests.cs
-Adds contextual suggestions for Binary Op node.
Today 
`Num = |` doesn't suggest global number types.
This PR will suggest global types depending on left hand side of type for binary op nodes.
=> Add Contextual Suggestion for Binary Op

src/libraries/Microsoft.PowerFx.LanguageServerProtocol/JsonRpc/ObsoleteTypeSerializer/FormulaTypeToSchemaConverter.cs
Fix #1789 
This only happens when front end &getExpressionType=true
We don't even need type information for dataverse types. Just short circuit and return empty.
=> fix stackoverflow from 1789

src/libraries/Microsoft.PowerFx.Interpreter/Environment/SymbolExtensions.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/IClockService.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryDate.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/TimeTests.cs
Add an IClockService, similar to existing IRandomService. 
Call clock service instead of DateTime.UtcNow directly. This abstracts our direct dependency on the machine. It also allows the host to override, which can be very useful for deterministic testing Today(), IsToday(), Now() - especially around UTC , datetime boundaries.
=> add clock service

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Refresh.cs
=> TexlFunction clean-up - removing DisabledFor[Commanding|DataComponent] virtuals

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs
Those virtuals are only used in Power Apps, not in Power Fx.
=> Remove component-related virtuals from TexlFunction

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs
This virtual property is only used in Power Apps - no need to have it in Power Fx.
=> Removed unused RequiresBindingContext virtual from TexlFunction

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Error.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseData/IntellisenseData.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseHelper.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/SuggestionHandlers/FunctionRecordNameSuggestionHandler.cs, src/libraries/Microsoft.PowerFx.Interpreter/CustomFunction/CustomTexlFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/CollectFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/PatchFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/RemoveFunction.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/CustomFunctions.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterSuggestTests.cs
Fixes #1787 
-If the custom function provided ParamType, now intellisense will suggest the corresponding columns. _including nested columns_, and columns inside a table type.
-Adds virtual `TryGetTypeForArgSuggestionAt(int argIndex, out DType type) ` to get Type intellisense will be used to match suggestions.
-Fixes Patch and Remove for suggestions.
NOTE: PA would need to override the `TryGetTypeForArgSuggestionAt()` for mutation functions definition in same way it's done here.
=> Enable field suggestion for custom functions.

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseHelper.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/SuggestionHandlers/DottedNameNodeSuggestionHandler.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/IntellisenseTests.cs
-If a path is deprecated or internal for Intellisense, do not suggest it.
-Dotted Name already was blocking it, FirstNameNode also blocks it now.
=> Do not suggest Deprecated Connector functions

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/Features.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Coalesce.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/If.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Logical.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Switch.cs, src/libraries/Microsoft.PowerFx.Interpreter/CustomFunction/CustomTexlFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/CollectFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/PatchFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/RemoveFunction.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestHelpers/TxtFileDataAttribute.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/FileExpressionEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/AndOr.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/Assert.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/ClearCollect.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/Coalesce.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/Coalesce_CoalesceShortCircuit.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/Coalesce_CoalesceShortCircuitDisabled.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/Coalesce_V1CompatDisabled.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/ForAllMutate.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/If.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/IfError.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/Patch.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/MutationScripts/Switch.txt
Fixes https://github.com/microsoft/Power-Fx/issues/1831 and https://github.com/microsoft/Power-Fx/issues/1066.  Added additional tests for short circuiting.  We also need to be careful not to break Canvas semantics before Power Fx 1.0 is adopted there.
=> Update Coalesce function semantics to short circuit

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Coalesce.cs
Since we made the Coalesce function lazy, we need to mark it as asynchronous so that it may need to block while evaluating some of its arguments, since they can be asynchronous themselves.
=> Mark the Coalesce function as asynchronous to account for lazy evaluation

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Coalesce.cs
Reverts microsoft/Power-Fx#1839
Power Apps doesn't need this change.
=> Revert "Mark the Coalesce function as asynchronous to account for lazy evaluation"

src/libraries/Microsoft.PowerFx.Connectors/OpenApiParser.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorTests.cs
When 2 functions share the same Path, we need to separate their deprecation status
One could be deprecated and not the other
=> Fix connection deprecated function logic 

src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/libraries/Microsoft.PowerFx.Connectors/Internal/ConnectorExtensions.cs, src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorType.cs, src/libraries/Microsoft.PowerFx.Connectors/Texl/ConnectorTexlFunction.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/ConnectorWizardTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/DynamicTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/OpenApiParserTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/Swagger/Teams.json
- OpenApiResponses can be 2xx and we were only looking at 200 Response. We'll now look at all 2xx responses and take lowest
- Update GetParameterSuggestionsAsync to use ConnectorParameter instead of a string
- add GetConnectorTypeAsync (for ConnectorParameter or ConnectorType) to allow discovery chaining of types
- renamed GetConnectorReturnSchemaAsync to GetConnectorReturnTypeAsync
-
=> Connector fix and API changes

src/libraries/Microsoft.PowerFx.Core/Errors/IRuleError.cs, src/libraries/Microsoft.PowerFx.Core/Errors/TexlError.cs, src/libraries/Microsoft.PowerFx.Core/Parser/NamedFormula.cs, src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs, src/tests/Microsoft.PowerFx.Core.Tests/ParseTests.cs
This PR adds a base index in NF formula parse results for NF identifier. This is needed so that when Formulas property rule changes, we don't need to rebind each and every named formula every time. We can only rebind the rules which are changed. Currently we need to do that as span for each named formula rule is not relative to named formula identifier token. With this base index information, we can then just use new base Index and previous base index to calculate the offset for each NF edit, which we can then use for the error reporting.
=> NamedFormula edit experience improvement

src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/libraries/Microsoft.PowerFx.Connectors/Internal/ConnectorExtensions.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorEnhancedSuggestions.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorSchema.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorType.cs, src/libraries/Microsoft.PowerFx.Connectors/Texl/ConnectorTexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/ConnectorSuggestions.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/DynamicTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/OpenApiParserTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs
New GetConnectorSuggestionsAsync API with ConnectorType parameter
Renamed GetConnectorTypeAsync w/ ConnectorParameter to GetConnectorParameterTypeAsync
Removed internal GetConnectorSuggestionsAsync with ConnectorParameter (using ConnectorType now)
Cleaned ConnectorExtensions
=> New GetConnectorSuggestionsAsync API with ConnectorType parameter

src/Directory.Build.props, src/buildAndRefresh.bat, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/LanguageServer/LanguageServer.cs, src/refreshLocalNugetCache.ps1, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/LanguageServerTests.cs
-sortText does lexicographical sort and hence we need to prepend string with 0s
otherwise,
e.g. if you had more than 10 suggestions... it would have sorted to
0
1
10
11
2
3
4
5
6
7
8
9
=> Fixes sorting issue.

src/libraries/Microsoft.PowerFx.Repl/Services/StandardFormatter.cs
Merges the Dataverse primary name and primary key fields into the standard table formatter, making it consistent with non-Dataverse table and record output.
Features include:
- Limits table and records to primary name and key by default.
- Shows "..." column on the right to indicate that there are more columns.
- Limits table output to 10 records by default.
- Shows "(showing first 10 records)" below the table if it is longer than 10 records.
- Shows "..." in record values after the primary name and key.
```
>> Contacts
contactid                                      fullname                     ...
============================================== ============================ =====
GUID("e3fda297-f859-ee11-be6f-002248046ef8")   Yvonne McKay (sample) …
```
=> Updates to REPL StandardFormatter to integrate Dataverse tables

src/libraries/Microsoft.PowerFx.Core/Syntax/Nodes/RecordNode.cs, src/tests/Microsoft.PowerFx.Core.Tests/ParseTests.cs
RecordNode doesn't currently report the correct complete span when there are parse errors in expression. This change fixes that.
=> Fixed RecordNode GetCompleteSpan logic

src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs
They were added as 'feature gated' for timing constraints, but it should be part of the core library.
=> Move EDate and EOMonth functions to the core library

src/libraries/Microsoft.PowerFx.Repl/Repl.cs, src/libraries/Microsoft.PowerFx.Repl/Services/StandardFormatter.cs, src/tools/Repl/Program.cs
The current REPL library doesn't provide whitespace between the expression and the output.  With the REPL here, we have the ability to color the prompt which helps.  to visually group the expression with the output.  But with the PAC CLI, we don't have this ability and it all bleeds together.  This is particularly true for Power Fx where an expression could cause recalc of other values which are rightly shown in the output.
In short, we want to change this:
Into the slightly longer, but much easier to parse and read:
We could have fixed this just in the PAC CLI, however I prefer this whitespace here too and consistency is good.  This also ensures that table formatting works correctly with added newlines.  It also mirrors the tests cases.
=> Add newline for REPL output

src/libraries/Microsoft.PowerFx.Core/App/Controls/IExternalControlProperty.cs, src/libraries/Microsoft.PowerFx.Core/App/Controls/IExternalControlTemplate.cs, src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs
Currently during binding, output properties that infer their type from the primary input property have their type retrieved from the control's template. This PR changes the logic for this determination and handles it similar to pass through input property type calculation
=> Refactor type determination for output properties that infer type from primary input property

src/libraries/Microsoft.PowerFx.LanguageServerProtocol/LanguageServer/LanguageServer.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/LanguageServerTests.cs
We previously anticipated wrongly that we do not need to send back empty control tokens. We actually need to do send back empty control tokens and that's the only way we know we went from having atleast one control token in a formula to zero control tokens in the formula. This is a small change that we need to do
=> Send back empty control tokens

src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text_DefaultNumber_Float.txt
We had defined a certain range where the default number-to-text conversion should go from decimal numbers to exponential notation, while leaving some to be implementation-dependent (until 1e10 should use decimal notation; starting from 1e20 should use exponential). In JavaScript, the exponential notation is used starting from 1e**21**, so we can relax the requirement and start requiring exponential notation from that as well.
=> Update required range for exponential notation

src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
Was just playing around with the recalc engine, and noticed that i got an internal null-reference error when trying to fetch a non-existing value using the existing `GetValue` method (see image)
This pr just introduces a new method to the RecalcEngine that returns a boolean if it fails to find the value.
=> [Suggestion] Add public TryGetValue method to recalcengine

src/libraries/Microsoft.PowerFx.Core/Public/Config/Features.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/AsType.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs
-Legacy analysis requires a hack that changes the return type to include ExpandInfo, this causes the runtime type mismatch in the interpreter. 
-Hence putting it behind a new flag
=> Fixes AsType() for interpreter

src/libraries/Microsoft.PowerFx.Core/Lexer/TexlLexer.cs, src/tests/Microsoft.PowerFx.Core.Tests/FormatterTests.cs
This pr fixes #1645. The Remove Whitespace functionality used to blindly remove training whitespaces around the string literals inside interpolated strings. This is erroneous behavior as those whitespaces are part of string literals and should not be deleted. For example [dollar symbol]"1 + 2 = {1 + 2}" should stay as [dollar symbol]"1 + 2 = {1 + 2}" but instead becomes [dollar symbol]"1 + 2 ={1 + 2}"
Before:
After:
=> Do not remove trailing whitespaces around the string literals in interpolated strings when "Removing Whitespaces/Unformatting"

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/IsBlank.cs
This scenario can occur, e.g. if a component has an input property expecting a `Screen` type, and is passed `Blank()`. In that case, IsBlank() is a valid operation on the control type, even if we're not coercing to the primary output property.
=> IsBlank can operate on controls without coercing

src/libraries/Microsoft.PowerFx.Connectors/Execution/FormulaValueSerializer.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorTests.cs
This test could be unpredictable depending on the your local timezone and/or time in the day
=> Make Office365Outlook_V4CalendarPostItem test reliable

src/libraries/Microsoft.PowerFx.Repl/Repl.cs, src/tests/Microsoft.PowerFx.Repl.Tests/ReplTests.cs, src/tools/Repl/Program.cs
Addresses:
- https://github.com/microsoft/Power-Fx/issues/2015
- https://github.com/microsoft/Power-Fx/issues/2014
Without Echo (default if running in the local REPL in this repo), only Notify calls will display - see first run.  All other results will only be shown if Echo is on - see second run.
Line numbers are now shown with errors, if the host passes the line number information in.  This is very helpful if processing a file.
=> Further REPL improvements

src/libraries/Microsoft.PowerFx.Repl/Repl.cs, src/libraries/Microsoft.PowerFx.Repl/Services/MultilineProcessor.cs, src/tests/Microsoft.PowerFx.Repl.Tests/MultilineProcessorTests.cs, src/tests/Microsoft.PowerFx.Repl.Tests/ReplTests.cs, src/tools/Repl/Program.cs, src/tools/Repl/Repl.csproj
Reverts microsoft/Power-Fx#2000
This needs some more work.
- Not designed for REPL library consumers, like the PAC CLI.
- Isn't working for me.
- Use of ESC and TAB keys breaks multiline detection.
- The extra newline in the prompt was there for a reason when used with the PAC CLI and should be retained.
=> Revert "Add Intellisense in Repl, with TAB, ESC, UP, DOWN keys management"

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs
BindKind.Data is used for non-component collections in legacy PA cases, but for components, ScopeCollection is used. This matches the behavior for those so that both are considered stateful and not lifted out of row scopes.
=> Also mark ScopeCollection references as stateful

src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/OpenApiParserTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/Responses/Teams_GetMessageDetails_GetSuggestionsForChannel.json, src/tests/Microsoft.PowerFx.Connectors.Tests/Responses/Teams_GetMessageDetails_InputType.json
PowerFX doesn't handle the situation when the parameter reference is referencing a specific field in the record. E.g.
"x-ms-dynamic-list": {
"operationId": "GetChannelsForGroup",
"itemsPath": "value",
"itemValuePath": "id",
"itemTitlePath": "displayName",
"parameters": {
"groupId": {
"parameterReference": "body/recipient/groupId",
"required": true
}
}
}
=> [Connectors] Property handle parameter reference

src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/tests/Microsoft.PowerFx.Core.Tests/TypeSystemTests/DTypeTests.cs
A call to TryGetPath was asserting on a valid invocation (last case in the newly added tests). It shouldn't assert - it should just return false in that case.
=> Prevent assert on DType.TryGetPath

src/libraries/Microsoft.PowerFx.Connectors/Texl/ConnectorTexlFunction.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/2045.
This fix addresses the intellisense problem only. Other mentioned issues are now individual filed issues.
=> Intellisense now displays connector optional parameters as record

src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/2052.
This fix does not address the exception since https://github.com/microsoft/Power-Fx/pull/2033 was fixed previously.
This PR addresses a new situation when running the expression described on this issue.
=> Handling date-no-tz type as datetime

src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/libraries/Microsoft.PowerFx.Connectors/Internal/ConnectorDynamicValue.cs, src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs
*Issue description*
When the x-ms-dynamic-values has "BuiltInOperation" instead of a normal operation, PowerFX reports that the parameter supports Suggestion calls. When this call is done, PowerFX throws with NullRefException:
Object reference not set to an instance of an object., Callstack
at Microsoft.PowerFx.Connectors.ConnectorFunction.GetArguments(ConnectionDynamicApi dynamicApi, NamedValue[] knownParameters, BaseRuntimeConnectorContext runtimeContext)\r\n
at Microsoft.PowerFx.Connectors.ConnectorFunction.GetConnectorSuggestionsFromDynamicValueAsync(NamedValue[] knownParameters, BaseRuntimeConnectorContext runtimeContext, ConnectorDynamicValue cdv, CancellationToken cancellationToken)\r\n
at Microsoft.PowerFx.Connectors.ConnectorFunction.GetConnectorSuggestionsInternalAsync(NamedValue …
=> Fix null reference when trying to get suggestions for BuiltInOperation

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Search.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/SortByColumns.cs, src/tests/Microsoft.PowerFx.Core.Tests/AssociatedDataSourcesTests/TestDVEntity.cs, src/tests/Microsoft.PowerFx.Core.Tests/AssociatedDataSourcesTests/TestDelegationValidation.cs, src/tests/Microsoft.PowerFx.Core.Tests/AssociatedDataSourcesTests/TestUpdateDataQuerySelects.cs, src/tests/Microsoft.PowerFx.Core.Tests/Helpers/TestTabularDataSource.cs
The logic to determine the delegability of the Search function does not work properly with column names as identifiers. This fixes it.
=> Fix delegation validation for Search function

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/DateTime.cs
The SubDayStringList field is not used anywhere, can be removed.
=> Remove unused member from DateAddFunction class

src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseData/IntellisenseData.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs
Expected returntype can have Dataverse type as expected return type. And that can cause intellisense to explode as that type can potentially point to different DV Tables.
This PR mitigates that by limiting intellisense to top-level fields, so intellisense never drills into nested fields. That helps us with the speed and out primary use case for the expected return type is to suggest top-level field anyways.
=> Prune expected returntype intellisense.

src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs, src/tests/Microsoft.PowerFx.Core.Tests/UserDefinedFunctionTests.cs
If we have unterminated double quotes in a string interpolation island in user definitions, that would cause an infinite loop and this PR fixes that
=> Fixed string interpolation with user definitions

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseResult.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/MarkdownString.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/SignatureHelp/DisclaimerProvider.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/SignatureHelp/SignatureInformation.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/LanguageServer/LanguageServer.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Protocol/MarkupContent.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Protocol/ParameterInformation.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Protocol/SignatureHelp.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Protocol/SignatureInformation.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/BindingEngineTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/DisclaimerProviderTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/MarkdownStringTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SignatureHelpTest.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/LanguageServerTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/PublicSurfaceTests.cs
Fix #1202
The disclaimer is markdown (including a help link) in the resources.
1. TexlFunction gets a virtual flag noting whether the function needs a disclaimer.  Default impl is based on a whitelist of AI functions, but we can override this flag next.
2. LSP will get flag and append , and send markdown to formula bar. 
This productizes the POC from #2099 .
=> Add AI disclaimer

src/Directory.Build.props, src/buildAndRefresh.bat, src/refreshLocalNugetCache.ps1
As we increase our official NuGet version, the version from a local build should have a higher version number. This increases it to a very large number, which should be enough until our major version update.
=> Increase local NuGet version to a large number

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Public/FunctionInfo.cs, src/tests/Microsoft.PowerFx.Core.Tests/CheckResultTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/Extensions.cs, src/tests/Microsoft.PowerFx.Core.Tests/FunctionInfoTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ConfigTests.cs
Add public helpers for getting function intellisense and parameter names.
These exist on TexlFunction, but is not exposed.
=> Add helpers for getting function parameter names.

src/libraries/Microsoft.PowerFx.Core/App/ErrorContainers/ErrorContainer.cs
Issue: During tight loops we sometimes need only error count and at this time we can only call GetErrors() which returns IEnumerable and the iterate though each error using Count() extension. It would improve performance if we can have native Count property
=> Added Count to ErrorContainer

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Types/IExternalControlType.cs
This removes a pointless restriction on property access via Gallery.Selected.
These properties were already accessible directly on children of the gallery, and this restriction doesn't have any runtime justification for existing. It also blocks deprecation of primary output properties (Icon has a design primary output prop, others might as well)
=> Allow access to design properties via Gallery.Selected

src/libraries/Microsoft.PowerFx.Core/Utils/Extensions.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/CollectFunctionTests.cs
Issue https://github.com/microsoft/Power-Fx-Dataverse/issues/423.
Ideally, PFx should support this. For the time being, let's return an error at compilation time.
=> Dont coerce Boolean to BooleanOptionSet when mutating.

src/libraries/Microsoft.PowerFx.Core/Public/Values/DateTimeValue.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryDate.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/DateAdd_TimeZone_London.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/DateValue_TimeZone_London.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests/DateTimeUTCTests.cs
There were some parts of the code that were mistakenly treating the GMT (i.e., London) time zone as UTC. Those are the same for part of the year, but not for all of it, which was causing some issues with parsing and adding date values. This change addresses it.
=> Fix handling of GMT time zone

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Lexer/Tokens/IdentToken.cs, src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Parser/NamedFormula.cs, src/libraries/Microsoft.PowerFx.Core/Parser/ParserOptions.cs, src/libraries/Microsoft.PowerFx.Core/Parser/PartialAttribute.cs, src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/UserDefinitions.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/AttributeParserTests.cs
This is an early prototype of support for a [Partial] attribute that enables combining named formulas.
This is done via name-mangling in the parser, renaming each NF to foo_Guid_0, foo_guid_1, ... and then creating a new hidden nf
Foo = Op(foo_guid0, foo_guid1, ...). This allows us to update the formulas independently in authoring, and process them without real changes to NF handling on the PA side.
=> Add [Partial] combination attribute support for Named Formulas

src/libraries/Microsoft.PowerFx.Core/Public/Types/BlankType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/BooleanType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/DecimalType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/NumberType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Types/StringType.cs
Small perf improvement: we don't need to create new DType instances for primitive types.
=> Don't create new DType instances for primitive FormulaType classes

src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/ConfigTests.cs
Issue https://github.com/microsoft/Power-Fx/issues/1578.
This was already available but now moving to `RecalcEngine` and no more need to extend `Engine` class.
=> Exclude a list of functions

src/libraries/Microsoft.PowerFx.Core/Lexer/Tokens/IdentToken.cs, src/tests/Microsoft.PowerFx.Core.Tests/AttributeParserTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/ParseTests.cs
For the Record support in PA Client for merge attributes, we're introducing a function that is only callable from generated expressions, not user code. This adds a flag to tell if an identifier is from source directly, or from something we generated.
=> Expose non-source flag on IdentToken to internals

src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/LanguageServer/LanguageServer.cs
Small pr that handles a null ref and makes const public since Power Apps doesn't seem to have internal access to Language Server SDK and i cannot access the internal static const
=> Nl2Fx: Handle Null Ref and Make Static Const Public

.editorconfig
Opening in VS 17.9.0, something has changed about how VS reads IDE rules and it's now complinaing about 100s of things.
=> Fix IDE rules to not complain about existing code.

src/libraries/Microsoft.PowerFx.Repl/Services/StandardFormatter.cs
Fix for a small issue I found while using REPL.
`Table({Value:1}, Blank())`
=> REPL fix to print blank records

src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/OptionSetInfo.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/PowerFxConfigExtensions.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/OptionSetInfo.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/Docs/DocTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs, src/tools/Repl/Program.cs
OptionSetInfo only returns one value, the logical name of an option set choice.  We'd like to redesign this function to accommodate:
1. The logical name is a text wrapped number for number and Boolean backed option sets coming from Dataverse.  We recently added the ability to get at these values with the Value and Boolean functions which is a better way, strongly typed.  https://github.com/microsoft/Power-Fx/pull/2230
1. There are other pieces of information that are worth knowing, for example the color of an option set choice, that can't be accommodated with this design.  
1. Our preferred design is to return an extensible record of information.  We could add an additional second argument with an enum to determine what information to return, with a default value of logical name, but this …
=> Deprecate OptionSetInfo, prepare way for new ChoiceInfo function

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Lookup.cs
Incorrect logic for determining whether a LookUp Call node could be delegated was added in a previous PR https://github.com/microsoft/Power-Fx/pull/2065
Updating the logic to ensure proper handling of edge cases
=> Update the Delegation logic for LookUp Call nodes

src/libraries/Microsoft.PowerFx.Core/Binding/BindInfo/NameLookupInfo.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SlotMap.cs, src/libraries/Microsoft.PowerFx.Json/FormulaValueJSON.cs, src/tests/Microsoft.PowerFx.Json.Tests/ParseJSONTests.cs
Applied the significant changes suggested in the comments from the previous pull request.
=> Fix for TableFromJsonArray: handling empty arrays with specified TableType #2267

src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/tests/Microsoft.PowerFx.Core.Tests/TypeSystemTests/DTypeTests.cs
Fixes a longstanding intermmitent Arg Null Exception we've seen, when DType.Invalid leaks into the system.
=> Ensure AssociatedDataSources is nonnull even for DType.Invalid

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Table.cs, src/tests/Microsoft.PowerFx.Core.Tests/Helpers/TestTabularDataSource.cs, src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs
Table function gives incorrect warnings in cases like
```
With({majors: Filter(DS, Age >= 18)},Table(majors,{Id:0, Name: \"Other\", Age:100}))
```
this PR addresses this issue.
=> Fix incorrect warnings from Table function

src/libraries/Microsoft.PowerFx.Core/App/ErrorContainers/ErrorContainer.cs, src/tests/Microsoft.PowerFx.Core.Tests/BinderTests.cs
This fixes a nullref that's always been possible in ErrorContainer.HaserrorsInTree Following #2284 it was more common that errors had only a token and not a node. This wasn't handled in this function.
=> Avoid nullref in ErrorContainer

src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs, src/libraries/Microsoft.PowerFx.Core/Texl/PostCheckErrorHandler.cs, src/tests/Microsoft.PowerFx.Core.Tests/EngineTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs
Hosts can now add custom host specific authoring error without extending the Engine class.
=> Adds a way Hosts can add error without extending Engine.

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/ShowDropColumnsBase.cs, src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs
Now that ShowColumns can be used with display names, we should propagate the name mapping so that its output also has both logical and display names.
=> Propagate display names with ShowColumns

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/strings/PowerFxResources.en-US.resx
We have a string that is a fwlink redirector in our localized resources. Fwlinks should not be translated (it redirects to the user locale, based on the browser's language), so this change removes it.
=> Removed resource that should not be translated

src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/UserDefinitions.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/tests/Microsoft.PowerFx.Core.Tests/AttributeParserTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/ParseTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/UserDefinedFunctionTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/UserDefinedTests.cs
Step 2 of allowing user defined types effort .
Retires `UserDefinitions.ProcessUserdefinitions` as it creates a tight coupling between Parse and processing of all different kinds of Userdefinitions. 
We and our tests assume that client uses this method for processing, hence fixing all the tests as we will not use this moving forward.
Moving `AllowAttributes` transformation to `Parse` as it is a transformation of `ParseResult` and returns a `ParseResult` . Ideally this could be a transformation on NamedFormula `ParseResult` .
This will be followed with  
1. Introduce NamedTypes, LookupType in INameResolver but support only Primitives. Remove PrimitiveTypeSymbolTable usage , Require INameResolver to create UDFs.
2. Introduce parsing and adding user defined NamedTypes.
3. Optimize type graph …
=> Retire ProcessUserdefinitions

src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/BaseConnectorTest.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/Microsoft.PowerFx.Connectors.Tests.csproj, src/tests/Microsoft.PowerFx.Connectors.Tests/O365OutlookTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests/Responses/AzureBlobStorage_GetFileContentV2.raw
When a connector function was supposed to return a BlobValue, we were returning a string instead.
=> Fix connector function when returning a blob

src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs, src/tests/Microsoft.PowerFx.Core.Tests/ParseTests.cs, src/tests/Microsoft.PowerFx.Core.Tests/UserDefinedFunctionTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/UserDefinedTests.cs
We considered UDF with parse failures in body to be parse valid UDFs which leads to issues when binding the body of UDFs with errors. 
In This PR we check if there are any new errors after parsing body and set parseValid appropriately.
=> Fix UDF with invalid body to be ParseInvalid

src/libraries/Microsoft.PowerFx.Core/Binding/BinderUtils.cs, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/StronglyTypedEnum_BuiltInEnums.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/StronglyTypedEnum_BuiltInEnums_PreV1.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/StronglyTypedEnum_TestEnums.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/StronglyTypedEnum_TestEnums_PreV1.txt
Addresses customer reported bug in pre-V1 where option set value = Blank() resulted in an error.  General remedy is to return the pre-V1 code to its original state and have a large if around V1 vs. pre-V1 code.  And more tests.
=> More improvements to strongly typed option sets

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/AddColumns_SupportColumnNamesAsIdentifiers.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Record.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/With_Decimal.txt, src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/With_Float.txt
Updates error to "The '.' operator cannot be used on <TypeName> values"
The error shows up in the case of
"the thing on the left of “.” is a number/string/other thing you can’t use “.” on ever, excluding polymorphic because it's weird"
=> Update Invalid Use of Dot error

src/strings/PowerFxResources.en-US.resx
The localization team asked us to remove the locked directive for one resource, as it was having errors in a few languages.
=> Update resource strings per localization team feedback

src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Protocol/BaseNLParams.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Protocol/CustomFx2NLParams.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Protocol/CustomNL2FxParams.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Public/NLHandler.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/PublicSurfaceTests.cs
This pr simply adds a new field to capture diagnostics for fx2nl or nl2fx
=> Add Field to Nl2Fx and Fx2Nl Result Dtos to hold diagnostics info such as Model prompt

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs, src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/DeferredSymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolProperties.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTableOverRecordType.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/CollectionTableValue.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/TableValue.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Clear.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Patch.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/PowerFxConfigExtensions.cs, src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryTable.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/CollectFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/RemoveFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/SetFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/Clear_V1Compat.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/FileExpressionEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/MutationScripts/AutomatedLowCodePlugins.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/MutationScripts/DeepMutation_V1Compat.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/MutationScripts/Set_DeepMutation_V1Compat.txt, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/PowerFxEvaluationTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/Scenarios/DataTableMarshallerProvider.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/SetFunctionTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/SymbolValueTests.cs, src/tests/Microsoft.PowerFx.TexlFunctionExporter.Shared/YamlTexlFunction.cs
Adds support for deep mutation through the Set function.  `Set( a, {b:1} )` doesn't change and will assign a reference to the record `{b:1}` to the variable `a`.  After `a` has been established, it now supports mutation through `Set( a.b, 2 )`.  This is an optional facility that is disabled by default and there are no semantic changes.  When creating variables the host has the option to enable this with `SymbolProperties.CanSetMutate`.
This also fixes two related bugs.  First, really deep mutations were not being properly copied on write, where `t` should be unaffected by the Patch https://github.com/microsoft/Power-Fx/issues/2450:
```
>> Set( deep, [[[[1,2,3],[4,5,6]]]] )
deep: [[[[1, 2, 3], [4, 5, 6]]]]
>> Set( t, deep )
t: [[[[1, 2, 3], [4, 5, 6]]]]
>> Patch( …
```
=> Deep mutations of records, squashed

src/libraries/Microsoft.PowerFx.Connectors/Microsoft.PowerFx.Connectors.csproj, src/libraries/Microsoft.PowerFx.Json/Microsoft.PowerFx.Json.csproj, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Microsoft.PowerFx.LanguageServerProtocol.csproj, src/tests/.Net4.6.2/Microsoft.PowerFx.Core.Tests/Microsoft.PowerFx.Core.Tests.csproj
#2442 bumped System.Text.Json nuget from to 6.0.9.  But not all consumers are updated. 
Restore back to 6.0.8
=> Restore STJ nuget version to 6.0.8

src/libraries/Microsoft.PowerFx.Interpreter/DebugDump.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/ComposedReadOnlySymbolValues.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/ReadOnlySymbolValues.cs, src/libraries/Microsoft.PowerFx.Interpreter/ParsedExpression.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/SymbolValueTests.cs
Add helper for creating SymbolValues from CheckResults. 
This is tricky since it needs to include whatever symbolVAlues the checkresult already has. So Check.Symbols.CreateValues() may miss those and end up creating duplicate symbol values. 
Also add more tests
=> Better SymbolValue Helpers

src/libraries/Microsoft.PowerFx.Core/Public/Values/InMemoryRecordValue.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/RecordValue.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Collect.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryMutation.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/Collect_V1Compat.txt, src/tests/Microsoft.PowerFx.Core.Tests.Shared/RecordValueTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/MutationFunctionsTests.cs
This includes:
- Coercion fixes.
- Blank fields after adjusting the record/table type.
- Interpreter implementation was not handling Dataverse errors when appending.
=> Collect fixes

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunctionSet.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/ComposedReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/ComposedSymbolTableCache.cs, src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/FunctionTests.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/SymbolTableTests.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ThreadingTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/ConfigTests.cs, src/tools/Repl/Program.cs
Optimize the pattern where:
- a host calls eval many times in a loop. 
- but using the same function set in all cases, as determined by just PowerFxConfig (with some enables).
This PR is an optimization and there shouldn't be any functional changes. However - we should review some of the behavior around TexlFunctionSet to enable us to pursue more comprehensive optimizations. 
Today, every call to Check() will compute the function set - which involves merging the function set from builtin functions plus the extra ones that were enabled.  This is expensive because TexlFunctionSet will "flatten" and copy all the functions into a single list. (Contrast to how we compose SymbolTables - which is entirely deferred). 
The optimization is to allow composing that once and caching it. But also to be …
=> Optimization for function sets 

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Collect.cs
PR https://github.com/microsoft/Power-Fx/pull/1964 checks for read-only fields. Changing the condition to run this check since PA deals with read-only fields differently.
=> Collect check semantics PA change

src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs
`CreatesImplicitScreenDependency` is a PowerApps specific behavior to InvokeControl functions and doesn't need to be in this class here. We can drive IsRestrictedInsideUdfBody from that flag in PowerApps.
=> Revert/Change TexlFunction flag name restricting use inside UDF

src/libraries/Microsoft.PowerFx.Core/Types/DType.cs
Noticed from telemetry some NullReferenceException errors in those new properties. Adding guard to fix it.
=> Fix NullReferenceException on new IsOptionSetBackedByXXX properties

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs
Getinfo may return null to certain callNodes and hence it is creating NullReferenceException consistently as a noise. this PR fixes that issue.
=> Add Nullcheck to GetInfo result in TryGetEntityInfo

src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/InternalTesting.cs, src/tests/Microsoft.PowerFx.TexlFunctionExporter.Shared/SwaggerFileIdentification.cs
This is to fix our Power Fx-ConnectorStats pipeline which was broken since we moved to multi-.Net version testing
Have also fixed a couple of places where defective swagger files were causing some trouble
I removed the SQL upload of results as we can't use a connection string anymore (will have to be fixed separately)
=> Internal tests fixes

src/libraries/Microsoft.PowerFx.Core/Localization/StringResources.cs
Perf improvement for string resources. Changes from #2513 by @Robulane
=> Don't lock string resources if not needed

src/libraries/Microsoft.PowerFx.Core/Lexer/TexlLexer.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ParseTests.cs
The lexer doesn't return the proper span for errors with surrogate characters (e.g., `Set(🍰, 1)`). This fixes it.
=> Ensure proper spans on lexer errors with surrogate characters

src/Directory.Build.props, src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/SafeDTypeToStringTests.cs
Fix RecordAndTableDTypeTests inconsistency
Fixed "#if DEBUG" conditions which were false when Debug462/70/All is used
Fix DType.Add behavior which is different between Debug (exception) and Release (no exception) when we want to change the field type in a record/table type.
=> Fix RecordAndTableDTypeTests inconsistency between Debug and DebugAll

src/libraries/Microsoft.PowerFx.Core/Entities/External/IExternalNamedFormula.cs, src/libraries/Microsoft.PowerFx.Core/Texl/ViewFinderVisitor.cs
Currently the logic to detect use of dataverse views in an expression doesn't work well when expression is abstracted under named formula.
For example,
T = Filter(Monthses, 'Monthses (Views)'.MyView);
Label1.Text = CountRows(T);
CountRows(T) is not detected currently as non-delegated expression as a result. This change fixes that. Unit test will be added on PAClient side for this where all of the delegation tests currently are.
=> Added another property on interface IExternalNamedFormula to detect reference to views in NF expressions.

src/libraries/Microsoft.PowerFx.Core/Syntax/UserDefinitions.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/UserDefinedFunctionTests.cs
Dataverse columns support hyperlink types so this is needed for datasource types.
=> Revert change to remove hyperlinks from allowed UDF types

src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Protocol/CustomFx2NLParams.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Protocol/ScalarRange.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/LanguageServiceProtocol/LegacyLanguageServerTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/LanguageServiceProtocol/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/LanguageServiceProtocol/RedesignedLanguageServerTests/Fx2NLTests.cs
Update the expected params for Fx2Nl (CustomFx2NLParams) with an optional range field.
This will be used and passed down for the explain this partial formula explanation.
=> Adding optional range param to custom fx2nl param

src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/libraries/Microsoft.PowerFx.Connectors/Execution/HttpFunctionInvoker.cs, src/libraries/Microsoft.PowerFx.Core/Public/ErrorKind.cs, src/libraries/Microsoft.PowerFx.Core/Public/HttpExpressionError.cs, src/libraries/Microsoft.PowerFx.Core/Types/Enums/BuiltInEnums.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Json/FormulaValueJSON.cs, src/libraries/Microsoft.PowerFx.Json/PowerFxJsonException.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Microsoft.PowerFx.Connectors.Tests.Shared.projitems, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/OpenApiParserTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PowerPlatformConnectorTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Responses/Azure Cognitive Service For Language v2.1_Invalid Response 2.json, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Responses/Azure Cognitive Service For Language v2.1_Invalid Response 3.json, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Responses/Azure Cognitive Service For Language v2.1_Invalid Response 4.json, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Responses/Azure Cognitive Service For Language v2.1_Invalid Response 5.json, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Responses/Azure Cognitive Service For Language v2.1_Invalid Response.json, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/Error.txt, src/tests/Microsoft.PowerFx.Core.Tests.Shared/IntellisenseTests/SuggestTest.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Json.Tests.Shared/ParseJSONTests.cs
Json deserialization can be "broken" with some exceptions which are impossible to understand for customers
This PR fixes/updates the error messages and wraps the Json deserialization issues into an ErrorValue instead of being inconsistent (previously, we would have an ErrorValue for invalid Json and a NotImplementedException if there was a type mismatch between what the connector code expects and what we got from the server)
We also accept some trivial mismatches
Add ErrorKind.InvalidJson
Add HttpExpressionError to return StatusCode in ErrorValue
=> Fix 2523 - Improve Json deserialization errors and be more permisive

src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/libraries/Microsoft.PowerFx.Core/Public/ErrorKind.cs, src/libraries/Microsoft.PowerFx.Core/Types/Enums/BuiltInEnums.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs, src/libraries/Microsoft.PowerFx.Json/FormulaValueJSON.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/OpenApiParserTests.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/Error.txt, src/tests/Microsoft.PowerFx.Core.Tests.Shared/IntellisenseTests/SuggestTest.cs
The newly added ErrorKind.InvalidJson should be called InvalidJSON, as JSON is an acronym and should be capitalized as in other places of the framework (such as in the ParseJSON function)
=> Update ErrorKind.InvalidJSON to use proper capitalization

src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ParseTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/RecalcEngineTests.cs
***Current State***
When Imperative UDF feature is enabled, UDF returning a record value needs to wrap it in parenthesis (eg: `F(): Point = ({x: 5, y:5})`) to parse it without errors.
***Fix***
* This PR adds logic to look ahead and decide between imperative definition and record value.
* UDFs with a body containing just `{}` is considered empty record and not imperative definition.
=> Allow UDF to return record without special syntax

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs
For an expression such as `With({a:1}, Set(a, 10))`, the first argument of the Set function should not refer to the scope variable `a` defined by the With function.
=> Update order of checking for scoping variable during binder's visit of FirstName

src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Handlers/Fx2Nl/Fx2NlLanguageServerOperationHandler.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Handlers/GetCustomCapibilities/GetCustomCapabilitiesLanguageServerOperationHandler.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Handlers/LanguageServerOperationContext.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Handlers/Nl2Fx/Nl2FxLanguageServerOperationHandler.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/LanguageServer/INLHandlerFactory.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/LanguageServer/LanguageServer.cs, src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Public/NLHandler.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/LanguageServiceProtocol/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/LanguageServiceProtocol/RedesignedLanguageServerTests/Fx2NLTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/LanguageServiceProtocol/RedesignedLanguageServerTests/GetCustomCapibilitiesTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/LanguageServiceProtocol/RedesignedLanguageServerTests/Nl2FxTests.cs
This pr makes nl handler creation async so during creation time, PA can attach context reduction filters with Nl handler which would then later be used to trim down the context. This pr also refactors nl2fx, fx2nl handlers to avoid class fields
=> Make Nl2Fx/Fx2nl Handler creation Async to allow for setting up custom NlHandler with Nl2Fx context reduction filters

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Types/ExpandPath.cs
Unable to easily test in this repo. Tests added in PA Client. 
Scenario is, e.g. for this expression, the expand info to the second PrimaryContact access should have ManagingPartner as part of it's expand path. 
"ClearCollect(c3,  Filter(Accounts,'Primary Contact'.Status <> 'Status (Contacts)'.Active));" +
"ClearCollect(c4,  Filter(Contacts, 'Managing Partner'.'Primary Contact'.Status <> 'Status (Contacts)'.Inactive))"
=> Fixes reuse of expandinfo from cache when expand is accessed via a different path

src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs
`GUID` is a known function.
`Guid` is an unknown function but PFx mistakenly finds it in the list of unsupported known functions. 
Before:
After:
=> GUID is a known function

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs
There was a mistake in following PR: https://github.com/microsoft/Power-Fx/commit/752efe46c476975a5433d9aab127f0b66808c187
=> Fix check to exclude UDFs from being marked as async if binding does not exist

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Visitors/ListFunctionVisitor.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ListFunctionVisitorTests.cs
Previously at https://github.com/microsoft/Power-Fx/pull/2474 we introduced an API to get a list of called functions from an expression.
We are now adding an option to anonymize a custom function to mask any private information.
=> Option to anonymize unknown public functions

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/PadUntypedObjectTests.cs
Reply to https://github.com/microsoft/Power-Fx/pull/2588.
=> ColumnName to work with array untyped object

src/libraries/Microsoft.PowerFx.Core/Public/Types/AggregateType.cs
Primarily used for optimizing delegation when looking up record with primary key on a relationship. 
e.g. LookUp(t1, relationField.PrimaryKey = GUID).
=> Adds a virtual to get primary key

src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/WeekNum.txt, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/WeekNum_StronglyTypedEnumDisabled.txt, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/WeekNum_StronglyTypedEnumEnabled.txt
Some tests for WeekNum should be split properly between those with support for strongly-typed enums and those without.
=> Split WeekNum tests to better reflect setup

src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Visitors/ListFunctionVisitor.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ListFunctionVisitorTests.cs
We are adding a way for the hosts to declare a list of non-core public functions that should be kept plain when getting function names from an expression.
=> Dont anonymize known custom functions

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/RecalcEngineTests.cs
In scenario of `F():Void = { F(); }`, when finalizing the binding, the Binder will attempt to fetch the CallNode datasource,
Because UDF `TryGetDatasource` override needs the binding, in this cycle/"recursive" edge case, there will be a null reference exception without the check added in this PR.
=> Avoid NRE in cycle edge case of imperative UDF binding

src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/libraries/Microsoft.PowerFx.Connectors/Execution/HttpFunctionInvoker.cs, src/libraries/Microsoft.PowerFx.Connectors/Internal/Wrappers/SwaggerJsonSchema.cs, src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorSettings.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/CdpTableResolver.cs, src/libraries/Microsoft.PowerFx.Json/FormulaValueJSON.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/CompatibilityTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Helpers/LoggingTestServer.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Microsoft.PowerFx.Connectors.Tests.Shared.projitems, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PowerPlatformTabularTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Responses/Compatibility GetSchema.json
Add CDP compatibility flag
When enabled, we don't require format=enum
=> CDP connectors - manage enums per OpenApi spec

src/libraries/Microsoft.PowerFx.Connectors/OpenApiParser.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorSettings.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/OpenApiParserTests.cs
In the Teams connector, the operation "PostCardAndWaitForResponse" contains extension "x-ms-notification-content" and is excluded from the parse result of `GetFunctions`.
In MCS, we want to make this operation available to our internal users to keep parity with Power Automate behavior.
This PR fixes the issue by
1. Creating a new setting "IncludeWebhookFunctions" to conditionally include those "webhook" functions on demand.
2. Consume that new setting when filtering on the webhook functions, it set to true, it won't filter away those functions.
As a result, 4 more operations inside Teams connector will be supported by merging this change.
On MCS side, PFX `GetFunctions` will be invoked with an additional setting parameter `IncludeWebhookFunctions = true`.
=> Add new ConnectorSettings "IncludeWebhookFunctions" to allow using more Teams operation

src/libraries/Microsoft.PowerFx.Connectors/Tabular/ExternalCdpDataSource.cs, src/libraries/Microsoft.PowerFx.Core/Entities/External/IExternalTabularDataSource.cs, src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/CountRows.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests.Shared/AssociatedDataSourcesTests/TestDVEntity.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/AssociatedDataSourcesTests/TestDelegationValidation.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/Helpers/TestTabularDataSource.cs
Some data sources, like Dataverse, will cache its count and not return the accurate result if a CountRows call is made to it (see note at https://learn.microsoft.com/power-platform/power-fx/reference/function-table-counts#description). This adds a warning to the node if this happens, to make it more explicit to the makers that this is the case.
=> Add a warning to the CountRows function if a data source that caches its count is passed to it

src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/Intellisense.cs
We found a NRE in Power Apps telemetry that was happening in the Intellisense code on Power Fx. We don't know exactly the cause, but this change is a defense-in-depth that will help preventing that.
=> Prevent NullReferenceException found in telemetry

src/libraries/Microsoft.PowerFx.LanguageServerProtocol/Handlers/Completions/CompletionsLanguageServerOperationHandler.cs
Fixes CompletionItemKind for SuggestioonKind.Types to display correct Intellisense Icon .
=> Fix CompletionItemKind for Types to display correct Intellisense Icon

src/tests/Microsoft.PowerFx.Core.Tests.Shared/TypeSystemTests/DTypeTests.cs
Currently the tree that stores fields of a complex DType (records or arrays) stores those in an ordered way (ordinal comparison). There is some code that relies on that, so codifying it as a test to make it a "specification"
=> Add new test to validate the DType always orders its fields

src/libraries/Microsoft.PowerFx.Core/Localization/ExpressionLocalizationHelper.cs
Working on some cleanup of localization code, and this utility is duplicated in PA Client.
=> Make syntax localization util internal instead of private

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/PlainText.txt
Fixes #2679 . Currently the PlainText doesn't handle some open tags correctly - the function is supposed to convert things like &lt;br/&gt; to a new line or &lt;p&gt; to two new lines, but it is matching tags such as &lt;bra&gt; and &lt;para&gt; which should not be matched.
=> Fix PlainText's handling of open tags

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs
…fore checking for any error/warnings.
=> As rule binding could be null, we need to make sure to check that before checking for errors/warning

src/libraries/Microsoft.PowerFx.Core/Binding/BinderUtils.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Json.cs
NameResolver.Lookup is a weirdly expensive operation when done from the middle of a running analysis pass. 
A few functions call TryGetConstantValue from CheckTypes, which is called during analysis to get functions result types.
In JSON it was possible to move that to CheckSemantics, but in Match, we want to avoid the expensive call to Lookup if we can, so we first look in the EntityStore to resolve enums. 
This doesn't meaningfully change the scenario for non PA hosts, as the entity store is a PA-only concept.
=> Change Lookup order in BinderUtils.TryGetConstantValue to check entitystore first

src/libraries/Microsoft.PowerFx.Core/App/Controls/IExternalRule.cs, src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs
As PA is moving away from rules with null binding, this PR introduces a new property called HasValidBinding which needs to be used to check the binding validity in future rather than Binding property itself. Eventually we should remove the Binding property from rule to abstract that. This change is first step towards that direction.
=> Added a new property on IExternalRule interface.

src/libraries/Microsoft.PowerFx.Core/Logging/StructuralPrint.cs, src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Nodes/TypeLiteralNode.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/TexlPretty.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Visitors/AggregateVisitor.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Visitors/TexlFunctionalVisitor.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/FormatterTests.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ParseTests.cs
Formatting , structural printing and cloning were broken for type literals. This PR fixes these issues and adds tests to ensure the changes work as expected.
Formatting of user definitions is still not perfect and has a bug where it would fail if we had definitions of same kind with same name.  That is not in the scope of this PR and shall be fixed as a follow up
=> Fix formatting and structural printing for type literals

src/libraries/Microsoft.PowerFx.Core/Public/Config/ComposedReadOnlySymbolTable.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/SymbolTableTests.cs
- OptionSets should only return first OS by name (first element wins)
- TryGetVariable not working as expected
=> Fixes in ComposedReadOnlySymbolTable

src/libraries/Microsoft.PowerFx.Connectors/Tabular/Capabilities/ServiceCapabilities.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/Services/CdpTable.cs, src/libraries/Microsoft.PowerFx.Core/Entities/External/TableDelegationInfo.cs, src/libraries/Microsoft.PowerFx.Core/Functions/Delegation/DelegationMetadata/CdpFilterOpMetadata.cs
Those are apparently useless and were creating confusion
FilterFunctions stays at column level
=> Remove ServiceCapabilities.FilterFunctions and TableDelegationInfo.FilterFunctions

src/libraries/Microsoft.PowerFx.Core/Public/Config/ComposedReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/PowerFxConfig.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/ReadOnlySymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs, src/libraries/Microsoft.PowerFx.Interpreter/Environment/PowerFxConfigExtensions.cs, src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/SymbolTableTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/RecalcEngineTests.cs
This PR fixes the issue where inbuilt enums are no longer part of the config if the config's symbol table is replaced after initialization.
After initializing the config if SymbolTable was replaced, we were loosing the enums attached to the previous default symbol table. This PR will adds a default symbol table(seprate from existing table) to handle that.
=> Fixes enum store when SymbolTable is replaced while setting up config

src/libraries/Microsoft.PowerFx.Core/Syntax/Visitors/IdentityTexlVisitor.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Visitors/TexlVisitor.cs, src/libraries/Microsoft.PowerFx.Core/Texl/ViewFilterDataSourceVisitor.cs, src/libraries/Microsoft.PowerFx.Core/Texl/ViewFinderVisitor.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/EngineTests.cs
Making the `TypeLiteralNode` visitor abstract in the `TexlVisitor` to ensure we consider handling TypeLiteralNode in future TexlVisitor implementations. keeping it virtual sometimes made this go unnoticed.
=> Make TypeLiteralNode visitor abstract in TexlVisitor

src/libraries/Microsoft.PowerFx.Core/Public/Config/Features.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/FeaturesTest.cs
Followup to #2740
This changes Features.PowerFxV1 from property to field - which is binary breaking change. 
Undo the break  - but still keep as singleton. 
Add test.
=> Undo breaking change in Features

src/tests/Microsoft.PowerFx.Core.Tests.Shared/TestRunnerTests/InternalSetup.cs
Tests would use reflection to mutate the Features object. 
But #2740 made `Features` a singleton.  So the object was getting randomly mutated. We'd see this as dataverse tests failing.
=> Fix flaky tests - Features is now a singleton.

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Functions/FunctionScopeInfo.cs, src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Join.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/Join.txt, src/tests/Microsoft.PowerFx.Core.Tests.Shared/IntellisenseTests/SuggestTest.cs
Fixing a possible order issue when passing scope types to `scopeInfo.CheckTypes`.
=> Scope args fix

src/libraries/Microsoft.PowerFx.Core/Functions/FunctionScopeInfo.cs, src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Join.cs, src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryTable.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/MutationScripts/Join.txt
When joining along with alias (`Join(t1 As x1, ...)`), the binder would try to access the fields from the wrong scope to evaluate the predicate, resulting in a wrong output.
=> Fixing join result when using source alias

src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/MutationFunctionsTests.cs
This isn't great
"Unknown" isn't a ton more helpful, but at least it's not obviously broken
=> Prevent _Min from showing up in error messages

src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs
See https://github.com/RicoSuter/NJsonSchema/blob/dde6f76a80b8acd55ff4f51e04c77b6b742f4294/src/NJsonSchema/Generation/ReflectionServiceBase.cs#L69
=> Support NSwag JSON schema types and formats

src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/IntellisenseHelper.cs
Telemetry from Power Apps showed a large number of NullReferenceException instances coming from this method. A TryXXX method should return false instead of throwing a NRE.
=> Fix NRE on IntellisenseHelper.TryGetInnerMostFunction

src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs, src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Nodes/TypeLiteralNode.cs, src/libraries/Microsoft.PowerFx.Core/Types/DefinedTypeResolver.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/AsType_UO.txt, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/If.txt, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/IsType_UO.txt, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/TypedParseJSON.txt, src/tests/Microsoft.PowerFx.Core.Tests.Shared/UserDefinedTypeTests.cs, src/tests/Microsoft.PowerFx.Json.Tests.Shared/AsTypeIsTypeParseJSONTests.cs
we plan to refer `Type` as a special function in our documentation and hence changing all references of Type literal in error messages and some cosmetic changes
=> Fix User-Defined Type error messages 

src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs, src/strings/PowerFxRuntimeResources.en-US.resx
Fixes #2781 
Examples of old error:
Example of new error:
=> Fix error message for mismatched types on untyped values

src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ParseTests.cs
Arg Identifier is null for certain UDF declarations eg: `SomeFunc(:` and `F(a: Boolean,:):Number = 1;`. these are intermediate states when writing UDFs and these cause Null ref exception. this makes changes to prevent NRE.
=> Fix UDF arg parse null reference

src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorSettings.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorType.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PowerPlatformConnectorTests.cs
When SupportXMsEnumValues is set to true, we want to force 'modelAsString' to false via ReturnEnumsAsPrimitive  flag
This will keep the x-ms-enum-* extensions to be parsed while creating a consistent FormulaType as string or decimal
=> Add ReturnEnumsAsPrimitive connector settings

src/libraries/Microsoft.PowerFx.Connectors/Public/CdpTableValue.cs, src/libraries/Microsoft.PowerFx.Core/Entities/External/TableDelegationInfo.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/DelegationParameters.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/TableValue.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/PublicSurfaceTests.cs
This pull request introduces several changes to the PowerFx library to support counting capabilities in table delegation. The changes include adding a new method to count rows asynchronously, updating interfaces, and introducing a new class for count capabilities.
Enhancements to counting capabilities:
* [`src/libraries/Microsoft.PowerFx.Connectors/Public/CdpTableValue.cs`](diffhunk://#diff-993c4c638e07f59077c442100bdb8ae7ae8bb5d6a56cc003d71468556198f930R69-R73): Added the `GetCountAsync` method to count rows asynchronously.
* [`src/libraries/Microsoft.PowerFx.Core/Entities/External/TableDelegationInfo.cs`](diffhunk://#diff-3262aeee6122a5873eb3c7866b3db562c90530f04d665f6186b26f32328abcf9R29-R31): Introduced the `CountCapabilities` class and added the `CountCapabilities` property to …
=> Adds Count Capabilites.

src/libraries/Microsoft.PowerFx.Connectors/Tabular/CdpTableResolver.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/Services/CdpDataSource.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/Services/CdpServiceBase.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/Services/CdpTable.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PowerPlatformTabularTests.cs
When using Unicode characters, we were seeing HttpRequestException: Request headers must contain only ASCII characters.
=> Fix issue when using Unicode characters in CDP datasets

src/libraries/Microsoft.PowerFx.Connectors/Tabular/Services/CdpTable.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Microsoft.PowerFx.Connectors.Tests.Shared.projitems, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PowerPlatformTabularTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Responses/SQL GetTables.json, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Responses/SQL Server Get First Customers_Aßþ.json, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Responses/SQL Server Load Customers_Aßþ.json
Tested locally to Preview and Search a CDP table
Fix to resolve Request headers must contain only ASCII characters
=> Adding support to Unicode characters for CDP table

src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PowerPlatformConnectorTests.cs
The condition for the body param required bool was wrong, which resulted in different properties being required when `UseItemDynamicPropertiesSpecialHandling` was on vs off.
See test case which was failing before the fix.
=> Fix special body param required condition

src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/libraries/Microsoft.PowerFx.Connectors/ConnectorHelperFunctions.cs, src/libraries/Microsoft.PowerFx.Connectors/Execution/HttpFunctionInvoker.cs, src/libraries/Microsoft.PowerFx.Connectors/Texl/ConnectorTexlFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/CustomFunction/CustomTexlFunction.cs, src/libraries/Microsoft.PowerFx.Interpreter/CustomFunction/ReflectionFunction.cs
Issue https://github.com/microsoft/Power-Fx/issues/2817.
This pull request focuses on updating method signatures to use `IReadOnlyList<FormulaValue>` instead of `FormulaValue[]` for improved type safety and consistency across the codebase. The changes span multiple files and functions.
Key changes include:
* [`src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs`](diffhunk://#diff-720d55f6094e558103fec3c4f1440cbc4cd5d6af39c7d21ec887627f31f32facL840-R845): Updated `InvokeInternalAsync` method signatures to accept `IReadOnlyList<FormulaValue>` instead of `FormulaValue[]`.
* [`src/libraries/Microsoft.PowerFx.Connectors/ConnectorHelperFunctions.cs`](diffhunk://#diff-5fd134a20257176c5329f27cc3a8ba06ae4b5e69cc75ea248309bfabeec6a7dbL61-R68): Changed `LogArguments` method to use …
=> Array to IReadList

src/libraries/Microsoft.PowerFx.Core/Logging/StructuralPrint.cs, src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/FormatterTests.cs
This pull request includes changes to enhance the handling of enums in the `StructuralPrint` class, update the list of known functions, and improve test coverage.
Enhancements to `StructuralPrint`:
* [`src/libraries/Microsoft.PowerFx.Core/Logging/StructuralPrint.cs`](diffhunk://#diff-4760f19aba839606fcde0849467658572c272afd030c115afae8263986234a6dR9): Added logic to handle default enums in the `Visit` method for `DottedNameNode`, and included the `Enums` namespace. [[1]](diffhunk://#diff-4760f19aba839606fcde0849467658572c272afd030c115afae8263986234a6dR9) [[2]](diffhunk://#diff-4760f19aba839606fcde0849467658572c272afd030c115afae8263986234a6dR126-R134)
Updates to known functions:
* [`src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs`](diffhunk://#diff-5a3b8429b8a783e4a4f50cbc …
=> Dont anonymize Join nor default enums

src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/TypeSystemTests/LazyTypeTests.cs
`DType.Add` overload was broken and it did not work correctly for LazyTypes leading to errors and NullReferenceExceptions in some cases. 
this bug came to light when investigating a customer reported incident for new analysis.
This PR fixes the `DType.Add` overload and adds tests to ensure the fix works as expected.
=> Fix DType.Add overloads

src/libraries/Microsoft.PowerFx.Interpreter/EvalVisitor.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/LanguageTest.cs
Add enforcement.
This is true because the class is private and it's always set here: 
https://github.com/microsoft/Power-Fx/blob/27928265741af482f8c650ccca7902231ead44c8/src/libraries/Microsoft.PowerFx.Interpreter/ParsedExpression.cs#L138
=> EvalVisitor.Culture is always non-null.

src/libraries/Microsoft.PowerFx.Core/Entities/External/TableDelegationInfo.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/DelegationParameters.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/PublicSurfaceTests.cs
This pull request introduces new capabilities for handling top-level aggregations in the `Microsoft.PowerFx.Core` library. The changes primarily focus on adding support for top-level aggregation capabilities and updating related classes and enums.
This is different that Summarize capabilities. Since Summarize **requires** group by, while top level aggregation does not.
e.g.
`Select Sum(col1) from table1 group by col2` equivalent Fx uses Summarize capabilities.
vs
`Select Sum(col1) from table1` equivalent Fx uses TopLevelAggregation capabilities.
* [`src/libraries/Microsoft.PowerFx.Core/Entities/External/TableDelegationInfo.cs`](diffhunk://#diff-3262aeee6122a5873eb3c7866b3db562c90530f04d665f6186b26f32328abcf9R32-R34): Added a new property `TopLevelAggregationCapabilities` to the …
=> Adds capabilities for top level aggregation.

src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Match.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/IsMatch.txt, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/IsMatch_V1Disabled.txt, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/IsMatch_V1Enabled.txt, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/StronglyTypedEnum_BuiltInEnums_PreV1.txt
Restore IsMatch behavior where we fall back to IsConstant if TryGetConstantValue fails.  Takes us back to the old behavior in Power Apps' component properties when the compiler may believe that IsConstant is true when in reality it is not.
=> Update IsMatch constant check for pre-v1

src/libraries/Microsoft.PowerFx.Connectors/Execution/FormulaValueSerializer.cs, src/libraries/Microsoft.PowerFx.Connectors/Execution/OpenApiFormUrlEncoder.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/OpenApiFormUrlEncoderTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/OpenApiJsonSerializerTests.cs
_Today,_ if we have an unknown schema, it requires the record to have a single .Value property (as if it is a primitive).
If it is not, we throw.
_With this change,_ when we are encountering complex (unknown) schemas that arent all .Value, we gracefully write the full record instead of throwing.
Change required updates to the UriFormEncoder to better handle nested objects within arrays.
=> Update FormulaValueSerializer to handle null schemas

src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PowerPlatformConnectorTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PowerPlatformTabularTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Responses/SF GetSchema.json
This pull request includes updates to improve type handling in connectors and expand test coverage by adding new fields and scenarios. The key changes include adjustments to how connector types are determined, updates to test cases to include new fields, and modifications to test data to support the expanded scenarios.
* Updated the `GetConnectorType` method in `OpenApiExtensions.cs` to use the name of the `openApiParameter` instead of the hardcoded string "Array" when creating a `SwaggerParameter`. This ensures consistency and better alignment with the input parameter.
* Modified the `DVDynamicReturnType` test in `PowerPlatformConnectorTests.cs` to adjust the expected structure of the return type, reflecting updates to the connector schema.
* Updated the `SF_CdpTabular_GetTables` and …
=> Fixes issue with OptionSet Naming.

src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Microsoft.PowerFx.Connectors.Tests.Shared.projitems, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/OpenApiParserTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Swagger/TestConnectorNoOutput.json
When the caller explicitly provides a type, we should honor it as such type, no matter the flags on the response type
Today, the override is completely skipped if there was no known output type.
=> dont force raw output when override is set

src/libraries/Microsoft.PowerFx.Core/Functions/UserDefinedFunction.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/UserDefinitions.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/UserDefinedFunctionTests.cs
Today we allow Void type to be used as a valid type in UDF argument while it serves no real purpose. We do not want to allow this pattern and this PR blocks such usage.
=> Block Void type use in UDF argument type

src/libraries/Microsoft.PowerFx.Connectors/Public/CdpTableValue.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorSettings.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/DefaultCDPDelegationParameter.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/Services/CdpService.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/Services/CdpTable.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/FileTabularConnector.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PowerPlatformTabularTests.cs
This pull request introduces a new delegation parameter class to handle `$top` query parameters for paginated data retrieval, updates the `ConnectorSettings` class to support configurable maximum row limits, and integrates these changes into the existing `CdpTable` and `CdpTableValue` implementations. It also includes updates to tests to validate the new functionality.
* **Added `DefaultCDPDelegationParameter` class**: This new class implements delegation parameters to generate OData query strings, including `$top` for row limits. (`src/libraries/Microsoft.PowerFx.Connectors/Tabular/DefaultCDPDelegationParameter.cs`)
* **Updated `CdpTableValue.Rows` property**: Modified to use the new `DefaultCDPDelegationParameter` for setting the maximum number of rows via `$top`. …
=> Enforces default Top for CDP Connector for non delegating expression.

src/libraries/Microsoft.PowerFx.Connectors/Public/CdpTableValue.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/CDPDelegationTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Microsoft.PowerFx.Connectors.Tests.Shared.projitems, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Responses/BlankTopLevelAggregation.json
This pull request introduces enhancements to the `Microsoft.PowerFx.Connectors` library and its associated test suite. The changes include improvements to blank value handling, the addition of a comprehensive test class for CDP delegation, and updates to test resources and project files to support the new functionality.
* **Improved blank value handling**: Updated the `ConvertToExpectedType` method in `CdpTableValue.cs` to create a new blank value using the expected type instead of returning the original blank value. This ensures better type consistency.
* **New CDP delegation test class**: Added `CDPDelegationTests.cs`, a detailed test class that validates CDP delegation functionality, including OData execution and table initialization. This class introduces mock delegation parameters …
=> Correct Blank handling for CDP Connectors.

src/libraries/Microsoft.PowerFx.Connectors/ConnectorConstants.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/AiSensitivity.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/BaseRuntimeConnectorContext.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/CdpExtensions.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/CdpTableValue.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorEnhancedSuggestions.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorKeyType.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorLogger.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorParameter.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorParameterWithSuggestions.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorParameters.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorPermission.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorSchema.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorSettings.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorType.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ICDPAggregateMetadata.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/MediaKind.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/PowerFxConnectorException.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/SupportsConnectorErrors.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/Visibility.cs
I spent about an hour trying to see which descriptions could be updated using VSCode Copilot Agent mode with this prompt:
```
Please scan all .cs files in the current workspace. For each file:
1. Only process public interfaces, enumerations, classes, methods, properties, and fields.
2. Do not touch private, internal, or protected members.
3. If a public member already has a /// XML comment, leave it unchanged.
4. If a public member is missing a /// comment, add a basic XML summary comment.
5. Do not modify formatting or indentation.
This operation must be idempotent and safe to run multiple times.
```
And a little trial & error.
If these descriptions can be updated, then perhaps this reference documentation will be more valuable: …
=> Again: Adding Copilot generated /// comments for connector namespace 

src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/OpenApiExtensionTests.cs
The operation "Get page content" in the OneNote connector (https://msazure.visualstudio.com/One/_git/AAPT-connectors?path=/src/Connectors/FirstParty/onenote/Connector/apidefinition.swagger.json&version=GBmaster) only outputs an text/html content-type which is not supported by PowerFx: https://github.com/microsoft/Power-Fx/blob/main/src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs#L922
Mike Stall who leads PowerFx is OK with text/html being allowed.
This PR add support for text/html type output.
=> Add support for text/html type output

src/libraries/Microsoft.PowerFx.Connectors/ConnectorConstants.cs, src/libraries/Microsoft.PowerFx.Connectors/ConnectorFunction.cs, src/libraries/Microsoft.PowerFx.Connectors/Internal/Wrappers/SwaggerJsonArray.cs, src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/CdpRecordType.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorType.cs, src/libraries/Microsoft.PowerFx.Connectors/Public/ICDPAggregateMetadata.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/CdpTableResolver.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/Services/CdpDataSource.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/Services/CdpTable.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/Services/InternalObjects.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/CompatibilityTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PowerPlatformTabularTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PublicSurfaceTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Responses/SQL GetSchema Products.json, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/Responses/SQL GetTables SampleDB.json
This pull request introduces support for handling sensitivity labels in the Microsoft PowerFx Connectors library. The changes include adding new constants, methods, and properties to manage sensitivity label metadata and improving the internal structure for caching and retrieving metadata. Below is a summary of the most significant changes:
* Added a new constant `XMsContentSensitivityLabelInfo` to `ConnectorConstants` for handling sensitivity label-related metadata. (`[src/libraries/Microsoft.PowerFx.Connectors/ConnectorConstants.csR25](diffhunk://#diff-f48903b696f5100da35ca9eb7593916ea62f5be930ddbd0299c8d7d78c947cc8R25)`)
* Introduced a new method `GetFieldMetadata` in `OpenApiExtensions` to deserialize sensitivity label metadata from Swagger extensions. …
=> Enable MIP Label via Metadata endpoint.

src/libraries/Microsoft.PowerFx.Core/Functions/UserDefinedFunction.cs, src/libraries/Microsoft.PowerFx.Core/Localization/Strings.cs, src/libraries/Microsoft.PowerFx.Core/Syntax/Visitors/DTypeVisitor.cs, src/strings/PowerFxResources.en-US.resx, src/tests/Microsoft.PowerFx.Core.Tests.Shared/UserDefinedFunctionTests.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/UserDefinedTypeTests.cs, src/tests/Microsoft.PowerFx.Json.Tests.Shared/AsTypeIsTypeParseJSONTests.cs
Restrict void return type from being used in non-behavior UDF. Also blocks Void to be used in aggregate types in UDTs.
=> Restrict void return type in non-behavior UDF

src/libraries/Microsoft.PowerFx.Connectors/PowerPlatformConnectorClient.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/IntellisenseTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/OpenApiParserTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PowerPlatformConnectorClientTests.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/PowerPlatformConnectorTests.cs
This pull request introduces a new HTTP header, `x-ms-enable-selects`, to enable additional functionality in requests, and updates related test cases to validate its inclusion. The changes ensure consistent application of the header across various connectors and enhance testing coverage.
* Added the `x-ms-enable-selects` header with a value of `"true"` in the `Transform` method of `PowerPlatformConnectorClient` to support additional query capabilities. (`src/libraries/Microsoft.PowerFx.Connectors/PowerPlatformConnectorClient.cs`)
* Added `x-ms-enable-selects` header to requests in multiple test methods, including `ConnectorIntellisenseTest`, `ConnectorIntellisenseTest2`, and `ConnectorIntellisenseTestLSP`. (`src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/IntellisenseTests.cs`) …
=> Adds header that enables column selection.

src/libraries/Microsoft.PowerFx.Json/FormulaValueJSON.cs, src/libraries/Microsoft.PowerFx.Json/Functions/JSONFunctionUtils.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/AsType_UO.txt, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/IsType_UO.txt, src/tests/Microsoft.PowerFx.Core.Tests.Shared/ExpressionTestCases/TypedParseJSON.txt, src/tests/Microsoft.PowerFx.Json.Tests.Shared/AsTypeIsTypeParseJSONTests.cs
Allows additional fields to be part of the input string in Untyped Object conversion functions.
=> Allow additional fields in Dynamic to Strongly typed conversion functions

src/libraries/Microsoft.PowerFx.Core/Functions/UserDefinedFunction.cs, src/libraries/Microsoft.PowerFx.Core/Public/Config/SymbolTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/DefinitionsCheckResult.cs, src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs, src/libraries/Microsoft.PowerFx.Core/Types/DType.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/IntellisenseTests/SuggestTest.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/UserDefinedFunctionTests.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/UserDefinedTypeTests.cs, src/tests/Microsoft.PowerFx.Interpreter.Tests.Shared/UserDefinedTests.cs
The body of UDFs is interpreted without the current engine features in place, the flags are not passed down and a default of Features.None ends up being used. In this example, the REPL is in V1 mode, and yet ShowColumns isn't using ColumnNamesAsIdentifiers, a part of V1:
```
>> f():Number = First( ShowColumns( [1,2,3], Value ) ).Value;
Error 42-47: Name isn't valid. 'Value' isn't recognized.
Error 20-31: The function 'ShowColumns' has some invalid arguments.
Error 51-57: Name isn't valid. 'Value' isn't recognized.
>> f():Number = First( ShowColumns( [1,2,3], "Value" ) ).Value;
>>
```
Fixing this exposed another bug where error messages could become confused: an extra field, which should be an error, would be reported as a type incompatibility in another parameter, despite coercion …
=> Plumbing Features settings down to UDF Body processing

src/libraries/Microsoft.PowerFx.Connectors/Public/ConnectorSettings.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/DefaultCDPDelegationParameter.cs, src/libraries/Microsoft.PowerFx.Connectors/Tabular/Services/CdpTable.cs, src/libraries/Microsoft.PowerFx.Core/Public/Values/DelegationParameters.cs, src/tests/Microsoft.PowerFx.Connectors.Tests.Shared/CDPDelegationTests.cs, src/tests/Microsoft.PowerFx.Core.Tests.Shared/PublicSurfaceTests.cs
This pull request introduces support for customizing OData query string encoding through a new `QueryMarshallerSettings` class. The changes allow for more flexible handling of boolean and date encodings, which is especially relevant for connectors like SharePoint and Salesforce. The `ConnectorSettings` class and related methods are updated to accept and propagate these settings throughout the query-building process.
* Added the `QueryMarshallerSettings` class, allowing configuration of boolean and date encoding in OData queries (e.g., encoding booleans as integers and dates as strings for SharePoint compatibility) (`src/libraries/Microsoft.PowerFx.Core/Public/Values/DelegationParameters.cs`).
* Updated the abstract method `GetODataQueryString` in `DelegationParameters` and its overrides …
=> Fixes SPO connector encoding.

src/libraries/Microsoft.PowerFx.Core/Public/Values/DelegationParameters.cs
Add constructor support for QueryMarshallerSettings to enable initialization in C# versions prior to 9.0
=> QueryMarshallerSettings - c#8 init support
